### ISSUE TITLE
Invocation time for polymorph seems high

### ISSUE THREAD

**Issue by istabosz** [openlegend/core-rules#10]
The casting time is 1 minute, which effectively means it can not be used in combat situations. Thoughts on reducing it to 1 Normal action?

**Comment by brianfeister** [comment]
The idea here was to require bane focus 2 for combat use. The difference between a witch that chants and the Warcraft wizard in bane focus 2 which reduces it to 1 normal action. Thoughts?

**Comment by istabosz** [comment]
That works for me. I figured there was something I was missing here.

**Comment by brianfeister** [comment]
Also, to further clarify this, and add something of a curveball here that might highlight something controversial (looking for feedback). This bane is perhaps the only one that doesn't have "Resist ends". When I designed it, it felt weird to have the target be able to "fight back" with a Resist roll to regain their physical form. So, because there is no chance to either shorten or lengthen the duration, it is perhaps quite problematic. 

Hence the long invocation time as it feels more like a mega curse / hex effect that should take time to call down on someone.

/cc @DMsShadow

**Comment by brianfeister** [comment]
closing for now, can re-open if needed
