### ISSUE TITLE
Expanded Area of Effect List

### ISSUE THREAD

**Issue by istabosz** [openlegend/core-rules#100]
I think we need to add some additional area of effects to the core rules in order to accommodate a lot of iconic spells/abilities. Here's a quick proposal for a new AoE list:

**Cube**: Disadvantage 1 per 5' length of side
- Note: this would replace our current square AoE, which is unclear as to the height.

**Cone**: Disadvantage 1 per 10' length. Cones originate at the caster and always have a width equal to their length at any give point.

**5' Wide Line**: Disadvantage 1 per 20' length

**Shapeable Wall** (such as a wall of fire): Disadvantage 1 per two 5' cubes. All cubes must have at least a touching corner.

Thoughts @brianfeister ?

**Comment by DukeAnax** [comment]
That looks oddly familiar (; 

I like the cube effect as it is better for fireball type spells, especially when you want to target flying targets.

However there are pure ground effects like quake or quicksand that affect a wide area, but have no height. Should there be a seperate Area affect kept for those? Maybe 1 Dis per 10'.

The Line and Wall have a simmilar relation to each other as Cube and Area would.

The Cone should probably mention that it has the same width **and height** as it's length.

**Comment by raihje** [comment]
I like this, and I think most people were going to homebrew it similar to this anyway. The disadvantage is fairly consistent shapeable wall is a bit more disadvantageous (vs a linee anyway which is 1D/4sq) maybe make it so it's 1D/3sq for the shapeable?

**Comment by brianfeister** [comment]
Sounds good to me. My inner rules lawyer is beginning to flare up a bit as I'm starting to wonder exactly how far behind non-supernatural attack modes are falling?

Like, I can see

| Physical Attacks| Supernatural Attacks |
| --- | --- |
| Weapon properties | Improved potential area of effect <br /> Flexible about targeting Toughness or Evasion <br /> ... feel like there are alot more I'm missing here  |

**Comment by brianfeister** [comment]
Also, 20' length on the line attack for Disadvantage 1 is OP, it should be 10' per Disadvantage 1.

**Comment by raihje** [comment]
Physical attacks from weapons are just a different stat, and occasionally easier to use certain banes depending on the weapons you picked.
Supernatural attacks are strongly superior atm, mainly in regards to targeting and the varied utilities those attributes bring outside of swinging something dull/sharp at something else.

**Comment by DukeAnax** [comment]
Now that I think about it, do we even need to specify a line shape?
The only effect I can think of that would be line shaped are walls.

**Comment by brianfeister** [comment]
I'm a bit more confused by **shapeable wall** since it's typically expected as part of a self-sustaining effect so that's slightly weird since that would be a boon, similar to `Retributive Barrier` and banes don't have a sustain effect.

**Comment by brianfeister** [comment]
Also, I think Disadvantage 1 per 5' cube is fine for shapeable wall, since it's ultra-flexible... though that does invalidate the area X by X area attacks since you don't have any risk associated with areas and no need for the feat that allows you to exempt one square. Stilling pondering, but pretty sure I'm opposed to **Shapeable Wall**

**Comment by istabosz** [comment]
For line effects I was imagining things like lightning bolt, laser beams, that sort of thing. And you're right @brianfeister , it should be Disadvantage 1 per 10'. I was fiddling with several iterations and wrote the wrong one I think.

Regarding shapeable walls, I was trying to think of a way to generalize wall effects so they could be created using pre-existing banes and boons. Retributive barrier, for example, only affects a target person. But how would they create a wall of fire? Or a ring of fire?

@DukeAnax Regarding the square effect. I think if we need one it should have the same disadvantage as the cube. Mechanically speaking the two are almost always equivalent in power because combat very rarely actually takes place in three dimensions.

**Comment by brianfeister** [comment]
My thinking about the **Shaepable Wall** is that it should actually be **Retributive Barrier** and we should make all of our changes over there on that boon. I played a game where someone invoked **Retributive Barrier** and was sorely disappointed by it's effect. What we might do is layer extra effects on the tiers of it so that it can ultimately become impassable or maybe "uses 15' of movement to pass through one 5' cube". 

There is also the other question about terrain shaping, but I would say that's a separate boon since it's Alteration-based and this is Energy/Entropy/etc.-based

**Comment by raihje** [comment]
Retributeive Barrier is pretty weak. If it was any enemy entering/starting their turn in that space then it'd be a bit better, but as it is it's a 5' square that's pretty easily avoided. For shapeable wall, dis /sq and require that each square be attached to the next means it will be quickly outpaced by area effects in terms of disadvantage. Area attacks will be much easier to pull off than large walls.

**Comment by istabosz** [comment]
Maybe we need to generalize Retributive Barrier then into just Barrier. And then have a menu of shapes and effects for the caster to choose from, such as deal damage, stop movement, or apply a bane. That would allow us to create several effects, such as wall of force, ring of fire, and wall of fog. I can take a crack at drafting that if you want.

**Comment by raihje** [comment]
It shouldn't be impossible to combine effects, such as a wall of thorns ejecting poison or thorns at nearby enemies, or the intense flames preventing movement and giving burns to people nearby, just have it similar to the illusion/phantasm that it's combined power level for effects.

**Comment by brianfeister** [comment]
Proposal sounds good @istabosz

**Comment by DukeAnax** [comment]
Well, according to the combat chapter, boons are supposed to use the exact same targetting as attacks and banes, that would include Shaped Wall. And that makes sense because it keeps things simple.

When first reading the boon I actually missed this line: "Designate a willing target or a 5' square that is not occupied by an enemy." because I thought targetting was already handled elsewhere. I'd been perfectly happy tp declare a 4' Area or Cube or 30' Wall of Retributive Barrier.

So to keep the boon in line with expections, it shouldn't define targets, size or shape, just the effects like damage and restricted movement.

"While this boon is active, it has one of the following effects:
Any enemy that passes within 5' of the Barrier takes damage
Any enemy/ally that passes through the Barrier has increased movement cost
..."

**Comment by raihje** [comment]
I agree with @DukeAnax here. Expanding the area effects for all effects is better than giving one boon a couple extra imo.

**Comment by raihje** [comment]
Cube, Line, Cone, and Circle should be shapes easily demonstrated. Circles for those times you're character thunderclaps or puts out some kind of shockwave ability, lines for lasers, various walls, Cone for flamethrower and color spray like effects, and Cube to clarify the current square effects.

**Comment by brianfeister** [comment]
I think I would call `Circle` radius, personally and make it only target squares adjacent to a creature that you choose. Also I think `Line` should be clear that it doesn't have to extend or connect with the invoker so it could be a fissure of necromantic hell energy that springs opens from a crack in the earth. 

My only real problem is how to calculate the disadvantage for the `Radius` shape I'm describing. I suppose it's OK from a balance perspective to just make it `Disadvantage 3` (I think 2 would be too easy for targeting 8 squares in most situations). Being able to shapeshift / alternate form into a larger size to get extra `Radius` effect squares I think would be rare enough / expensive enough that `Disadvantage 3` might cover it.

**Comment by DukeAnax** [comment]
@brianfeister  I think the word you are looking for here is Aura, something that sticks to a target and affects the adjacent area. I'd make it Disadvanatge 3 per 5' though. Mainge it bigger at that cost seems save, because Cube is cheaper.

I'd love to put an Aura of Regenerartion on my Druid and a Warlock could throw an Aura of Permanent Damage (Pestilence) at his foes.

**Comment by istabosz** [comment]
Not a fan of the term "radius" for an area of effect, as it's a bit of a misnomer. I'd prefer Ring, as it implies circular with nothing in the middle. I think a fair penalty for it would be disadvantage 2 per 5' diameter. That's kind of hard to imagine without a visual, but it means disadvantage 2 allows you to encircle a 5'x5' area (or 1 creature); disadvantage 4 allows you to encircle a 10'x10' area (or 4 creatures); disadvantage 6 allows you to encircle a 15'x15' area (or 9 creatures); and so on.

**Comment by DukeAnax** [comment]
Ring is something else again as what we were talking about specifically had an inside.

But Ring could be jet another shape that can be placed freely. Want to stop the fleeing fugitive without killing him? Make a Ring of vines around him.

**Comment by DukeAnax** [comment]
So if I see it right we would have these 5:

Freely placed:
Cube - 1 Disadvantage per 5' length of side
Line - 1 Disadvantage per 10' of length at 5' width and 20' height
Ring - 2 Disadvantage per 5' diameter at 5' thickness and 20' height

Originating from the caster:
Cone - 1 Disadvantage per 5' of length at same width

Originating from target (which can be the caster):
Aura - 3 Disadvantage per 5' of radius

To accomodate the idea of Shapeable Wall, I'd just say that the line doesn't have to be straight.

**Comment by raihje** [comment]
Aura should large be the same as Cube, just with the center square out. I think it might be reasonable to have the Aura 2D/r

**Comment by istabosz** [comment]
Yep, @DukeAnax I think that's where we're at.

The 20' height for the line seems a bit silly, now. It makes sense for walls, but not lightning bolts or laser beams. I suggest we reduce it to 10' height.

Ring has pretty clunky mechanics (which I take full responsibility for, as I wrote them). I think we can get rid of Ring if we just allow lines to be constructed contiguously. That way, you can encircle an enemy if you need to.

**Comment by DukeAnax** [comment]
True, if you draw the lines like this:
OXO
XOX
OXO
and 
OXXO
XOOX
XOOX
OXXO
It would be the same Disadvantage as Ring has, so that works.

**Comment by istabosz** [comment]
I'm thinking that aura is such a unique effect, in that it follows the target around, that it doesn't merit being included in the standard area effects. Casters can already create an area attack that doesn't include them by using the Area Manipulation feat.

For auras, we probably need a separate boon called Aura. Not that I want to add another boon, but it does seem like a worthwhile one.

**Comment by DukeAnax** [comment]
I'm not sure that boon is the right thing for what Aura was meant to do. For example the Idea of an Aura Barrier. You'd have a boon that has a boon that applies a bane. Even just a Heal Aura would stack two boons.

But you are right that it is a unique form of targetting. I think Aura Caster would work better as a feat.

**Comment by brianfeister** [comment]
@istabosz as much as I hate to admit it, I'm also excited about the `Aura` boon since it can represent a super common and beloved effect from video games, Paladin's with a healing aura, demons with a fiery, aura, etc. I'm excited to see what you come up with

**Comment by brianfeister** [comment]
@DukeAnax I'd rather not see it as a feat, really strange mechanical break from the existing pattern where you never expend character building points just to shape an effect

**Comment by brianfeister** [comment]
@istabosz nudging you ont this

**Comment by istabosz** [comment]
Just committed the new AoEs

**Comment by brianfeister** [comment]
Re-opening -- the change was not made in the SRD

**Comment by jcte02** [comment]
@brianfeister This was merged in #192. Can close issue now
