### ISSUE TITLE
The Long-Requested Summoning Boon

### ISSUE THREAD

**Issue by brianfeister** [openlegend/core-rules#113]
The following was proposed on https://openlegend.mightybell.com/posts/947284/comments/862546. There are a number of rough edges, but I'm posting this here now because this does not seem like it's going away. I see this request probably more than any other.

---

Summon (Boon)
Having studied the rules, there doesn't seem to be a native rule for summoning creatures into play.  I have always loved the old trope of wizards summoning hordes of beasts to fight, or mad scientists and unleashed horrors, so I wrote this boon in case anyone wanted to apply it in their game or give it a solid balancing check, as I'm presently a little wary of it being too OP.  Taking a cue from the Animate boon, the boon provides no innate ability to control summoned creatures, but I have tried to balance a swift conjuring time with the need to sustain the boon.  I would appreciate someone breaking this so it can be fixed better.

Summon
Duration: Sustain Persists

Invocation Time: 1 Major Action

Power Level: 4 / 5 / 6 / 7 / 8 / 9
Attributes: Movement
Description

You summon temporary creatures from another plane or distant location.

Effect

Invoking powerful arcane summons or your matter transporter ray, you are able to summon creatures from other planes or dimensions, or simply from far away, bringing them to a location within 25 feet of you.  The creature or creatures remain where summoned until you cease to sustain the boon or until they are killed or subject to the Banished bane.  Killed summoned creatures' bodies return to their home plane upon death.  This spell grants no special control or influence over any summoned creatures.

Special:  The character that invokes this boon cannot wilfully dismiss their summoned creatures for 1 full round, short of killing them.  Other characters may be able to kill or Banish summoned creatures before this time limit is expended.

Power Level 4 - You can summon a single creature of animal intelligence.  The creature's highest attribute score must be at least 2 points less than your attribute score.

Power Level 5 - After summoning a creature, on the same round as invoking this boon, you may attempt to apply either the Dominated or Charmed banes to your summoned creature as a minor action, provided you have sufficient Influence.  NB: Multi-targeting penalties still apply when attempting to Dominate or Charm multiple summons.

Power Level 6 - You can summon multiple creatures.  For a single creature, the creature's highest attribute score must be equal to or less than your attribute score.  For multiple creatures, any creature's highest attribute must be at least 3 points less than your attribute score.  When invoking this boon for multiple creatures, you apply Disadvantage equal to the number of creatures being summoned (e.g. summoning 3 Ghasts applies Disadvantage 3 to your check).

Power Level 7 - You can summon a single creature of human intelligence or multiple creatures of animal intelligence.  When summoning multiple creatures, any creature's highest attribute must be at least 2 points less than your attribute score.  You gain Advantage 1 on Dominating or Charming your own summons.

Power Level 8 - You can summon one or more creatures of human intelligence.  When summoning multiple creatures, any creature's highest attribute must be at least 1 point less than your attribute score.  You gain Advantage 2 on Dominating or Charming your own summons.

Power Level 9 - You are able to truly bring summoned creatures to you.  A single 'called' creature may be summoned truly to your location; once 'called' it does not need to be sustained in place.  The called creature cannot be dismissed by its summoner without Banishment.  If killed, the creature's corpse (if any) will remain on the plane rather than returning to its home plane.  A called creature can still be Banished.

You may not call more than a single creature with a single invocation of this boon.  Calling creatures in this manner takes 1 full hour, rather than the normal action time of 1 major action.

**Comment by DukeAnax** [comment]
I'm not sure about the Movement though, temporarily teleporting something makes little sense and with Movement you'd also have the problem of locating a suitable target.

I think more sense would make Entropy for Demons, Protection for Divines and Energy for Elementals.

Maybe Movement could give you the advantage of permanent summoning, while the others get advantage to controlling.

**Comment by Elvenoob** [comment]
I agree more with movement, both due to the 9th level permanent version, and due to the fact that you are indeed "moving" them to you, even if it snaps back to it's own natural location after a while.

But, I also agree more with the original stance of "No, temporarily summoning things doesn't really make sense at all."

In other fantasy series not tied to a game mechanic, let's use the Bartimaeus novel series for the most relevant example, the summoned spirits do not return to their own original place after a set amount of time, or even when they die, they specifically have to be banished by a human operating a magic circle.

I'd say, giving summoned creatures a specific shout-out in the companion feat and Animation boons (Maybe let it use Movement as an attribute for summoning spirits from other planes.)

**Comment by DukeAnax** [comment]
Maybe just rework Animation into Summon to include both?

Animation could be seen as a special case of summoning from nothing.

**Comment by raihje** [comment]
This seems quite a bit stronger than animation, no reagents needed poof here's a monster (hopefully) under my control. Granted it needs to be sustained which is a nice balancing feature, if someone disrupts you that might mean you lose control of the summon (no longer able to banish them without inflicting the bane)
I agree with Energy for Elementals (this would be more 'conjuring' than 'summoning') Entropy for Undead, Creation for your normal living stuff, Movement for stuff far removed from this plane or physical place, and maybe Alteration for your classic 'constructs' or golems - tbh this might be a better addition to Animation than movement as I think someone above mentioned.

**Comment by Elvenoob** [comment]
@raihje Who said no reagents needed? In all summoning lore I've known so far (that is, only counting  novels and some movies, not games), that's not been the case, not only has there been necessary reagents, usually burning incense and that kind of thing, there's also usually a summoning circle (Mistakes on drawing this could be _very_ interesting in the OL system) and ritual required.

**Comment by raihje** [comment]
Animation requires fur, bones, something. This is "poof I have a minion" as a boon, lol. Open Legend goes a long way towards abstracting things. Rituals are more or less covered in ritual casting, although a circle or something (within 6 seconds) would be interesting.

**Comment by twystedcures** [comment]
I think adding more attributes, such as energy, creation, entropy, and alteration would be good, as has been said. 

Conjuration and summoning are part of traditional playstyles for a lot of gamers. 

This allows for something closer to Final Fantasy style summoning, or the summoning you would find in Skyrim. These games are important points of reference for a lot of new gamers. 

It's important to consider other genres/references in a system that is multi-genre. 

I know you don't like summoning, Brian, but it's really cool that you're listening to your supporters' feedback.

**Comment by raihje** [comment]
So we agree add more attributes. I think this boon is a pretty good start, just make each attribute feel unique in what it's bringing forth and you have a good boon on your hands.

**Comment by Elvenoob** [comment]
This was an early first draft, @raihje , and if we were to add the Movement attribute, and thus summoning, to the Animation boon, then it would of course have to be tied in line to the other attributes used by requiring those kinds of material components.

@twystedcures I think you have the wrong idea here, one of the things I liked the most about Open Legend was that it brings the RPGs back towards the Storytelling focus, and a significant shift in the way Summoner-type characters work, to a more realistic, less gamey style, seems like a very fitting way to drive that idea home.

**Comment by raihje** [comment]
Summoning and Animation can be separate, that's cool. I'm just saying the attributes should be unique. Animation may not be able to use Movement (intense telekinetic forces maybe keep whatever material around together, sure) but it makes sense to at least add Energy (elementals) to Animation. I'm not sure about Alteration/Movement and Golems/random matter being compelled to move magically or "magic-mechanically" but one of those should probably be added to Animation as well.

**Comment by Elvenoob** [comment]
Yeah, I'm the one who's saying, merge 'em together, there's no need for summoning to work on different mechanics to what we already have for making minions through boons.

**Comment by istabosz** [comment]
I think this is a good start, but could use some streamlining so that every PL doesn't introduce new rules. I also think we should assume that the summoned creature is under the control of the summoner, rather than requiring separate checks to charm.

Since we don't have a bestiary, I say we just specify the Hit Points, defenses, and attribute build available at each power level. Something like this:

PL 3: 10 hit points; Defenses 10; attributes 2, 1, 1
PL 4: 12 hit points, Defenses 11; attributes 3, 2, 2
PL 5: 15 hit points, Defenses 13; attributes 4, 3, 3
etc...

That's just for example. Haven't thought about balance yet. I'll do that if people like this model.

**Comment by brianfeister** [comment]
Love the general approach @istabosz

**Comment by istabosz** [comment]
Here's a shot...

# Summon Creature

**Duration:** Sustain Persists

**Invocation Time:** 1 Focus Action

**Power Level:** 4 / 5 / 6 / 7 / 8 / 9

**Attributes:** Creation, Entropy, Energy, Alteration

**Description**
You summon forth creatures to assist your cause, whether they are animals called from the wild, undead minions built from the remains of your foes, or worker bots constructed of spare parts from a salvage yard.

**Effect**
You create or summon forth a temporary NPC companion that is under your control though of limited intelligence. It has stats according to the power level of this boon. You may assign the attributes as you see fit among the following attributes: agility, fortitude, might, perception, energy, and entropy. The creature acts on your turn and gets the usual assortment of actions.

**Special:** This boon is not subject to normal multi-targeting rules. However, you may use a single invocation to summon multiple creatures. For each additional creature summoned beyond the first, you suffer an additional disadvantage 2 on your action roll to invoke.

| Power Level | Hit Points | Defenses | Attributes |
| --- | --- | --- | --- |
| 4 | 5 | 10 | 2, 1, 1 |
| 5 | 7 | 12 | 3, 2, 2 |
| 6 | 9 | 13 | 4, 3, 3 |
| 7 | 11 | 14 | 5, 4, 4 |
| 8 | 13 | 15 | 6, 5, 5 |
| 9 | 15 | 17 | 7, 6, 6 |

**Comment by brianfeister** [comment]
@istabosz it's beautiful to see written out! I think it's perfect. I worry slightly about specializing here to be able to regularly and easily summon 2 or 3 minions that each have their own shot at a d20 explosion, but despite that, I don't think Disadvantage 3 would work, so I think you've nailed it.

**Comment by DukeAnax** [comment]
Agreed. There needs to be some clarification about what "temporary" means though.

If summoning several creatures is too strong how about this to play with: `For each additional creature you summon, all creatures are one power level lower than normal.` So you could summon one of power 6 or three at power 4.

Also how complete do you want these attribute lists to be? 
Animals called from the wild should be Influence and Guardian Angels could be called with Protection.

On the other hand, I struggle to see Alteration produce a creature.

PS: it's astonishing how much you can polish a nail when you want to, lol (;

**Comment by brianfeister** [comment]
@DukeAnax LOL. I thought temporary was pretty clear - it's a Boon with "sustain persists" so the creatures last as long as you sustain.

Alteration is for sentient plant minions animated by your power of puppetry / warping.

**Comment by brianfeister** [comment]
And also, no no no, all of them are the same @DukeAnax, you get multiple identical ones

**Comment by istabosz** [comment]
I'll bring up the elephant in the room... Boon Focus Tier 3. Doesn't quite make sense with this feat without a little clarification. I can see two options:

A) You can have one summoned creature without sustaining the boon.

B) We could give Summon Creature a duration of 10 minutes instead of Sustain Persists and just stipulate that additional invocations cancel out any previous ones.

I like option B, as it is nice and clean.

**Comment by istabosz** [comment]
Also, in regards to the previous discussion of lumping Animation in with Summon Creature, I think we should just add an option at tier 6 and above: "You may voluntarily increase the invocation time to 8 hours in order to make the duration of this boon permanent."

**Comment by brianfeister** [comment]
I'm down with lumping the two boons together. Slight reservations, but nothing major.

Regarding **Option A** vs **Option B** I'm wondering about a possible **Option C** because B has a problem for me, it can be abused via "stacking" -- if the creatures last for 10 minutes, I could do "battle prep" for 1 minute to summon 10 creatures that will last for 9 minutes of combat, etc.

**Comment by raihje** [comment]
Except any invocation cancels previous ones, so it'd just be one over and over again.

**Comment by DukeAnax** [comment]
@brianfeister yeah, brain fart on my part on both accounts (;

I did mean that all of them would be identical, just that all of them would be of a lower power level, pretty much the same as would happen with higher disadvantage but with less random.

**Comment by brianfeister** [comment]
@raihje - not sure if that was a suggestion, but I like that idea, that summoning new ones cancels the previous. 

@istabosz - found a new (probably worse) loophole though. If I summon 3 of them and then 2 get taken out. I just use my Major Action to a "refresh" of 3, so it's like having infinite meat shields... not so sure I like that aspect.

**Comment by Elvenoob** [comment]
^
One of the reasons I think the Open Legend system should play with Summons in a different way, there's no resources required & spent to limit them like there is the user's mana and skill cooldowns in MMOs, or spell slots in things like D&D.

**Comment by istabosz** [comment]
@brianfeister Yea. Canceling out extra summons was part of Option B. Re-read it above and you'll see.

Regarding the constant meat shield problem, that's one of the reasons I made it a focus action rather than major action, just to bump up the cost a bit. But perhaps this boon just needs a limitation that says "Once you have successfully invoked Summon Creature, you cannot invoke this boon again for 10 minutes." If we did that, I'd drop the casting time down to a major action.

On the other hand, is it really that OP to be able to constant summon? It's worth thinking about what you are sacrificing when you use your turn to summon. You aren't making a damaging attack. You aren't sustaining a boon (assuming we leave the casting time at 1 focus action). You aren't attempting to stun, or fatigue, or slow someone with a bane. And what you get for not doing those things is a minion who can be taken out with an attack roll of 15 (at PL 4). If you summon a creature and it gets taken out before your next turn when you get to use it, you've spent your action to cancel an attack, basically. If the creature does survive for you to get an attack with it, it's not a particularly strong one. I think at PL 4, Summon Creature is actually pretty balanced. The HP and defenses at higher PLs just need to be tweaked so that the survivability of the the minions doesn't get too intense. Here's a new proposition:

| Power Level | Hit Points | Defenses | Attributes | Roll to Kill |
| --- | --- | --- | --- | --- |
| 4 | 4 | 11 | 2, 1, 1 | 15 |
| 5 | 5 | 12 | 3, 2, 2 | 17 |
| 6 | 6 | 13 | 4, 3, 3 | 19 |
| 7 | 7 | 14 | 5, 4, 4 | 21 |
| 8 | 8 | 15 | 6, 5, 5 | 23 |
| 9 | 9 | 16 | 7, 6, 6 | 25 |

The **Roll to Kill** is just a sum of HP + Defense to demonstrate what it would take to one-shot a minion. I won't put that column in the actual boon text.

**Comment by brianfeister** [comment]
@istabosz I think I might be OK with removing all limits, I'd like to introduce a "slowdown" factor that is the same as what I've done in most other places mechanically, like the `Dominated` bane we need a `Command` aspect here. Here's my proposal, I think it will "slow down" invokers enough to de-incentivize a cancel/re-summon loop when combined with your Focus action invocation:


# Summon Creature

**Duration:** Sustain Persists

**Invocation Time:** 1 Focus Action

**Power Level:** 4 / 5 / 6 / 7 / 8 / 9

**Attributes:** Creation, Entropy, Energy, Alteration

**Description**
You summon forth creatures to assist your cause, whether they are animals called from the wild, undead minions built from the remains of your foes, or worker bots constructed of spare parts from a salvage yard.

**Effect**
You create or summon forth a temporary NPC companion that is under your control though of limited intelligence. It has stats according to the power level of this boon. You may assign the attributes as you see fit among the following attributes: agility, fortitude, might, perception, energy, and entropy. 

The creature acts on your turn and gets the usual assortment of actions. The first turn that you invoke this boon, you also issue a simple command that it can understand (assign a Logic score to your NPCs if you want them to comprehend complex instructions) and it attempts to carry out that command indefinitely. You can use a major action to issue a new command, such as attacking a different target, or protecting a different ally.

**Special:** This boon is not subject to normal multi-targeting rules. However, you may use a single invocation to summon multiple creatures. For each additional creature summoned beyond the first, you suffer an additional disadvantage 2 on your action roll to invoke.

| Power Level | Hit Points | Defenses | Attributes |
| --- | --- | --- | --- |
| 4 | 5 | 10 | 2, 1, 1 |
| 5 | 7 | 12 | 3, 2, 2 |
| 6 | 9 | 13 | 4, 3, 3 |
| 7 | 11 | 14 | 5, 4, 4 |
| 8 | 13 | 15 | 6, 5, 5 |
| 9 | 15 | 17 | 7, 6, 6 |

**Comment by istabosz** [comment]
So, @brianfeister I don't think your proposed solution actually addresses the issue. Since they get to issue a command as soon as they summon, there is nothing to stop them from re-summoning when their minions are dying off. They've still got a constant meat shield, and since you've upped the HP again, they've got really GOOD meat shields.

If you aren't a fan of my reduced stats, maybe we just need to add a clause to slow down re-summoning: "Once you cease sustaining this boon or once all of your minions are defeated, you cannot invoke this boon again until one full round has passed."

**Comment by DukeAnax** [comment]
Keep in mind though, that the use of meat shields is somewhat limited in live rpgs, as you can't trick any AI into attacking them. If the GM pops out some Rangers or Mages or maybe even an Assassin type, they can be bybassed.

**Comment by brianfeister** [comment]
@istabosz actually we need some careful wording to communicate the intent, so let's fix the wording. 

My proposal actually intends that you use a focus action to summon them but they act on the NEXT turn, so if I decide to re-summon, that needs to kill existing ones (they die and don't act this round) and the issued command does not get executed until the following turn. This caused the invoker to lose 1 round and then if they need to change commanded targets etc. they lose a round for that as well.

**Comment by DukeAnax** [comment]
The solution here could be to do the exact opposite: Each boon action can only summon one creature, but the next invocation doesn't cancel the previous. That way the summoner has to conjure them faster than they are destroyed while still having extra actions to adjust the commands. 

I really like this solution because it mashes well with Superior Concentration. (maybe too well?) And the disadvantage on summoning further creatures makes it harder and harder to replace your dying minions with equally strong ones.

Also I'm not too worried about meat shields in live RPGs anyway. A decend GM can deal with that, a swarm of his own to overhelm them, a Mage to annihilate all of them at once, a Ranger or Assassin to simply ignore them.

# Summon Creature

Duration: Sustain Persists (special)
... 
issue a simple command
...

Special: This boon is not subject to normal multi-targeting rules. **_However, you may sustain any number of this boon equal to half the Attribute used_**. For each additional creature summoned beyond the first, you suffer disadvantage 2 on your action roll to invoke.

**Comment by raihje** [comment]
New summons replace old summons, summons cannot be revived with a focus action. Seems simple enough imo, leave it with the power level idea @brianfeister put forth. Make it a focus action to cast, but a major or minor to sustain. They can't do much else if they're sustaining anyway (at least for boon) And those summons will die off until they can put the effort into summoning more (with dis. 2 per extra, no less)

**Comment by brianfeister** [comment]
@istabosz awaiting your feedback on this

**Comment by istabosz** [comment]
Sorry. Muggle life got in the way for a bit there.

I'm good with @brianfeister 's revisions. I'll add them in if there is nothing left to discuss.

**Comment by istabosz** [comment]
Okay. I take it back. As I was trying to write this up, I just can't get over how messy it is. The issuing of commands limitation just opens up too many questions: If I tell my minions to defend me, does that mean they only take the defend action? Or could they also attack? Do I issue the same command to all of my minions, or can I give different minions different orders (and does it take a separate major action for each minion)? If I command my minion to attack an orc, and then the orc dies, does my minion stand there like an idiot until I spend a major action to change his orders?

Plus, I think having to waste the action to change commands just lacks in the fun department. If I build a character to be a summoner, I want to have control over my minions and I want it to be easy. I don't want to have to decide whether or not to cast another spell or to command my minions, especially because I'm already paying to sustain the boon.

I really think that my latest proposal does a pretty good job at keeping the fun without making re-summon loops OP. So, I'd kinda like to hear what you think doesn't work about that proposal.

**Comment by brianfeister** [comment]
@istabosz I think you're right about the command aspect, good observation, it's overly complex and less fun.

I think all I really wanted to accomplish was a small buffer that prevents the creatures from acting on my first turn. If each re-summon causes me to miss a turn, then it demotivates summoning loops for gamebreaking and means that it will only be used because it's legitimately a key character story thing.

Also, since the boon is `Sustain Persists` that prevents you from using an existing minion on the turn that I summon a new one. I think all I really want is a caveat like:

`Special: You use the same sustain action to both keep the boon active and control the creatures, so the creature(s) first act on the round following your invocation`

**Comment by DukeAnax** [comment]
No need to make it special, regular rules already cover this.

Just state that controlling minions is a minor action.

Since you can do any number of minor action you can do that control action as well as the sustain action, but you can't do it on a focus action.

@brianfeister maybe im missing some detail on the Core rules here, but I don't see how Sustain Persists on it's own would prevent you from using the old one and making a new one.

**Comment by istabosz** [comment]
Yea, I actually envisioned minions not acting on their first turn, but just didn't put it in the text. Here is my latest draft for consideration. I also added the bit about making the summon permanent to replace the animate boon:

# Summon Creature

**Duration:** Sustain Persists

**Invocation Time:** 1 Focus Action

**Power Level:** 4 / 5 / 6 / 7 / 8 / 9

**Attributes:** Creation, Entropy, Energy, Alteration

**Description**
You summon forth creatures to assist your cause, whether they are animals called from the wild, undead minions built from the remains of your foes, or worker bots constructed of spare parts from a salvage yard.

**Effect**
You create or summon a temporary NPC companion that is under your control, though of limited intelligence. Your minion's statistics are determined by the power level of this boon. You may assign the attributes as you see fit among the following: agility, fortitude, might, perception, energy, and entropy. Your minion's attributes do not affect their hit points or defenses.

| Power Level | Hit Points | Defenses | Attributes |
| --- | --- | --- | --- |
| 4 | 4 | 11 | 2, 1, 1 |
| 5 | 5 | 12 | 3, 2, 2 |
| 6 | 6 | 13 | 4, 3, 3 |
| 7 | 7 | 14 | 5, 4, 4 |
| 8 | 8 | 15 | 6, 5, 5 |
| 9 | 9 | 16 | 7, 6, 6 |

Your minion cannot act on the turn that it is summoned. On each of your following turns, your minion acts on your initiative count and receives the usual assortment of actions. If you invoke this boon while you already have minions summoned, your current minions are immediately dispelled.

**Permanent Minions:** At Power Levels 6 and above, you may choose to increase the invocation time to 8 hours. If you do so, your minion exists permanently and does not require a sustain action to persist, nor is it dispelled when you invoke this boon to summon temporary minions. The maximum number of permanent minions you may have at any time is equal to your attribute score minus 5.

**Special:** This boon is not subject to normal multi-targeting rules. However, you may use a single invocation to summon multiple creatures. For each additional creature summoned beyond the first, you suffer an additional disadvantage 2 on your action roll to invoke.

**Comment by brianfeister** [comment]
:100:

**Comment by ThirteenStrings** [comment]
Sorry to chime in on this... It's been a long thread and I hope I'm not just being ignorant. 

I thought you changed boons so that the power level is determined AFTER the roll. However, this write up makes you pick the desired power level before the roll and then aim for it. Feels to me like this is in contradiction to why you changed the boons. Could this be slightly tweaked in some way so that the roll determines the minions summoned instead of having to pick a number and have only pass/fail?  

I know it makes the boon slightly stronger without the disadvantage being factored. Perhaps the CR for each power level can be modified to make it harder to summon multiple minions while at the same time not forcing the player to guess at a single level and hit it.

Maybe I'm just missing the point, again sorry, I know how long this boon has been an issue.  I think every single part of it except my mentioned problem is awesome. Thanks for all your hard work gentlemen.

**Comment by istabosz** [comment]
This boon works just like others. Make your roll. That determines your power level. Your power level determines the strength of your minions.  If the wording was unclear, let me know where you got the impression that it worked differently.

**Comment by ThirteenStrings** [comment]
I deleted my comment shortly after. Apologies, I realized my error. Apparently it still shows up for you? Anyway, it's a solid boon, thanks!

**Comment by DukeAnax** [comment]
Only one thing: If Hit Points and Defenses are fixed, why assign attributes to Fortitude?

Also why is it even fixed in the first place? Simple build is quick and easy in combat, but a lot of Players I know would want the option of complex build. Most of the time they would use the same premade minions anyway. But if I''m up against a Telepath I'd like something with more resolve.

Also why not the other attributes? As it stands minions are just meatbags that can only attack, what If I want somethign like a Mindflayer? Or how about a healing minion, would that be OP?

I don't know the games balance nearly as well as you guys, but at first glance it only seems to restrict Fun. Wouldn't it be better to leave that between the Players and GM?

**Comment by brianfeister** [comment]
@DukeAnax - that's an interesting point about Fortitude that @istabosz and I should address, I think. My guess is that we should remove Fortitude as an option since it factors into HP and Defense scores, which are fixed.

I suppose we could just put the attribute point total column for people who want to build their own minions. I know the goal is to reduce complexity, and we definitely will break the game if we let characters build entirely custom NPC creatures with this boon, but we could give an attribute point allowance for custom builds. 

I'm really concerned about giving access to supernatural attributes, creation being a great example. It would be a very OP loophole for me to take **Boon Focus: Summon Creature** (interesting here that this would allow me to summon creatures more quickly (I've updated the feat text to include the focus action invocation impact) + **Superior Concentration x 3**. I could summon 4 minions any time with auto-success, and give each of them a Creation score, meaning I have 4 "healing batteries" making me virtually unkillable. So, yes, we need to disallow access to most attributes. If you want a necromancer with a insubstantial Shade creature, that's actually a case for using the **Companion** feat where you pay the cost and get full customization. We can't give full customization for this because it's a **boon** which means it's very easy to access and doesn't require much sacrifice to gain access to.

If you can give **ANY** attribute to a minion, that would essentially make it possible for a character with access to "Summon Creature" to gain access to every single bane and boon in the game, and have an infinite flexibility in solving problems the GM might throw at them.

You Paladin's guardian angel either needs to be represented by using **his** Creation score to heal (and the Guardian Angel is the flavor text that explains it) or take the **Companion** feat, which I personally think would be AWESOME, to have a Companion Guardian Angel with the Creation attribute.

**Comment by DukeAnax** [comment]
Right, makes sense, thanks for the complete explanation!

**Comment by istabosz** [comment]
The problem with allowing custom minion builds is that it opens the door for more questions and allows for more min/maxing. We'd have to specify the maximum attribute score for each Power Level, which complicates the feat further. At PL 9, I'd have 70 attribute points, so I could build a 7, 7, 4 which seems a bit more optimized than a 7, 6, 6. I think that Companion is also a better fit for people who want to customize their minions.

Regarding the attribute selection, I'm imagining minions as mostly being used for grunt work, simple combat, and meat shielding. I think allowing presence would be awkward, because that means you could summon a minion to give a rousing speech or lead an army. Plus, Presence gives access to the heal boon. It just seems beyond the scope of the boon which specifically summons creatures of limited intelligence. I stuck to mostly active attributes, which is why I left Will out. I included Fortitude for things like summoning camels to transport goods through the desert.

**Comment by brianfeister** [comment]
@istabosz comment gave me a revelation about something I could build that never even occurred to me. I could actually take the **Companion** feat many times to have a growing entourage of minions. Instead of upping the Tier of the **same** companion over and over, I could have an array of lesser powered minions. Man, I actually **LOVE** the idea as I'm thinking of it, like a Druid with a whole array of different beasts, even magical ones and creatures with Supernatural attributes. 

At the end of the day, I agree all we are really talking about here is a request to be able to do what the Companion feat is specifically made for, without spending the feat points. So I prefer to keep it as is with the only customizability being the selection of the 3 attributes.

Interesting about Fortitude-based camels, LOL. I hadn't thought of that.

**Comment by DukeAnax** [comment]
Oh I wasn't opposed to the stat array, I agree that using attribute points would be too much. I'm just not sitting well with fixed defenses. It's an OK hack to help out GMs improvise combat, but as a player I don't really like it.

After you pointed it out I see that Presense and Will would be weird. So what about the reverse: If they are grunts without Presence or Will, why would they have Resolve? Actually them having that weakness seems a good idea.

What do you think about this? 
HP is Power + Fortitude, (That's right between both the tables posted) 
Toughness is 10 + Fortitude and Evade is 10 + Agility. (they'd get less or same)
Resolve is always be 10?

**Comment by istabosz** [comment]
My thought on the standard HP and defense was just for simplicity's sake. So that the summoner wouldn't have to worry about balancing their minion stats just right or be able to over-optimize based on the enemy. The main benefit behind the boon is to be able to tie up foes, make moderately effective attacks, provide meat shields, etc. so I just don't think it's worthwhile to add other layers of complexity.

If we were to allow varying Defenses, I wouldn't want to introduce new formulas, as that would just be extra bloat for little payoff. If we used the standard formulas, that would mean we'd have to allow will and presence to be thrown in the attribute mix.

**Comment by brianfeister** [comment]
I agree that we should keep variable defenses out of it. Unfortunately the desire to optimize here is the exact thing that I think we shouldn't be appeasing with this boon. Especially not in the core rules. So this will be a case where people need to house rule custom defenses with their GM.

**Comment by istabosz** [comment]
K. Let's add it to the core then. I dunno the syntax for formatting tables in the feats file, though. It's not the same as in markdown is it?

**Comment by brianfeister** [comment]
Yeah it's different but similar. I'll do it. Let's go over the how-to in person soon so you know too

**Comment by DukeAnax** [comment]
Fiar enough, kinda what I expected, but it was worth a try (;
