### ISSUE TITLE
Alternate Form: Not quite done. (Sorry, I know. Just polish this time.)

### ISSUE THREAD

**Issue by Elvenoob** [openlegend/core-rules#114]
We never did actually end up clarifying a few important things about Alternate Form, such as what happens to the character's inventory, and how to represent things like a Dragon's natural weapons 

(I've just been using the stat blocks of normal weapons from that table to represent innate things like claws (Greatsword) or tails (Glaive), but maybe a paragraph about that in the character creation section might be useful, since people might just straight-up make a dragon who doesn't turn into an elf, or some other kind of non-human race like a centaur with it's hooves... And this is me reigning in the crazy, I've had some outright ridiculous ideas about things I could do with this system. And I love it. Back on topic...)

So, not only is the problem we noticed earlier about the inventory not entirely clear when it comes to this new version of the feat, but...

There's new problems. Hit Points.

You can have form A and form B's max HP at different levels.

There's an easy solution, simply tell that player to track how much damage they've taken, and apply that to both forms, but then, you have to clarify what happens in this one nasty little case:

Form A has 4 more max Hit points than Form B, so if you're reduced to, let's say, 2 HP in form A, and then transform to form B, what exactly does that do?

It doesn't make sense for your character to outright faint (Well, I could see it for a lot of situations, sure, I admit that, but not all of them), but you _are_ on 0 HP.

**Comment by DMsShadow** [comment]
Because @Elvenoob and I have been discussing this on Roll20, I wanted to throw my random thinking about options at you. So here it is:

1. Whatever HP you were on, you have in your 'normal' form when you revert (but can't go above your max HP for the form). I.e. if the alternate form (form B say) had 24 HP and you took 5 damage, you'd be on 19 when you changed back (to form A), but if you'd only taken 3 damage, you'd be at full HP in form A. The cons to this method are what do you if you change back to form B? Do you go to full HP, or back to 21 etc? How do you keep track of that, how do you heal it, etc. (this makes it kind of like temp hit points, but could be abused if you change back and forth to get that raise in HP).

2. Whatever damage you have taken, transfers between your forms, so if form B was as above, and you took the 19 damage, you'd revert back to form A with only 1 HP. But you I'd probably go for you never being able to drop to less than 1 HP in this way, and if you changed back to your Alt form (B) you'd get those extra 4 back. Again, issues around record keeping if you chop and change and don't rest in between. However, could counter that fatigued argument as you'd have to rest to get HP back for both forms.

3. As 2, but you can drop to 0. Mirrors the temp HP that barbarians used to get in D&D, but I hate this idea personally.

4. When you change back you get full HP back. Simplest, but then could be abused to heal without healing.

5. Track HP completely independently for each form. Stops abuse, but how does the alt form heal if you're not in it? And you'd have to have the two sheets (which I'd propose anyway).

6. Have some proportion of the damage transfer between forms. I.e. when you go from form B to A you transfer half the damage. Gets round the risk of being taken out (unless your alt form has twice as many HP as you do), but again what if you change back in 2 rounds?

I have a preference, but I'm not saying for now.

**Comment by raihje** [comment]
I'd say track damage for whatever form you're in. When you change forms that's how much HP you have unless it's beyond the max for the form you shifted into, in which case it's at max. If you drop to 0 you're unconscious, regardless of what form you're in. If you try to shift back while being in exceptionally poor shape (that you'd be at 0) the effort of transforming succeeds but you have one round to heal or you're unconscious (similar to deathless berserker)

Inventory melds, meaning it doesn't exist unless you shift back, similar to druids wild shape and such, although this is more case-by-case if it's between two humanoid forms I could see equipment being fine. Ultimately, I think equipment should always be separate from the character though it's simple and gives them something unique to think about for transforming.

**Comment by twystedcures** [comment]
Narratively, tracking HP for both forms separately opens up some interesting possibilities.  From comics, I can remember a Ghost Rider arc where the host body (Johnny Blaze) was dying, and he had to maintain the Ghost Rider form to stay alive.

**Comment by raihje** [comment]
I'd be fine treating it like Druids in 5E (revert back at full health - any extra you would've taken in your other form) but that's wayyy too open to abuse in OL since there's no limit to how often you can transform and what you can transform into.

**Comment by DukeAnax** [comment]
If I remember correctly Druids in 5E shift into full HP but revert back with the original HP they had before shifting minus excess damage.

I'd be fine for Shapeshifting in OL to handle HP the same (that's not yet defined either btw) I'm not sure that would work for alternate Form though.

How about both forms track their HP seperately and player can choose one of these modes?
Linked: The other form gets half the damage, but also gets half the heal.
Unlinked: Both forms take damage and heal seperately.

**Comment by raihje** [comment]
It's the same person, so I don't agree with unlinked fundamentally. They aren't calling a friend to take their place with it's own block, they're assuming a new form.
I think it's simplest to say your HP is what it is, if you shift into a form with less HP it's capped by it's current max HP. If you hit 0 you hit 0.

**Comment by Elvenoob** [comment]
I don't understand people wanting to keep the damage tracked seperately between the two different forms...

I originally suggested, just telling the player to keep track of the damage they've taken, and apply that to the new form, despite the problem that plan has with changing forms near 0 HP, it still seems like the best plan to me...

**Comment by brianfeister** [comment]
No chance of me tracking damage separately between two forms, that's contrary to the core of fun and simplicity with Open Legend. The advantage of shifting to a form with a higher HP total should be represented by the fact that your HP total floats higher so when you revert to a lower HP form, you keep the same HP, effectively giving you a boost if you go from a form with 40 HP down to a form with 30 HP>

**Comment by DMsShadow** [comment]
@brianfeister what if you change back up again?

**Comment by raihje** [comment]
@brianfeister So  essentially, anyone can dump points in their alternate forms physical attributes for a permanent health increase (in addition to supernatural powers) at the cost of 3 feat points?

**Comment by DMsShadow** [comment]
Let's be clear, with the above, to recharge those 10 HP, you'd have to focus action to change back to your base form, then another to get back to your alt form. That's two rounds of doing nothing to get 10 HP. Not to mention that if you dropped below the 30, you GM might make the new lower total carry back to your alternate form.

**Comment by hmack312** [comment]
Since you guys are adjusting the alternate form feat, could you also provide clarification on how the new set of attributes works for the second form?
The last line specifically states that your physical attributes return to their previous values. So if you have a character that has 6 attribute points total and put 3 in might and 3 in influence to get a score of 2 for each. If this character has Alternate Form tier 1 then he should get half of those attribute points back (3) to spend on a new set of attribute points. So if he spends those 3 to get a 2 in fortitude, does he retain the 2 in influence?

**Comment by brianfeister** [comment]
@hmack312 The new Alternate form feat description should answer those questions - http://www.openlegendrpg.com/feats/alternate_form

**Comment by brianfeister** [comment]
2 Focus actions to heal is no problem at all. It would be WAY easier to get a much better result by taking `Creation` and just using the `Heal` boon.

**Comment by brianfeister** [comment]
@DMsShadow Whoops, I missed it, I'm seeing the problem now -- if you start at full HP in a lower `Fortitude` form and shift to a higher Fortitude form, what happens? Presumably you gain HP, but that's contrary to what I said above about keeping your HP total the same regardless of shifting forms.

What do people think about having your HP always stay the same unless you're at full HP? This would mean that we can keep things simple but still have the benefit of the werewolf shifting into a higher `Fortitude` form getting the HP benefits they would normally expect.

For the times they shift AFTER damage, I would think of it as being like "Hey, my vulnerable base form took damage, so it hurts worse"

**Comment by brianfeister** [comment]
So, proposal is: if you're at full HP, your HP total changes when you shift. If you've taken any damage, your HP total doesn't change.

**Comment by Elvenoob** [comment]
I think @hmack312 's confusion was with this line;

> Upon returning to your original form, your physical attributes return to their previous values.

Which doesn't really make sense with this version of the feat either, since ALL your attributes are changing back and forth between the two sheets.

___

On another note, I don't really agree with that, particularly with Presence and Will as HP stats too, if you change one of these (Will makes no sense, true, but Presence can easily be explained.), the explanation doesn't hold up.

I'm more of a fan of, your HP will change up and down by the difference between the maximums, when you change forms, but if this change would put you below 0, you remain below 0, but do not fall unconscious until you take further damage.

**Comment by brianfeister** [comment]
Yeah see, that last part you mention @Elvenoob is more complicated than I'm wanting this to become. I suppose if everyone else wants it, then I can concede to tracking total damage, but I'm pretty sure I'm not going to be able to get on board with anything regarding tracking HP separately. Either we track total damage sustained or we track total HP, but either way, it's uniform across transformations.

**Comment by Elvenoob** [comment]
I wasn't talking about tracking HP separately, it's just, I'm a fan of tracking total damage taken, but that has the one issue which will need answering either way when one does that, shifting into a lower HP form when you've taken enough damage to knock that form out.

I don't approve of leaving the HP the same as soon as you take damage though, example; 

"Oh, no, I took a papercut for 1 damage, and suddenly my Alternate form is down an extra 20 health for no reason~!"

(Sure, I exaggerated it a little, but points need to  be made.)

**Comment by Elvenoob** [comment]
(Ooops, guess I did go a little over the top... thanks...)

Actually, yeah, that'd work a lot better, the 1 HP thing. Not entirely sure why I didn't think to put it like that.

**Comment by brianfeister** [comment]
No problem - not over the top at all!

So, this is your chance to vote folks, I think these are the two options I'm willing to accept:

Option A - You track total damage sustained, your HP fluctuates with shifting, and you always remain at 1 HP minimum when shifting.

Option B - You track your HP total, when you shift to a new form, if you're at max HP then you get max HP for your new form's attributes, but anything less than full HP you just keep the same HP when shifting.

I think Option A looks alot simpler now that I write it 👌  ... and it also prevents the loophole of bypassing damage via shifting. Since your total damage is tracked, you can't shake off that damage by shifting. If form A has 30 HP and form B has 20 HP, and you've taken 25 damage, then you would have 5 HP in form B and 1 HP in form A. That seems pretty logical and straightforward to me.

**Comment by DMsShadow** [comment]
Option A all the way. I think when I discussed this on Roll20 with @Elvenoob it's the one I flagged as my preferred (option 2 on my list), unless I'm remembering wrong. Though it does mean keeping track of damage over HP remaining, it means you keep a buff when you change, but you don't drop when you shift back (but you are very vulnerable).

**Comment by DMsShadow** [comment]
Though I should say I was tempted by @raihje suggestion to make it like deathless berserker. Is there some merit in that parallel?

**Comment by Elvenoob** [comment]
To make the counting of the votes easier, I also support option A.

**Comment by raihje** [comment]
.. I definitely support option B but it looks like that doesn't matter now. Free power bumps, also never go below 1 hp? Pretty solid I guess. How are you going to track fluctuating HP? Percentage? X from max?

I much prefer if you need max HP to get max HP in your new form. Or you could do it as X from max in your new form as you took damage. So if your 8/16 it'd be 24/32.

**Comment by Elvenoob** [comment]
Not sure where you get "Never go below 1 HP", from, we're saying, the mere act of transforming never knocks you out...

And, option A **is** tracking how far from max health the PC is, it's just that, with that method, say you're in a 30 HP max form, a Vampire for example, you take 22 damage, and then you turn into a 10 HP bat.

Tracking how much health the PC has lost would put the bat form at -12 HP. 

But, it makes no sense to get knocked out or die by the mere act of changing forms, so we add the clause; if you transform and doing so would put you below 1 HP, you are at 1 HP instead.

___

The problem with option B, is, as I put it earlier, papercuts. It makes no sense to suddenly be missing a possibly huge chunk of HP out of the high-HP form if you take 1 point of damage whilst in the lower-hp form.

**Comment by brianfeister** [comment]
Yeah @raihje I must not be explaining myself well. You don't track "HP %" with Option A, you track "number of HP in total damage sustained". Hence my example:

>  If form A has 30 HP and form B has 20 HP, and you've taken 25 damage, then you would have 5 HP in form B and 1 HP in form A.

**Comment by Elvenoob** [comment]
(I think that also doesn't quite explain it well enough, @raihje is mis-understanding that )

**Comment by Elvenoob** [comment]
(Ooops? That button is usually where the cancel button is, sorry.)

**Comment by DukeAnax** [comment]
Ok sofar it seems we go with option A. And I agree, because I had a thought: Why not do it that way all the time?

So instead of maxHP and currentHP, you'd have just HP and Damage. And you'd loose conciousness when damage exceeds HP.

That way you wouldn't even have to explain how alternate forms deal with HP, players would do it intuitively.

And I personally think it is a better concept in general anyway. Most people find it easier to add than subtract. It gets rid of all weirdness of what happens around 0,you don't suddenly stop taking damage or have negative HP, healing works naturally.

**Comment by raihje** [comment]
With @Elvenoob's example of "papercut" you'd be 1 from max regardless of form with Option B, how is that unreasonable? Are we just agreeing with different words?

**Comment by brianfeister** [comment]
@raihje not quite. Option B would mean that starting in form X with 19/20 HP and shifting to form Z with 40 max HP, but your 19 total becomes sticky and you shift into the new form with 19.

**Comment by raihje** [comment]
Oh, I simply meant you shift with your max - damage, and can't have more than the max of whatever form you're shifting into (also applies to druids using the shapeshift boon, I'd imagine)

**Comment by Elvenoob** [comment]
That one was option A.

Since it seems fairly well agreed on, I think it might also be time to call some attention back around to the other two things which need a little clarification, Equipment, particularly Armor, and, not exclusively to do with just Alternate Form, but in general, characters with natural weapons, how to represent those, and when it comes to Alternate Form, how shifting into a form which has them works.

**Comment by DukeAnax** [comment]
I think Natural Weapon should be a Feat

**Comment by Elvenoob** [comment]
Considering how cheap weapons are, and the lack of an overly significant effect for most of them, I really disagree with that. Maybe in a system like D&D, but it really feels way too costly to make that a feat in Open Legend...

**Comment by brianfeister** [comment]
Yup, I'm not really open to a Natural Weapon feat, but thanks for being proactive about making suggestions, let's lock conversation here to just the issue at hand, though. 

Sounds unanimous about "Option A" and I'll leave that as the closing thoughts on the matter until we actually implement it. If someone wants to vote "Option B" here, then feel free to add it but so far Option A seems unanimous:

> **Option A** - You track total damage sustained, your HP fluctuates with shifting, and you always remain at 1 HP minimum when shifting.

**Comment by Elvenoob** [comment]
(Umm... The issue at hand _was_ originally including that, and what happens to your equipment when you transform, though, conversation just first focused on the HP issue first... Should I make a seperate thread for Natural Weapons, since they're not directly tied to Alternate Form?)

**Comment by brianfeister** [comment]
Gotcha, sorry -- difficult to keep track of everything. We're definitely fixing the HP issue, but I'm not planning to fix the natural weapons issue. I'm pretty strong on the belief that natural weapons combined with shapeshifting will actually upset balance and make shapeshifting OP.

**Comment by Elvenoob** [comment]
Well, I think the Weapons page iteslf needs a 5e style disclaimer of "These are just stat blocks, if you want to use a Katana, or maybe your character is a beast with deadly claws, you should choose the stat block which best represents that weapon"

Which would kill both the "Exotic" & "Natural" weapons birds with one stone.

But, discussing that is probably best suited to a whole new thread, leaving the last remaining issue; Equipment, and whether it does a 5e and whatever you have on one form melds into the other when you switch, or you leave it all behind when you transform...

Or, even just telling the players; "You can choose whether your equipment melds into your form or remains behind when you transform, when you take this feat, but you cannot change this choice later."

Which means, they will have to deal with the inconveniences of whichever one they decide to go with.

**Comment by istabosz** [comment]
I've just updated the feat to reflect the new HP tracking and also edited in general for clarity. I'm leaving this issue open until it gets reflected in the SRD.

**Comment by brianfeister** [comment]
Closed per #212
