### ISSUE TITLE
Aura Boon

### ISSUE THREAD

**Issue by istabosz** [openlegend/core-rules#117]
Per discussion on Issue #100 I propose the following...

# Aura

**Duration:** Sustain Persists
**Invocation Time:** 1 Major Action
**Power Level:** 4 / 6 / 8
**Attributes:** Any supernatural
**Description**
You surround a willing target in an aura that hurts their foes or helps their allies. A shield of flame that burns attackers, a circle of healing, and an aura of elemental protection are all examples of this boon in action.

**Effect**
An aura extends from a willing target in a distance determined by the power level of this boon:

**Power Level 4:** 5' radius
**Power Level 6:** 10' radius
**Power Level 8:** 15' radius

Choose a single bane or boon which uses the same attribute that you used to invoke *Aura*. The maximum power level for the chosen bane or boon is one-half the power level of your aura.

**If the aura radiates a bane**, then the target of the aura is not affected by it. All other creatures (friend or foe) who willingly enter the area of the aura or end their turn within it suffer a bane attack to inflict the chosen bane. No creature may be subject to a bane attack from the same creature's aura more than once per round.

**If the aura radiates a boon**, then the target of the aura is also affected by it. The target and all allies who end their turn within the area of the aura automatically gain the chosen boon. Upon leaving the area of the aura, the boon is immediately removed. No creature may gain a boon from the same creature's aura more than once per round.

**Special:** This boon may require special attention and adjudication from the GM, as not all banes and boons may abe an appropriate fit for an aura. Telekinesis, for example, is not a boon that can be granted to allies and thus does not work well as an aura.

**Comment by DukeAnax** [comment]
Hole in One. I couldn't see how it would work as a boon, but this feels just right. You are a mechanics wizard Ish.

**Comment by Elvenoob** [comment]
Hmmm... I would really like to see a character Boon Focus this, it's not as powerful as Boon Focusing something more dramatic, in fact, it's exactly half as powerful, but it's a lot more versatile.

One little... well, it's not really a problem, but it probably needs clarification: How does Boon Accessing work with this? (In multiple ways; Boon Access on this boon itself, and trying to use a Boon you've gained through the Boon Access feat in an aura form.)

**Comment by Elvenoob** [comment]
(Oh, something else: If you hand out a Boon like Fly, which is Duration; Sustain Persists, who has to do the Sustaining to keep that Boon active? Does that fall under sustaining the Aura as a whole, or does each affected person need to sustain the effect themselves?)

**Comment by Elvenoob** [comment]
(For clarification: I agree with @DukeAnax , this is really good right now, I just noticed a couple niche situations which might need clarification.)

**Comment by brianfeister** [comment]
@Elvenoob There's not really a reason to Boon Access this if you do the math. You get a bane or boon equal to half the invocation Power Level. That means, the max bane / boon you can ever access here is Power Level 4. So, you can't fly, and you also can't access any bane or boon that you couldn't easily access already by purchasing a 4 in an attribute.

But I **can** see a case for taking **Boon Access** with this boon, and I think it works well. If I want to "aura heal" at Power Level 4 (1d10). 9 feat points is alot to spend, but aura healing d10 is crazy powerful so I think it works out. 

I'm certain that sustain is done by the Aura invoker, since they invoked the boon. I think the rules are already pretty clear on that.

**Comment by brianfeister** [comment]
I've just closed a loophole with `Boon Access` thanks to this feat -- the potential of abusing Boon Access to change your invoking attribute on the fly (swapping between Entropy and Creation with `Boon Access (Aura)`.

I've added this caveat [in this commit](https://github.com/openlegend/core-rules/commit/6918572e2a0d7296ab3b4cb32e453440b0f9ecc1)

> If the boons has multiple attribute prerequisite options, you choose one attribute when you take this feat.

**Comment by Elvenoob** [comment]
Just to make sure this is as-intended, with this boon, and either Boon Access or Boon Focus, as things are right now, if you're running Boon Access (Aura) (Alteration), for example, you could still use either Resistance or Shapeshift as you see fit.

And, for people with a few high supernatural stats Running Boon Focus III, they could switch between whatever aura whenever they feel like it, say they have a pretty good Alteration (Because it's a convenient example of two useful boons for Auras), on their turn, they could run through their normal turn in human form, then, decide to change their Aura from Resistance to Shapeshift, allowing everyone to turn into fishies and not drown, or something like that.

**Comment by brianfeister** [comment]
Very helpful that you've pointed it out, but I'm OK with it because they 

1. Spent 9 feat points
1. Still have to roll and can't auto-invoke
1. Could do all of that with auto-invoke but it would cost... ummm... 18 points? For `Multi-Target Boon Expert` and all of that. Also, when they go that route, for all those points, they still had to lock auto-success to one specific boon

I think I'm OK with all of this

**Comment by DukeAnax** [comment]
Not to mention as a GM I wouldn't allow Shapeshift Aura without a _very_ good reasoning. Seems quite odd to me.

**Comment by Elvenoob** [comment]
@brianfeister About #4, I was talking about the Boon Focus character seperately, and why is Multi-Target Boon Expert necessary when you have Aura and everyone is inside range?

And, You've never mentioned anywhere in any of the rules that Boon Focusing Aura is restricted to using just one Boon as an Aura...

**Comment by DukeAnax** [comment]
I guess what Elvenoob wants to say is anyone with Boon Focus (Aura) has Boon Focus on any and all Power 2 boons and banes

**Comment by brianfeister** [comment]
And I think I'm fine with that, because you're still limited to one at a time and really, the real power scale is a bell curve. I'm pretty sure anything PL 4 or less is low-impact, and if we find high-impact boons in there, we should be bumping their power level higher.

**Comment by brianfeister** [comment]
As an important example, you can't fly / levitate until PL 5.

**Comment by istabosz** [comment]
Seems like everything in this discussion is resolved, so I've just commited Aura.
