### ISSUE TITLE
Necessity of Fortitude?

### ISSUE THREAD

**Issue by Sennar25** [openlegend/core-rules#123]
I was just wondering if Fortitude is actually a necessary attribute. 

I mean pretty much everything fortitude does could be pushed on might or would that make might just way too over powered?

In case of the hitpoints you could just say that instead of the 2 hitpoints per fortitude you get 1 point per Agility(bend with the attack to reduce its damage)/Might(toughen it out).

I don't really see any need for Fortitude but please do enlighten me on it's specific uses and why you don't want to replace it.

**Comment by brianfeister** [comment]
@Sennar25 thanks for the feedback. I do think attributes that contribute to all 3 of HP, attacks, and defenses are overpowered so we won't do that. Agility used to have this problem and became clearly the best stat so we broke it up so that it no longer factors into HP.

Also Github is not the place for general rules discussions. Only for specific actionable proposals of fixes.

If you'd like to have a discussion about this, please take it to the community site: https://openlegend.mightybell.com
