### ISSUE TITLE
Expanding the Weapons section (Without actually making and balancing more weapons.)

### ISSUE THREAD

**Issue by Elvenoob** [openlegend/core-rules#127]
I think a 5e-esque statement about re-flavouring the weapon stat blocks should be included, and I would say, rather than letting it get lost in the text, it should be featured, because the versatility of the flavour text has been a focus of OL so far. 

For the statement itself, I think something like this should work.

"The weapons list below is not meant to be an exhaustive list of the weapons you can use, it's simply there to supply a stat block to some of the more common armaments. If you have a less common weapon, use the most fitting stat block from the section below to represent it. For example, if you have a Katana, a Longsword's stats would describe a Katana's capabilities perfectly."

The only problem about this is Natural Weaponry, specifically, the fact that they can't be disarmed of these.  And, if you do something to disable the weapon, like make their claws blunt, do you just say "But you see something suitable for re-sharpening them up to 15 feet away"?

**Comment by Odog4ever** [comment]
I think natural weapons are easy to disarm. Ever accidentally slam your hand in a door? You are probably going to wait for the pain to reside before you do anything particularly deleterious with your fingers/hand. "Re-arming" is shaking off the pain and regaining the use of fine motor control.

I may have missed it but is "disable" and an actual bane/affect?

**Comment by ThirteenStrings** [comment]
My players have expressed an issue in regards to disarm. Not sure if we should add a proficiency system or cause disarm to invoke automatic penalties to later attacks, but as it stands now, being disarmed might not be a big deal. With certain weapons, you gain very little over unarmed strike from the weapon. A melee fighter using a long sword isn't affected and the assumption is any character is just as good with their fists as any other.

In fact, during a playthrough my main melee character was disarmed... his sword slid across the ground. He pointed out that it didn't make any difference and continued the fight as if nothing happened.  He didn't like the feel of that but at the same time was demonstrating the fault in the rules as written.

**Comment by Odog4ever** [comment]
@ThirteenStrings 

What fault do you see in the rules as written?

The weapons don't have damage values but do give advantages for inflicting certain banes, enabling attacks from different ranges, with different attributes, etc. (Basically the entire reason you pick one weapon over another) etc. So the "advantages" (the non-mechanical kind) come from the tactical options the weapons give you. Your example of long sword vs unarmed is one of the unfortunate ones since it's  one of the few official weapons that doesn't have an associated bane so it's harder to see the advantage of long sword, specifically, over unarmed in combat.

I think the rules remove some of the unfairness from other games when one side has access to objectively better weapons/armor etc. Taking certain feats can make one weapon choice "more" but then it comes down to innate ability or training, fictionally, and using all you tactical options smartly (which is what I prefer personally).

If a PC concentrates on buying feats to strengthen their "unarmed" attacks then "any character is just as good with their fists as any other" doesn't apply anymore, really.

**Comment by brianfeister** [comment]
@Elvenoob - I'm going to close this only because with the "Expanded Weapons & Equipment" stretch goal that we've unlocked I'm not only going to be doing this, but also **much** more and try to expose the weapon system as composable (this means that it's modular in the ways other things are in the game).

**Comment by ThirteenStrings** [comment]
I understand your points, however, mechanically a longsword is not different from unarmed strike.  My players thought it was weird that even though the melee fighter was disarmed it made no difference. I can see this happening in several instances. 

From a story standpoint it seems weird. Someone completely untrained in a weapon has no problem using it, and the corollary to this is that if someone is disarmed it doesn't really matter for many of the weapons because unarmed strike covers so many properties. 

At this point, why would a character who trained in longsword (story wise, not with weapon specialization) bother using or retrieving his weapon?

My players and I all feel that the weapons, unarmed strike, disarm bane, or a proficiency system need to have tweaks to consider this. 

Thanks for the conversation, love the game, just wanted to share my concern. My party can house rule this if nobody else had this concern, but I'm not alone with finding this an issue at my gaming table.

**Comment by Odog4ever** [comment]
@ThirteenStrings 

I have to ask, did you apply advantage/disadvantage when the melee fighter got disarmed? That's within the rules as written to apply those, when appropriate, as the GM.

So if the PC gets disarmed give them disadvantage to attack unarmed.
If an NPC gets disarmed give them disadvantage to attack unarmed OR give the PC advantage to attack, etc...

**Comment by brianfeister** [comment]
> I understand your points, however, mechanically a longsword is not different from unarmed strike. My players thought it was weird that even though the melee fighter was disarmed it made no difference. I can see this happening in several instances.

This is not true, there are mechanical differences, as we discussed. `Two-handed` is a huge difference. And the not-yet-released `Deadly` property of some firearms that also gives Advantage is huge. This harkens back to an important thing about Open Legend. "We don't have +1 modifiers" ... we paint broader strokes, so it's either a +2.5 (Advantage 1) or it's just a +0 and flavor text. Giving every weapon a variable Advantage bonus would be a huge mistake, something that was proven by testing so we don't need to discuss it.

> From a story standpoint it seems weird. Someone completely untrained in a weapon has no problem using it, and the corollary to this is that if someone is disarmed it doesn't really matter for many of the weapons because unarmed strike covers so many properties.

This is incorrect. If you're completely untrained, then you have an attribute score of zero in Might and Agility. In Open Legend, your attribute reflects your training. You can say you don't like that, but it's not negotiable.

> My players and I all feel that the weapons, unarmed strike, disarm bane, or a proficiency system need to have tweaks to consider this.

While there is a 99% chance I will say no to any such proposals, you should just lay them out so I can explain what I've already tried and why it's problematic. On the off 1% chance that it's something I haven't considered and it doesn't break the game, then I'm all ears.

So, more solutions, less debate, please.

**Comment by ThirteenStrings** [comment]
Thank you for the response Brian. I didn't see your response before my last reply. Apologies if I was coming off as belligerent.   I'm excited to hear we reached our stretch goal for weapons. My intention wasn't to debate. I see you pointing out excellent explanations and solutions, and I was looking to generate solutions not debates. I have a group of players who are just excited as I am about this system and we're always trying to get a feel for what works and doesn't.

**Comment by brianfeister** [comment]
@ThirteenStrings - no problem, sorry to come off harsh it's just that I have very limited time and alot of work on my plate. Truly these questions should be asked on [the Community site](https://openlegend.mightybell.com) because many of the people over there understand the reason things work the way they do, and so you have a better chance of discussion and benefit from the collective wisdom -- https://openlegend.mightybell.com

Really glad to hear you guys are enjoying the game, that's my favorite thing to hear!
