### ISSUE TITLE
Do dice from the heal boon explode?

### ISSUE THREAD

**Issue by istabosz** [openlegend/core-rules#13]
I'm assuming yes, but I figure either way we should clarify in the rules text because its an unusual situation.

**Comment by DMsShadow** [comment]
I assume they'd have to as they explode in every other situation.

Get Outlook for iOS




On Fri, Jul 15, 2016 at 2:53 AM +0100, "istabosz" <notifications@github.com> wrote:





I'm assuming yes, but I figure either way we should clarify in the rules text because its an unusual situation.

---
You are receiving this because you are subscribed to this thread.
Reply to this email directly or view it on GitHub:
https://github.com/openlegend/core-rules/issues/13

**Comment by brianfeister** [comment]
I'm good with adding it to the text though we will need to be vigilant, there is at least one other place and maybe more. `Persistent Damage` also rolls non-action roll dice that can explode.
