### ISSUE TITLE
Gm Resources Suggestion

### ISSUE THREAD

**Issue by Bookwyrmling** [openlegend/core-rules#141]
I've been making a lot of characters, and I've been wondering if there could be a way we submit them somewhere for a DM to scoop up for their Campaign or a One-shot. Would this be a viable option to host on the website. I've been just keeping them sitting on a roll20 campaign.

**Comment by brianfeister** [comment]
@Bookwyrmling - for the time being, posting links to them or sharing them as posts on the community site (https://openlegend.mightybell.com) is the only option.

Your proposal is actually part of a very large effort I plan to do eventually, which is to create a database for all Open Legend players to create a login and then generate characters and share them with each other / the community but this is going to involve me writing alot of code and will take alot of time so I'm going to close this just because it's so far in the future that I'm not comfortable keeping this open as a to-do item because it's to far in the future
