### ISSUE TITLE
Consider removing "Deal 5 damage" on a miss

### ISSUE THREAD

**Issue by brianfeister** [openlegend/core-rules#159]
I think this has caused more woes than anything else in the rules text. Everyone asks about it, everyone criticizes it, I just don't know if I feel confident in it anymore. When I'm GMing I do sometimes use it but I find that the better goal is to use misses as a chance to drive the cinematic imagery of a scene forward with a bane effect rather than damage. 

The problem I have is that it is a categorically different GM mindset that seeks to deal straight damage to a character so I feel like there's just a big chasm between Knockdown, Forced Move, and then 5 damage. Granted, you can one-shot kill a character on a cliff with Forced Move. I don't know.

I had this conversation, which I think the commenter is getting lost on semantics but it did make me think hard about it.

**Comment by Elvenoob** [comment]
On the other hand, the option to deal damage through success with a twist is still there through the application of the Persistent Damage bane, so if the players want to do it, they can.

I do really like the idea of the 5 damage option, it could lead to some really cool moments, but it has led to a decent amount of confusion, so it staying or going is fine either way with me, but I would say don't get so disheartened over it, it was still a good idea.

**Comment by DukeAnax** [comment]
For me a lot of the weirdness comes from it being fixed (both damage and banes). The static nature goes against the idea of rolling dice and storywise it is weird that every time you fail you get a very precise predictable result.

Another big factor is that succeding may end up giving only a few damage. No matter the rationale of avoiding a counterattack, You can't shake the feeling that you failed by rolling slightly **_too high._** 
Also with the fact that you can apply banes below 0, getting a 1 feels like a missed chance.

To alleviate theese feeling we are currently trying this system instead:

When you succeed:
You add your attribute dice to the damage, so it rarely feels disappointing.
Banes are still only applied when your attack is 10, no matter the modified damage.

When you fail:
You can choose to do your attribute dice in damage, or apply a bane that is half the power of your attribute dice. If you do the GM can do the same.
Alternatively you can retreat 10' and the GM does nothing.

Yes this means higher attribute dice also mean higher counter when you fail. The idea is that you try too hard to compensate and face the consequences. But this is offset by the abbility to choose not to pull through with the attack and recover instead.

This smoothes over a lot of the bumps I stumbled over without adding complexity and it creates an interesting dynamic that my players seem to enjoy more than the standard system.

**Comment by istabosz** [comment]
@DukeAnax That sounds like a great home brew work around, but I don't think it will fly in the core rules. One thing that I think a lot of people have praised is the single roll combat mechanic.

I'm okay with removing the damage option, but I feel like we'd have to replace it with something else just to broaden the options. 

I'll admit I'm not totally sold on removing the damage, though, because I think it is integral to keeping combat from stagnating by having round after round of misses. I think there have been two primary areas of confusion: (1) 5 damage is a lot and makes hitting by a narrow margin feel like a failure, and (2) the paradigm shift for GM to whom it is a far stretch from the norm.

We could fix these issues pretty easily by (1) reducing the damage dealt down to 3, and (2) just adding a paragraph or two to explain the rationale/execution.

**Comment by ucffool** [comment]
My first take on it was I didn't care for it. I haven't run an OL game yet, so I don't have anything to backup the first reaction. Rolls should matter, and people DO MISS in combat, so being able to *deal damage anyway* seems far to *participation trophy* -esque.

**Comment by brianfeister** [comment]
It's not participation tropy-esque, it's a focus on moving things forward. If you miss in combat, in most scenarios, something changes to hinder you. Maybe your gun jams, or your sword cleaves into a tree and you have to get it loose again. Maybe you overextend and hit your enemy while they also hit you.

Anyway, I agree @istabosz, I've been thinking for a long time now that it should be 3 damage on a miss. As far as (2) goes, I agree, I think we should explain the rationale.

**Comment by DukeAnax** [comment]
@istabosz that's presicely why we like this solution: it's still a single roll, sorry if that wasn't clear. I mean't we use the attribute dice portion already rolled, not reroll them. We just make use of the dynamic OL creates by using different dice in the same roll.

I'm actually starting to use some of that rationale in interpreting all rolls. The d20 determines various random factors of the situation and the attribute dice determine how you handle those factors.

As for your idea: lowering the damage to 3 is certainly an easy way to help with the confusion between success and failure. Also I think it's not so much the paradigm shift that is the problem, but the fact that failure is still so effective.

**Comment by brianfeister** [comment]
@dukeanax I have to say, that is insanely broken. Under your proposal, I could roll 17 on my attribute dice, one on my D20 and still do 17 damage. Since monsters and NPCs don't have effects that trigger on a miss this would be incredibly unbalanced.

**Comment by istabosz** [comment]
> Anyway, I agree @istabosz, I've been thinking for a long time now that it should be 3 damage on a miss. As far as (2) goes, I agree, I think we should explain the rationale.

@brianfeister Is that the green light to make the edits?

**Comment by brianfeister** [comment]
Yup, let's do it @istabosz

**Comment by brianfeister** [comment]
Actually, funny story, I accidentally used the new rule in combat in a game I was running less than an hour ago (3 damage) and it felt completely natural as if it was the way it should have been all along. Didn't even realize that I made the switch until I read this now. I remember always feeling some hesitation / anxiety about using the "5 dmg option" before.

**Comment by Th3Way** [comment]
The reduction to 3 damage I think is a good solution. Also it solves the bane focus on a miss problem. A complete removal though I think compromises the failing forward.

**Comment by istabosz** [comment]
I think 5 damage made a lot more sense back before we changed the HP formula. 5 damage was a lot less back then.

**Comment by DukeAnax** [comment]
Lol Yeah @brianfeister that was in no way meant as a proposal. That's why I just said, "we are testing this". Food for thought, maybe give inspiration for an alternative direction. Our characters are quite low so a 17 in attribute is a pretty rare explosion.

I had to increase HP to compensate for the extra damage, but it is not actually unbalanced, because the NPC get to do the same. The way we are doing this, if the player decides to go through with that 17 damage, the NPC can do 17 damage as well. Or a Power 8 Bane, lol. Probably need to adjust that rule, haven't had a roll like that yet.

I totally agree that some of this is way over the top for Open Legends Core, but hell is it fun to play.

**Comment by istabosz** [comment]
@brianfeister I've made the change and added a paragraph to explain the rationale. Leaving open for SRD.

**Comment by brianfeister** [comment]
props @jcte02
