### ISSUE TITLE
Resistance Boon could be streamlined

### ISSUE THREAD

**Issue by istabosz** [openlegend/core-rules#16]
https://github.com/openlegend/core-rules/blob/master/boons/boons.yml#L367

I think that this boon could use some cleaning up. Since the current power levels are not cumulative, there are situations in which PL 3 would be more beneficial than PL 5.

What if we make it like this:

PL 3 = +5 defense
PL 5 = +10 defense
PL 7 = immune to damage

Also, one of the listed damage types is Enchantment, but I don't think that makes sense. Not sure about Psychic either.

Good and evil are both listed as damage types as well, but I think we need to clarify what that means. I'm assuming it would be damage from an extraplanar creature hailing from an aligned plane but NOT just protection from attacks from a good or evil humanoid. Is that what you were going for?

**Comment by istabosz** [comment]
I got ya on Enchantment now. That being said, should we make the text for PL 7 say "immune to attacks" instead of "damage" or something like that. Because otherwise, PL 7 isn't doing anything for Enchantment attacks.

**Comment by brianfeister** [comment]
need to add `Illusion` to that list as well.

**Comment by brianfeister** [comment]
Sorry if I wasn't clear here. Yes, "immune to attacks" sounds good.

**Comment by brianfeister** [comment]
@istabosz  I've been giving this some thought since my playtest yesterday where this boon finally got use. Raising a defense score by 10 is INSANE. Granted you can disrupt the person maintaining the boon, but it's not actually that easy to achieve disruption right now, since even stunning still allows you to maintain focus on a boon if you choose. Only using the `Incapacitated` bane against the invoker of the boon guarantees the cancelation of this boon.

Also, immunity to damage is INSANE, and while 7th level is pretty high, I would think that should be placed quite firmly at the very top of the curve.

I'm thinking  maybe we should do something more like:

PL 3 = +3 defense
PL 5 = +6 defense
PL 7 = +9 defense
PL 9 = Immune to damage

**Comment by istabosz** [comment]
That sounds good to me. I'll make the changes
