### ISSUE TITLE
Entropy overloaded with banes / boons for both "theme" and "source"

### ISSUE THREAD

**Issue by brianfeister** [openlegend/core-rules#162]
From Mightybell:

> My specific complaint about Entropy, however, was more about the way that Ish brought his idea of attributes across. No matter how I consider it, Entropy is not the effect as the system would suggest. It seems - to me - to simply be necromancy/dark magic by another name, making it more a causation.
> 
> Creation fits specifically because it is one of the effects. Alteration to alter, creation to create, energy to blast, influence to mentally affect, movement to move, prescience to see/analyze, and protection to protect. Then there is Entropy, which picks and chooses from effects to form a cause. Further, Entropy feels like it directly borrows from Necromancy/Dark Magic altogether, and feels to me like a school of magic that allows one to bypass taking effect attributes. Blasting someone with negative energy, after all, is Entropy in spite of blasting with any other energy being the Energy attribute.

**Comment by DukeAnax** [comment]
This would be easier to go voer if we were able to search for banes and boons by their attribute.

**Comment by DukeAnax** [comment]
Ok I went through the list: There are exactly three Boons that support Entropy: Aura, Barrier and Animate/Summon Creature. There are a lot of banes, but all of them deal with various forms of sickness and decay.

There are exactly two references to Necromancy, one is the Death boon, the other is Animate.

If anything it's rather that necromany traditionally borrows from entropic effects, rather than the other way round.

I have no idea where the notion that negative energy is not Energy came from.

Conclusion: I don't see the case. 

One may argue about summoning, but I use protection to "create" divine summons and energy to "create" elementals. So I see no issue with entropy "creating" undead and demons.

**Comment by Elvenoob** [comment]
Well, Demons is more the realm of Movement, but I agree, I don't see the problem with Entropy creating undead, I like how Entropy and Creation kind of mirror the positive/negative energies of other systems, but both of them have a more unique aspect to them as well, which is the bit they're named after.

**Comment by infernodemon2005** [comment]
perhaps destruction? possibly would be a better name to catch the undead and necromantic energies.
most necromancy spells either destroy the flesh, soul, or bind what has already been destroyed.
so, perhaps renaming entropy to destruction could help solve some of these issues.

**Comment by Rgconner** [comment]
Destruction and entropy are synonyms to me, so I am not sure what it would change.

Also, Creation, while it has 4 banes, has 10 boons. They are sort of mirror concepts.

**Comment by brianfeister** [comment]
Yeah I think I'm done entertaining the notion of changing this. Thanks everyone!
