### ISSUE TITLE
Mention Large / Small Size via two feats and in Shapeshift boon?

### ISSUE THREAD

**Issue by brianfeister** [openlegend/core-rules#163]
So my thinking is that we can hit "size categories" without too much trouble by just having one for larger and one for smaller:

**Larger Sized** - You are larger than average humanoid size. Chose a cubic size of 5', 10', 15', or larger at the GM's discretion. If you chose 5' cube or a 10' cube and have a 10' reach. If you chose to occupy a 15' or larger cube and have a 15' reach.

**Smaller Sized** - You are larger than average humanoid size.  You get a +2 bonus to your Evasion defense.

Also the thought is to add this to the Shapeshift boon for access with shapeshifter forms. Then `Alternate Form` users can access it via these feats.

**Comment by Elvenoob** [comment]
So, you get the increase of the extended reach, but the issue of being easier to attack. 

I do wonder how Larger Size interacts with weapons with the Reach weapons, though, because in the current RAW, I don't think there's going to be a difference, because I think the wording sets the reach to 10, rather than extending it by five, which will usually be 10. 

I just had a thought thinking about mounting your friends and such, though, not only would larger characters be able to let smaller characters ride them (Half the number of squares your character occupies seems reasonable), but the issue of heavy and bulky items come up, a bulky backpack might be an issue for a medium humanoid, but a huge dragon would have a lot less trouble with such an item.

**Comment by DukeAnax** [comment]
@brianfeister  I like the general approach, though I got some questions:

Are there enough drawbacks to being larger that choosing size freely is permissible or should every 5' size increase be another feat tier?

Also should Smaller Size have tiers, fairys are smaller than a gnome is smaller than a human. Also should each tier give +2 Evasion?

What other implications could there be for being larger or smaller?
Larger creatures would have more movement. +5' for every 5' of size?
There is probably some Advantage/Disadvantage situations in fight between different sizes.

I know OpenLegends as a rule doesn't subtract from characters but I feel like there should be a Might restrictions on smaller creatures. Full Plate Fairy Paladin is a bit ridiculous.

**Comment by Elvenoob** [comment]
Then again, it's fairy sized full plate, so it's not nearly as heavy as human full plate.

**Comment by DukeAnax** [comment]
True and all other might checks can be handled with disadvantage if really need be.

**Comment by DMsShadow** [comment]
I just wanted to ask what makes the 5' cube different to a normal humanoid size? If you use 5' spaces or squares then most characters occupy this anyway don't they? I didn't see any disadvantage to being larger, but if it is a feat, then I'd say you don't need to as you're already paying for it.

@elvenoob who would try and ride on a larger shapeshifted individual, I can't imagine that coming up ;)

**Comment by DukeAnax** [comment]
I paused at that for a moment too, my conclusioan is that a 5' large creature is taller, like 8' or more, so they get the extra reach without actually occupying much more space.

**Comment by istabosz** [comment]
Any thought on not making these feats and instead just have them as options during character creation? Rather than make the benefits too mechanical, I think that the GM could just assign advantage/disadvantage in appropriate situations. For example, small characters could get advantage to things like hiding and squeezing but disadvantage to grappling. Large characters might get advantage when intimidating, but disadvantage on hiding. Leave it open to GM interpretation and context.

I'd say that the reach of large creatures is counterbalanced by the ability to be more easily based and the potential for being squeezed in tight places at times, provided that the reach doesn't allow for opportunity attacks.

I also really don't like the Evasion bonus. I think opening up another avenue for increasing defenses just invites min/maxing.

**Comment by DukeAnax** [comment]
True, when thinking long enough about you find that both size increase and decrease have each nummerous benefits and drawbacks. The net amount is close to zero so using a feat point is quite a waste.

Also the evasion bonus isn't actually necessary, if a larger creature attacks a smaller, they'd just have disadvantage, which has essentially the same effect.

**Comment by brianfeister** [comment]
@istabosz so are you proposing we make it a perk I instead? The only issue I have with this is selecting new perks for shapeshifting and alternate form. I suppose it's ok to go that direction. But we are pushing the complexity somewhere else rather than truly simplifying it. I like it being a feat because it forces alternate form characters to pay for it. Also, if it's a feat we should give a benefit. I'm not worried about min maxing because armor mastery already supports min maxing. We probably just reduce the Evasion bonus to 1.

**Comment by brianfeister** [comment]
To clarify what I said above -- I worry that making size a perk (or a separate step in the character creation process) obscures the fact that it's "changeable" when you shapeshift or use alternate form and I think we've already got enough character "properties" to track (perks, flaws, feats, attributes)... I'd really rather not add another property.

**Comment by DukeAnax** [comment]
I think the extact opposide is true, individual perks and feats are quite obscure simply because they disappear between all the others.

Open Legends somewhat suffers from the notion that being humanoid or even being human is the default. So that it often seems it only supports humanoids, even for NPCs.

Making size a feat will have a lot of people miss that it is even an option. But making it an integral part of character creation ensures that everyone takes it into consideration.

While limiting properties is good, Size is only a singular property and I think it's quite an important one to make Open Legends more Open.

**Comment by brianfeister** [comment]
I understand where you're coming from, however, adding size categories is still a new property and a new section that ends up occupying lots of space. Depending on how we implement it, there's the possibility of impacting the following:

* Character Creation
* Perks 
* Rework the Chapter 7 NPC building tables
* Rework shapeshifting
* Rework Alternate Form

**Comment by Elvenoob** [comment]
You're going to have to play with some rules anyway, because, currently there are no feats with any kind of anti-requisite type thing, but you'd probably need to add that somehow.

Also, you can find ways to justify Smaller as a feat, sure, being able to ride normal creatures and on top of that, getting Evasion bumps, it's all good in there.

On the other hand, the larger size, you get the reach, ok, but you increase the number of people who can attack you at once in melee by quite a large amount, so I think there needs to be some benefit beyond that and the possibility of 1 or 2 allies riding you for that to work as a feat...

I do agree with everyone else, though, it might be much more painful to do it on this end, but having Size categories, even as sort of vague guidelines, as part of the core rules would work a lot better in the long run and make things simpler for a GM, and players looking to make a character.

(Although, the smaller size as it currently is would also need some changes to be fair as something which isn't a feat, or else we risk the wrath of the untouchable army of halfling paladins.)

**Comment by istabosz** [comment]
@brianfeister I don't like the idea of making it a feat because that implies that small or large characters are more powerful than medium ones. I think we can simply add size as one of the things to choose under "race" in step 5 of character creation. This is already a step that characters using alternate form would go through.

**Comment by Hades99** [comment]
I mean, I have always thought that statting out a monster like a player with perks and flaws is the way to go anyways. Additionally I don't think that you should have to modify shapeshift or alternate form at all either. If you are a giant that turns into a werewolf the werewolf should be giant as well. What I do think should be changed is that you share perks and flaws in your alternate forms(the feat at least). Shapeshift on the other hand is already worded to support this. Based on it's wording you base the sizes of your forms on your original size so at power level two as a large creature you could become medium size. Just as an example.

**Comment by brianfeister** [comment]
@istabosz - ok, took me awhile to warm up to this idea, but I suppose it won't be common for us to need to add new properties to characters. Go ahead and write something up as part of character creation, though I'm still not sure how we will handle treating small characters differently without them getting an edge. And keep an eye out for impact on shapeshift and alternate form feats

**Comment by istabosz** [comment]
K. I just added a commit with rules for size added to character creation.

**Comment by jcte02** [comment]
@brianfeister This was merged in #192. Can close issue now.
