### ISSUE TITLE
Character Creation

### ISSUE THREAD

**Issue by BuildAndDie** [openlegend/core-rules#173]
There was a lot of discussion on discord.

It might help for character creation to have steps 5 & 6 to be before steps 1-4.
This might require some subsequent re-wording.

The reasoning is it would help people coming into the system understand there is more emphasis on WHO your character is, rather than the attributes that make your character.

That is, create a concept first, and then work the attributes, feats, perks, and flaws to fit what you have in mind.

**Comment by Hassurunous** [comment]
Just wanted to put in a quick +1 for this suggestion. I was also in the Discord discussion and wrote an article about this not too long ago on Medium and my Blog. 

The players that I worked with in this way really ended up with characters that felt more real and thought out than the players went the other way. They also had less changes to make after the first couple sessions (I allow players to tweak their characters if there is something they learn doesn't fit their character or isn't working how they thought it would). 

I think quick stats builds are great for quick characters, but in discussing with ChrisJ on the Discord, I can see how certain things about the rules can be a bit confusing for players not used to a more narrative-driven game like OL.

**Comment by brianfeister** [comment]
Since I haven't seen the Discord thread and not everyone reading this will, I think we need more information.

The following comment doesn't make sense to me

> The reasoning is it would help people coming into the system understand there is more emphasis on WHO your character is, rather than the attributes that make your character.

Attributes are absolutely essential to **WHO** your character is, moreso than your physical description, perks, and flaws in my opinion. 

The opening of Chapter 1 goes like this:

> Chapter 1: Character Creation
> Before you can start telling your story, you’ll need a character to play. This chapter will offer you step-by-step instructions to create your own hero. In Open Legend, you typically begin as a level one character. As you complete quests and gain more experience adventuring, you’ll level up and gain more power. These rules explain how to create a character starting at level one. Later, you’ll learn what to do when you level up.
> Before reading on, take a minute and think of your favorite movies, books, or video games.
> Who were the characters you identified with?
> Who inspired you?
> Now that you’ve got some of your favorites in mind, let’s create your character.

**Comment by BuildAndDie** [comment]
So I think the key there are the last 4 sentences. It tells you to think about your character, who inspires you. Steps 5-6 go into further detail about doing just that.

Then, yes, the attributes are critical to your character, but those critical things would be easier to define and determine if you had a more clear idea in your head of your actual character. Steps 5 & 6 help you with that.

Mind you, I'm trying to help explain and summarize with a slightly fried brain right now, long day yesterday that wore me out physically and mentally. Hopefully someone from that will maybe help clarify.

**Comment by infernodemon2005** [comment]
while attributes are the core of a character, a person who has been enchanted or mutated to controll fire would use energy, however, it would not make sense for the narrative that they could also suddenly release a blast of ice or pulse of lightning even though it would be mechanically possible based on their energy stat.
A thief would use their agility to sneak while an illusionist would influence others to make them just not notice them. these would give the same mechanical benefits though they are described differently in the context of the narrative.
by refocusing on the concept of the character, then bringing the mechanics together, it makes for more fleshed out and interesting characters than just starting with the attributes.

**Comment by Chris-J-68** [comment]
Approaching this from another angle. 

I mentioned on Discord that I was looking for a Sneak/Move Silently type of ability/skill so I was going to change the Skill Specialisation feat (page 28 pdf) to Skill Focus. The change was that you did not take advantage for an attribute anymore, you now chose a narrower ability and that got the advantage. In this example the narrower ability was Sneak. 

I was told there was no need to do this because defining Sneak and its link to Agility stemmed from my character concept/profession/definition/etc. This way, I could define my character as a master thief who could 'Sneak' (using the Agility advantage from the feat on page 28) with the best of them, but I would not necessarily be adept at surfing or balancing or pole vaulting or anything else tied with Agility - because it did not fit with my idea of a master thief. 

I said I did not get this idea/information from the rules as written, and that it needed to be called out. Thus the idea to swap step 4 and 5 with step 1. 

(I still like my idea of Skill Focus though)

**Comment by infernodemon2005** [comment]
I will freely apologize if my thoughts on concept limitations is not within the core of the system and work to understand things from other perspectives. it just makes things easier when designing characters for my players who are less familliar with tabletop systems to focus on a concept and limit the applications of the mechanics based on their concept in order to both drive the narrative as well as ease them into these concepts by not overwhelming them with a large number of banes and boons.

**Comment by brianfeister** [comment]
@Chris-J-68 - whether or not your Skill Focus feat is broken would depend upon it's feat point cost. I suspect that it most likely **IS** broken / OP because you probably dropped the cost down to 1 feat point, instead of 2, which would make it OP.

Perks & flaws are like the cherry on top of the ice cream sundae, they are an afterthought. I suppose that people coming from traditional RPGs would be confused by the fact that your race is part of perks & flaws chosen at the end. I understand why people would see it that way, but I think this is a situation where it's best to challenge the status quo. If I built a character with the "Short-tempered" flaw as the first mechanical choice, I would be building in the wrong order. Granted, race might play a significant part, but I think there is no perfect answer for the order of mechanics since they're all interwoven.

But that's just my reaction regarding perks & flaws. I think the decisions for attributes and feats should be made first to inform the perks & flaws selection.

But I understand the importance of emphasizing the narrative-driven aspect and get people more open-minded and prepared to let go of expectations in Step 1, before they start defining the mechanical aspects.

So, I can see moving Step 5 to become Step 1, and then leave the rest as it is now.

@istabosz

**Comment by infernodemon2005** [comment]
that is a fair compromise. perks and flaws are more minorly important to the concept but can still effect the role playing a large amount.

**Comment by Chris-J-68** [comment]
Not sure what OP means (over powered?). I'll be keeping the cost at '2 points'.

**Comment by brianfeister** [comment]
Yup, "OP = over powered".  That's fine. If you're keeping it at 2 points, then you're not actually changing it, you're just twisting the flavor text a bit, which is what Open Legend is all about.

**Comment by infernodemon2005** [comment]
which is what we were trying to get at in the server lol here's to solving linguistic misunderstandings

**Comment by istabosz** [comment]
Makes sense to me. I kinda think it works well either way, though, so I'm pretty neutral on this one.
