### ISSUE TITLE
Add some explanation (can be small) about what a grid is and why things are measured in 5' increments?

### ISSUE THREAD

**Issue by brianfeister** [openlegend/core-rules#174]
Based on feedback from this post:

https://openlegend.mightybell.com/posts/969887

Personally I'm torn about whether or not to do this as I don't know if I agree it's confusing. I mean, you can do just fine with theater of the mind, but perhaps a sentence or two is in order.

**Comment by Rgconner** [comment]
To me, it is a GM call as to how he is doing it, theater or grid.

If he is using a grid, he needs to explain it. 

Maybe explain both, briefly. Most game systems do some sort of explanation.

**Comment by Brycelor** [comment]
I would suggest adding it in Chapter 7.
My concern is a group of people jumping in without someone to be the GM who has experience playing tabletop RPGs. We can tell the GM he'd have to imagine the feet distances or he could use a grid, and explain what that is. Otherwise, there might be some confusion. This sort of stuff pretty much goes without saying for tabletop RPG veterans, but I'd like to bring in new players and help them understand everything they need.

**Comment by istabosz** [comment]
I think a brief paragraph in the combat section would work best. That's what 5e does and it seems to work fine.

**Comment by DMsShadow** [comment]
Yeah, I'd agree. Default to measurements in feet, but just add in a bit that says:

"Some players prefer to play using figures or counters on a grid map. In such instances, each grid square measures 5' (i.e. 30' becomes 6 squares). If you are using larger scales, then simply increase the size of the squares appropriately."

But worded better than that.

**Comment by BuildAndDie** [comment]
In the 5e player handbook the concept of grid play is listed as a "Variant: Playing on a Grid" it is on page 192.
![variant grid](https://cloud.githubusercontent.com/assets/23116144/21296202/fbac7cde-c52b-11e6-9bc9-e7df64d3ccd3.JPG)

**Comment by twystedcures** [comment]
Have we consisted hex grids, and not just square grids?

**Comment by twystedcures** [comment]
Have we consisted hex grids, and not just square grids?

**Comment by istabosz** [comment]
Just added text in Ch. 6 for this. Added to SRD as well.
