### ISSUE TITLE
Quantifying Shapeshift

### ISSUE THREAD

**Issue by EliManthey** [openlegend/core-rules#177]
Eli here from Mightybell.

Making creatures for shapeshift, summon, companion, and to an extent alternate form right now is a bit of a nightmare. I would like to see the rules for them fleshed out a bit more just because of how much variation there is in the simple NPC creation rules. 

I wanna get the ball rolling with this to make a more official system so I thought about something a bit drastic.

There are several common things happening at the same time on the github here. We are talking about summoning, alternate form, shapeshift, etc...what all of these have in common is that they are living things controlled by players. What if we create a system for making these similar to the npc creation system so instead of saying here make it up yourself willy nilly we can point them to a table or guide and say make a level 3 creature or in the case of a summon maybe a couple level 1 that they could then flavor themselves.

I don't have anything fleshed out right now but I had the idea and thought I would put it up. This could also be used for the companion feat as well.

**Comment by Hassurunous** [comment]
The Challenge Rating system from D&D does a pretty good job of this, and I think something similar could be implemented to limit the power of the shapeshift/summon/companion/alternate form. We already sort of have something like that in each one, but a unified system would indeed make it much easier to explain and use each ability.

**Comment by infernodemon2005** [comment]
the alternate form is like a completely different character though, it might not be so easy to build one into a chart of quick builds.

**Comment by brianfeister** [comment]
The problem I see with this is that it makes Open Legend alot less open and freeform. There are alot of people who want really specific stats and tables, numbers, and are hyper-focused on game balance, but Open Legend is not really trying to scratch that itch.

For me, if I had a table with all kinds of + / - modifiers for creating an NPC or monster then it would really take away alot of the appeal of Open Legend for me. 

Having GM'd Open Legend for over 2 years now in an ongoing campaign, I can say that while I love everything about Open Legend, if you ask me why it's great from a GM's perspective, my answer is very much the opposite of this request. In other words, I would say "As a GM, the best thing about Open Legend is that I don't have to deal with tables and charts when I build things. I typically don't even plan my encounters out in advance, I just decide on a particular bane that characterizes an enemy, decide if that bane is going to trigger on 5 damage or 1 damage and then choose "easy" / "moderate" / "difficult" for how tough the enemy is, correlating to "primary attribute 3" / "primary attribute 4" / "primary attribute 5".

It's very clear to me why you're focused on this as the "monster manual guy" @EliManthey, so I see where you're coming from. But the reality is that, when I publish an official monster manual, it will involve creatures that have "levels" as described in `Chapter 7: Running the Game`, but the creatures of the same level will not have identical power level / balance.

The reason for this is that Open Legend has a unique approach of giving you an incredibly large "toolbox" to work with in the form of banes, boon, and attributes, but you still end up choosing typically just one action per round. In the end of the day, you don't need to obsess over whether an NPC or monster has access to too much power because everything in Open Legend can be countered by something else, and most combats last about 3 rounds so you don't really need to be worried about how balance will swing in a slogfest of linear damage-dealing that lasts for 8 rounds like you might find in D&D or other systems. 

The "volatile d20 time bomb" effect is like death in real-life, it is the great humbler of all players, monsters, and NPCs alike.

**Comment by brianfeister** [comment]
And regarding some of those comments, moderators might be wondering how this impacts the weapon building chart. To be honest, it's a hard decision for me. Exposing something like that may be putting a foot onto a slippery slope in a way that I shouldn't be doing. We should definitely talk about this at the Thursday moderators meting.

**Comment by EliManthey** [comment]
You have hit on a lot of things I'd thought about as well. I can accept that this isn't the direction you want to go. I wish I could be there on Thursday to discuss this myself. That level of ambiguity just makes it harder as a gm to plan for a player with shapeshift....

**Comment by brianfeister** [comment]
Actually, @EliManthey, the more I think about this, the more I feel that it's actually something that is tackled appropriately for the intended audience of the core rules, but what we might do is dedicate a significant portion of the Monster Manual to this when we Kickstart that in 2017.  This kind of content seems like a natural fit for that book, since we will be covering a wide array of genres and there will be tons of gaping holes that I can't cover due to cost restrictions. So providing the formula for monster creation there seems like an ideal way of apologizing and saying "Hey, sorry we couldn't do ALL THE CREATURES from fantasy, historical fiction, far-future sci-fi, and modern horror... so we're giving you the formula to make your own in a very crunchy way if that's what you like. But keep in mind the advice in the Core Rules still stands and you don't need to adhere strictly to this formula if you don't want to.

I'm happy to co-author that book with you, I appreciate your hard work on the subject and I think that there will still be a huge audience for that, especially as Open Legend grows and more and more people ask for it... this is probably the big thing people are looking for next from Open Legend, as far as I can tell. But I don't think we should build it into the Core Rules. We need a system that allows for the Core Rules to still be a valid way of handling these issues, but complements them without competing.

I think the only thing I'm unsure about is how this should affect Shapeshift. For me, Shapeshift might mean something a bit different than it does for you. I'm not limiting it to what a Druid does with an array of familiar animals. I imagine Shapeshift to also be a means of weird, unusual effects, for example, I alter my body at a molecular level so that my eyes change and I have the vision of a hawk, or my nose changes and I have the scent of a wolf. It's fine if you want to treat it as a traditional Druid approach, but that shouldn't be imposed on others using the `Shapeshift` boon as a requirement. That's just the flavor text you put onto the Shapeshift boon for your character. 

So, that being said, I think the guidelines around what types of transformations are possible with Shapeshift right now are correct. When you say the ambiguity makes it hard for a Shapeshifting character, what do you mean by that? Are you trying to say that you need to add feats to your Shapeshift forms so that you can gain stylistic benefits of that creature? Because bane and boon access with freeform attributes seems like it should cover that in most cases. I'd be willing to consider a "Master Shifter" (LOL, we removed the feat with this name but a different mechanic) feat that allows you to gain some aspect of the new form beyond just attribute scores (maybe you choose 1 thing, like defense scores, or multi-attack specialist for a creature with many natural weapons). In the Core Rules this would be up to GM discretion but then we could add those feats to the monsters in the Monster Manual so that the "Master Shifter" feat would have a direct relationship to the feats that are part of the official monster stat blocks in the Monster Manual.

**Comment by EliManthey** [comment]
I would be honored to help write that book!! As for shapeshift I have always liked the kind of shifting you have described but I do not think it is clear enough how those elements work. Maybe an example under shapeshift would be helpful for gm's...especially from older systems to understand what you are trying to do.

**Comment by brianfeister** [comment]
An example under shapeshift sounds good... can you give me some more detail on what you're thinking and what gaps you're looking to fill in?

**Comment by EliManthey** [comment]
basically what you said about more subtle changes and maybe 1 example of the mechanical differences

**Comment by brianfeister** [comment]
Sorry, just copy paste what I said, I'm not sure which part you're referring to, I wrote too much :P

**Comment by EliManthey** [comment]
something like this: "alter my body at a molecular level so that my eyes change and I have the vision of a hawk, or my nose changes and I have the scent of a wolf"

**Comment by DukeAnax** [comment]
Well if that is the case there needs to be a revision of the shapeshift boon, because right now it reads as complete transformation into specific shapes.

But if partial transformations were handled through the boon, what about Alterations Rolls?

**Comment by EliManthey** [comment]
@brianfeister this is what I was talking about with the wording being unclear.

**Comment by brianfeister** [comment]
I guess I broke my own rules when I said that. Dun dun DUUUUUNNNN. @istabosz !!!!!!!

Looks like partial transformation that I mentioned really doesn't fit at all with what this feat is aiming to do, but perhaps it can be added. 

I see now why we're discussing this. Talk about a waste of time typing out what I did earlier.... determining the attributes of the new form does very much indeed need a formula just like Alternate Form needed a formula added to it, because right now it does indeed depend upon arbitrary ability scores that will invite too much contention if there is a stubborn player or an overly strict GM in the equation.

Here's my first idea for  a fix:

---

(Add this somewhere in the intro paragraph)

Each power level below provides a guideline for an upper limit for attributes of the new form. The GM has the final say in the attribute scores of the new form, and may choose to assign better or worse attributes to a given shapeshift form. Below is a guideline for what the best possible attributes are for a form of a given Power Level, however, this is intended as a guideline not to be exceeded. Shapeshifting into a Giant via Power Level 9 does not mean that the story implications should be ignored to create a typically clumsy giant with an Agility attribute of 8.

* **Power Level 3** - Shapeshift into a creature between half and double the target's original size. Gain any non-flight movement modes of the new form. Suggested Agility, Might, Fortitude, and Perception array: 3, 2, 1
* **Power Level 4** - Shapeshift into a creature between one quarter and quadruple the target's original size. Suggested Agility, Might, Fortitude, and Perception array: 4, 3, 3, 2
* **Power Level 5** - Gain the flying movement mode of the new form, if applicable. Suggested Agility, Might, Fortitude, and Perception array: 5, 4, 3, 3
* **Power Level 6** - Shapeshift into a living creature that lacks a typical physiology, such as an elemental, ooze, or a plant. Suggested Agility, Might, Fortitude, and Perception array: 6, 5, 5, 4 
* **Power Level 8** - Shapeshift into a creature of any size. Suggested Agility, Might, Fortitude, and Perception array: 8, 7, 6, 5
* **Power Level 9** - Gain all supernatural attributes possessed by the target. Suggested Agility, Might, Fortitude, and Perception array: 9, 8, 7, 6

**Comment by brianfeister** [comment]
@EliManthey @DukeAnax, I've addressed the partial Shapeshift with a new [Enhance Boon Proposal](#180) in #180, mainly because this boon is already so packed full of content that it would get lost if we attempt to put more functionality into it.

**Comment by EliManthey** [comment]
I think this works well as a fix for now but what about players that want things like pack tactics or intimidating presence. I suggest handling it on a case by case basis but maybe a clarification in the core rules and/or monster manual will be helpful.

**Comment by istabosz** [comment]
@EliManthey What are you referring to mechanically when you say "pack tactics" or "intimidating presence"? The shapeshifter would gain access to all of the banes and boons that their new stats make available, so they could mimic the powers of their new form.

**Comment by EliManthey** [comment]
They were just examples of things that have been asked about, intimidating presence would allow them to use their might for intimidation just like the feat for example. Things that are inherent for beasts like enhanced senses.

**Comment by EliManthey** [comment]
To clarify, I think it can all be handled with banes and boons for now but there are strict gm's out there that want things quantified.

**Comment by brianfeister** [comment]
To be fair, it is already quantified as ish pointed out. You want creatures and their feats defined. Unfortunately we probably need shapeshifters to gain that via a feat and that feat to be in the Monster Manual since it doesn't make sense without that

**Comment by EliManthey** [comment]
Agreed.

**Comment by EliManthey** [comment]
By the way community consensus is that you gain the inherent features of creatures you transform into.

**Comment by brianfeister** [comment]
What does "inherent features" mean?

**Comment by EliManthey** [comment]
let's say the gm statted a bear and gave it intimidating presence per say...the consensus was that if you turned into that bear you would gain intimidating presence.

**Comment by brianfeister** [comment]
Good to know. I don't think I'll mention that in the rules though. Because GMs that don't create such inherent features will be confused. Also, personally, there's a good chance that I might prevent my players from gaining access to that stuff because they already have a pretty big toolbox being able to shapeshift at will. So, my preference is that the rules don't explicitly validate one side or the other. I still think we should define this stuff in the formal monster manual when we have something more quantified and less arbitrary.

**Comment by EliManthey** [comment]
I can get behind that, I think shapeshift would make a good survey topic to find out how others are using it in games.

**Comment by EliManthey** [comment]
Also, their alteration score can cover a lot of those things if they get to keep supernatural attributes. Spider webs were an example that came to mind.

**Comment by brianfeister** [comment]
Closing this after having labeled it with `backlog` so we can revisit later
