### ISSUE TITLE
Boon Focus Minor Clarification

### ISSUE THREAD

**Issue by Hassurunous** [openlegend/core-rules#193]
https://openlegend.mightybell.com/posts/976629

Minor fix suggested in the Mightybell forums that might help new players. 

Adding a short phrase to clarify that the caster "automatically succeeds at any level up to the highest level they can invoke naturally" would help to clarify the point that Jacob's players brought up.

**Comment by ucffool** [comment]
If Brian can chime in on the wording, I'll make the edit/commit. 

My suggestion would be:

> When you invoke the chosen boon on a single target, you succeed automatically and do not need to make an action roll. **The boon's power level may not exceed attribute and/or feat values.**

The rational is that if someone attained Boon Access III: Bolster and then Boon Focus I: Bolster, no attribute scores are used. It's wordier than _invoke naturally_, but since this is all about clarification, thought it was prudent.

**Comment by brianfeister** [comment]
Let's do

> You can invoke the boon at any of the power levels you could access via your other means.

**Comment by ucffool** [comment]
@brianfeister close
