### ISSUE TITLE
Did a big overhaul of Shapeshift boon.

### ISSUE THREAD

**Issue by istabosz** [openlegend/core-rules#21]
https://github.com/openlegend/core-rules/blob/master/boons/boons.yml#L448

Let me know what you think. I tried to clarify the movement mode thing in the "special" heading. Also noticed some disparities between the power level tags and the list in the effects. Think that's all cleared up now.

**Comment by brianfeister** [comment]
I like the direction you went with this, in particular, the thorny issue of giving flight to first level characters is interesting. And it's even done "free" given your decision to set flight as a Power Level 5 ability. 

So, my question is whether or not that's safe. Is it broken? I honestly don't know.

If it's not broken and we're giving flight to first level characters with a 5 in a given attribute, this should also impact the `Levitate` and `Flight` boons. Flight would also need to become PL 5 and Levitate could conceivably be as low as PL 3, but probably PL 4.

Before we had the `Boon Access` feat as a way of gaining access to a PL 6 bane or boon from first level, so that equates to a heft penalty / price to pay for that ability.  With this, as a Druid you're going to want Alteration 5 anyway, so you can then take `Boon Focus` to be capable of auto-shifting into a giant eagle at-will.

Thoughts @DMsShadow?

**Comment by istabosz** [comment]
Actually, flight was already listed as power level 5, but that must have been one of the inconsistencies I mentioned. In the power level tag you had 6 listed, but there was no power level 6 in the description. So, I think we should set flight at 6.

**Comment by brianfeister** [comment]
Oh wow, not sure if this was intentional, but your `Special` note actually gives us a clever way of being a bit more gradual about this. You made it so that non-standard movement modes are available but your speed is halved. That solves the problem of excessively fast overland movement via flight, but it doesn't solve the "I can reach places other people can't" problem.

To be fair, I had already decided not to worry about the latter, since `Levitation` can get you that as well, so this is an existing issue, not a new one.

But I like the idea of clumsy movement before you master it and making flight PL 6.

**Comment by istabosz** [comment]
Cool. Sounds all good.
