### ISSUE TITLE
Inspiring Champion trigger condition wording

### ISSUE THREAD

**Issue by jcte02** [openlegend/core-rules#213]
The triggering condition for this feat is 
>when you deal 10 or more points of damage to an enemy

Should it be changed to
>when your damaging roll exceed the enemy's defenses by 10 or more

?

**Comment by hmack312** [comment]
As far as I understand it, the original wording is better. The inspiring champion feat  seems like it is about watching your ally successfully harm an enemy and receiving a moral boost in the form of hp. This is different compared to beating the defense score because the enemy could have some form of damage resistance, or anything that prevents damage from being dealt without changing the defense score.
