### ISSUE TITLE
Psychic ability doesn't have any banes/boons

### ISSUE THREAD

**Issue by DMsShadow** [openlegend/core-rules#23]
Was just doing a run through as part of something else and I notice this. Is it deliberate, are we thinking of taking out the psychic ability, or has it just been missed off?

**Comment by brianfeister** [comment]
I removed the Psychic attribute after much deliberation and @istabosz recommendation. 

The problem is it was a shortcut to a wide range of abilities that would otherwise be acquired through investing in multiple attributes. I think the way it is without it, Psychic characters can choose between disciplines represented in Movement, Illusion, Alteration, Energy, Divination, and Enchantment. 

Thoughts?

**Comment by DMsShadow** [comment]
You know me, I have lots of thoughts. In this case I definitely agree. To me I'd see psychic powers as a flavor (without the u) for the abilities rather than needing one of it's own.

**Comment by DMsShadow** [comment]
PS We need to remove it from the character creation section of the rules though.

**Comment by brianfeister** [comment]
I believe that as of https://github.com/openlegend/core-rules/commit/0fffc4701a33f45c54238f5015a66faf965a250d all remnants of `Psychic` references should be gone and the website should now be updated.
