### ISSUE TITLE
Add Rules for "Group Action Rolls"

### ISSUE THREAD

**Issue by brianfeister** [openlegend/core-rules#238]
We've discussed this before, but never noted it as a to-do. 

The idea is pretty straightforward, we err in favor of the players with something like:

> GROUP ACTIONS
>  If more than one character can contribute to a given action in a meaningful way, have each one choose an attribute and describe how they're leveraging their attribute to contribute. Then have all participating players make an action roll with their chosen attribute. Figure out the number of successful vs. failed action rolls. If there are more failures than successes, the group action roll is a failure, otherwise it is a success.

**Comment by BuildAndDie** [comment]
Does this limit the "every roll matters" philosophy?

Instead of having all participating players make an action roll, why not have them give advantage to one player making the roll? Assist Ally is already a thing in Combat, seems like it could be extended to actions outside of combat?

I'm guessing this might be to address something where a group is all acting together, like sneaking through a courtyard, where you would normally have everyone roll "sneaking/hiding" and as long as more success than failure, the whole group is good at staying hidden?

IN that case, perhaps someone who isn't able to contribute to a given action in a meaninful way imposes Disadvantage. So you would add the Advantage and Disadvantage of the contributors for a final value for one player to roll?

Not sure which way is easier... more rolls... or figuring out Advantage/Disadvantage.

**Comment by istabosz** [comment]
I think @brianfeister 's wording works best for situations like everyone sneaking, where the group's collective success determines the outcome.

It still works well enough for situations where multiple people are working together to achieve a singular task, such as two PCs attempting to hack a computer. It might not be a perfect fit, but I think it's best to keep things simple and not create too many niche mechanics.

We just need to make it clear that the GM can make the call about who gets to contribute, for things like Perception or Learning rolls.

**Comment by brianfeister** [comment]
Agreed. Also the phenomenon of everyone at the table wanting to roll their dice is just too strong, it needs to be accommodated. That and we are actually grouping the rolls and determining success via many rolls counted as one. So that aggregate roll still matters.

**Comment by istabosz** [comment]
Done. I've added it to chapter 2 and the SRD.
