### ISSUE TITLE
Combat: Interrupt > Defend - Clarify movement benefit

### ISSUE THREAD

**Issue by ucffool** [openlegend/core-rules#259]
I tried to get some discussion on this but failed, so it just needs to be a call and a clarification over a few things from @brianfeister  and @istabosz :

> As part of your defend action, you may also move up to half of your speed at any time during your action. If you are adjacent to your ally when moving, the ally may choose to move with you.

1. If they are choosing to move with you, is this considered forced movement or does it trigger opportunity attacks?
2. Can they choose to move around you if they are adjacent, even though you are stationary. 
3. Should wording be added that the attack must resolve before movement, or can you literally Defend by moving them out of harms way, negating the attack in the first place?

**Scenario:**

`Adjacent ally who is near death has a golem's fist coming down upon her. You Defend, attempting to block the attack. You succeed in doing so and have two options: Both move away from the creature 15' feet (possibly triggering an opportunity attack), or move her behind your position (no longer adjacent to the creature), maintaining your position, between her and the golem.
`

In the above scenario, a triggered opportunity attack negates the Defend action. It doesn't have a feel good outcome. Forced movement and being able to move the ally without moving yourself (they must still be conscious to qualify for 'move themselves') feels heroic and defensible, story wise.

**Comment by brianfeister** [comment]
@istabosz You're up at bat.

**Comment by brianfeister** [comment]
Sounds good to me. For `#3` I was going to say we should clarify that "Your countering (Defend) action happens first, then the allowed movement" so that we're clear that you're standing there when the incoming attack lands. But that creates a problem -- the movement originally was meant to be an option for a melee usage of `Defend` to be a "I rush in and tackle / Defend my ally with my 15' movement".

Thoughts on this @istabosz this seems tricky but only defending melee characters adjacent to you does seem like a big penalty for melee characters. But maybe we do just that, since melee characters have an edge over ranged characters due to their ability to dual-wield / two-handed wield to get Advantage 1.

**Comment by ucffool** [comment]
I agree it's tricky, but after I wrote my idea (defend before movement) I realized that negates the great grenade example. I think it's just wording: Movement can occur anytime as part of using Defend, but it cannot negate the attack itself.

**Comment by istabosz** [comment]
I think we are talking about the ally's movement. I don't think it really matters which one occurs first. We just need to say "If your defended ally's movement takes him out of reach of the original attack, he is still subject to the attack." But better worded than that.

**Comment by brianfeister** [comment]
Agreed.

**Comment by istabosz** [comment]
Updated in core and in the SRD. I made an in-the-heat-of-the-moment executive decision to make it so that neither character's movement provokes Opportunity Attacks. It saved an extra sentence, made the rules simpler, reduces potential extra rolls at the table, and makes things more fun by opening options rather than limiting them. I don't think it's OP because the defender is using up a major action.
