### ISSUE TITLE
Bane focus is tagged with Might

### ISSUE THREAD

**Issue by istabosz** [openlegend/core-rules#26]
Don't know too much about github code, but this doesn't seem quite right to me.

"Might" is listed as the only attribute in the tags for Bane Focus. I'm assuming the tags should include either all of the attributes or none of them.

**Comment by brianfeister** [comment]
"Tags" are a whole mess we haven't gotten into yet. Right now they do nothing, in the future I will have to do lots of work and find a way to add filters in the searchable list. The idea is that you can specifically look up "feat chains", "non-combat" feats, "combat" feats, and other ways of categorizing or grouping feats besides just their attribute prerequisite. 

So that area is often wrong or a wasteland but doesn't impact anything yet

**Comment by istabosz** [comment]
K. So, should I just ignore them for now?

**Comment by brianfeister** [comment]
Yeah, I mean feel free to just make them match whatever very rough approximation of a pattern you see elsewhere.

**Comment by istabosz** [comment]
10-4
