### ISSUE TITLE
Make "Adventuring Packs" somehow multi-genre

### ISSUE THREAD

**Issue by brianfeister** [openlegend/core-rules#267]

**Comment by DukeAnax** [comment]
Hiking gear?

**Comment by istabosz** [comment]
I think what we really need to do is just expand that list of gear to include multiple genres, like we have for weapons.

**Comment by brianfeister** [comment]
Agreed. To me it wasn't a "how" so much as a to-do task I assigned to you.

**Comment by jcte02** [comment]
Maybe we can add a guideline for custom-building a pack like it has been done for the weapons? So we guarantee that this is truly multi-genre.

**Comment by brianfeister** [comment]
I don't think we will need guidelines for building packs, since the game doesn't really track your wealth anyway, you simply start with whatever you want that is within reach of your Wealth Level.

**Comment by istabosz** [comment]
Okay, so as I was working on this, I thought maybe we should just remove these altogether. I don't think there is a way to make enough of them to cover everything, and they kind of go against the idea that you should only keep track of inventory that matters. I think during character creation, players can just add important things like rope, tools, lockpicks, laptops, etc. based on their character concept rather than us trying to make generic collections that catch all.

**Comment by EliManthey** [comment]
I think the packs should be scrapped personally. Just as our attributes can be versatile and imaginative so should our inventory. If we need a small item not worth marking on our sheet (a piece of twine) we should be able to roll for it with a simple d20 and a bonus determined by our wealth score. DC based on the complexity of the item. Just a thought.

**Comment by brianfeister** [comment]
OFF WITH IT'S HEAD! 💀

**Comment by EliManthey** [comment]
next logical question then is if we should keep bulky items

**Comment by brianfeister** [comment]
This has been removed.
