### ISSUE TITLE
Interrupt action wording modification

### ISSUE THREAD

**Issue by Cryogenic6891** [openlegend/core-rules#286]
Currently no real rules are established for 'holding' an action which has been brought up quite a few times on discord and mightybell.

After bringing this up on mightybell Brian suggested to reword the interrupt action to something like: "expend the next Major action you would receive" to reflect that a player can use an interrupt action to use up a major action that turn or before the next turn.

However the interrupt action also doesn't allow for an attack.

**Comment by brianfeister** [comment]
This is going to require input from @istabosz.

I don't know, I'm not trying to clone 4th Edition here. "Triggers" and "Delays" all get a bit too messy and complex I think. We can discuss this, but my thought is that it's obvious you can just "wait" and take your turn later in the initiative order. But I don't think we need to recreate 4th Edition D&D's ability to "ready an action" to attack when a trigger happens. 

At the same time, I suppose the reason we have this problem is because we embraced "triggered actions" when we included Opportunity Attacks.

**Comment by istabosz** [comment]
I guess it makes sense that we should account for someone who says "If an orc comes through the door, then I shoot him".

I don't think we should be as prescriptive as D&D is, though.

**Comment by brianfeister** [comment]
Agreed. Let me know if you have a rules text proposal fit me to review

**Comment by istabosz** [comment]
Here you go. This would go at the end of the initiative section:

**Delaying your Initiative**
If you do not wish to act when your turn comes, you may choose to delay your initiative, either by waiting or by preparing to react in response to some sort of situation. If you wait, you may take your turn at any time *after* another character has finished their turn but *before* another character has begun.

If you are preparing to react, then you should give a general description of what you are preparing for, such as "I'll act when a threat to come through the door" or "I'm readying my bow to shoot at an enemy who goes for the altar." When the triggering action occurs, you may choose to take your turn even if it interrupts another character's turn (such as if they are in the process of moving). Once your turn is complete, any characters who you may have interrupted may complete their turn.

If, by the end of the round, your triggering conditions were not met, you may take your turn as usual.

**Comment by brianfeister** [comment]
I think the title "delaying your I initiative" will cause people to think that your position in the initiative will be permanently altered. I think the word " initiative " and delay shouldn't be next to each other. 

Perhaps "preparing to react" would be clearer since it doesn't have the overlap with lots of D&D jargon which is a problem in a few spots in this proposal. 

Mechanically it sounds good.

**Comment by istabosz** [comment]
Can we call it "Delaying your Turn"?

The problem with the title "Preparing to React" is that these rules also include situations in which you are just holding off rather than waiting for some sort of triggering condition.

**Comment by brianfeister** [comment]
I don't know. I just don't like the overlap with D&D. I would be willing to remove the "waiting without a particular trigger" thing in favor of the great rule of common sense.

**Comment by brianfeister** [comment]
@istabosz I have a new proposal for this. Can we call it: 

### Waiting to Act

**Comment by brianfeister** [comment]
@istabosz reworded my proposal:

### Waiting to Act

If you do not wish to act when your turn comes, you may choose to defer your turn, either by waiting or by preparing to react in response to some sort of situation. If you wait, you may take your turn at any time after another character has finished their turn but before another character has begun.

If you are preparing to react, then you should give a general description of what you are preparing for, such as "I'll act when a threat to come through the door" or "I'm readying my bow to shoot at an enemy who goes for the altar." When the triggering action occurs, you may choose to take your turn even if it interrupts another character's turn (such as if they are in the process of moving). Once your turn is complete, any characters who you may have interrupted may complete their turn.

If, by the end of the round, your triggering conditions were not met, you may take your turn as usual.

**Comment by istabosz** [comment]
Yeah. I like that a lot. Seems to cover all bases

**Comment by brianfeister** [comment]
Fixed and released.
