### ISSUE TITLE
Legend Point Section

### ISSUE THREAD

**Issue by BuildAndDie** [openlegend/core-rules#333]
In Chapter 2:

Spending Legend Points
Before making an action roll, a PC may spend a maximum number of legend points equal to their level plus one. For each legend point spent, they gain advantage 1 on the action roll.

The problem text I see is "Before making an action roll", this should be "Before or after" or another wording that shows you can choose to use the Legend Points after a roll. This is based on a discussion with Brian where he says he allows it to be used as a re-roll in that sense.

**Comment by istabosz** [comment]
I've made the change. The new text reads...

A PC may spend a maximum number of legend points equal to their level plus one in order to enhance a single action roll.

Before making an action roll, the PC declares how many legend points they are spending, and gains advantage 1 on the roll for each legend point spent.

Alternatively, a PC may choose to spend legend points after they make an action roll and are dissatisfied with the result. Each legend point spent applies a retroactive advantage 1 to the roll, allowing the player to roll additional attribute dice and recalculate the roll completely as if it was made with the new advantage total.
