### ISSUE TITLE
Genesis Power Level 1

### ISSUE THREAD

**Issue by BuildAndDie** [openlegend/core-rules#339]
Power Levels 3, 7, & 9 all state the Invocation time within the Power level description.

Power Level 1 states no Invocation time.

I'm guessing it is suppose to be either 1 min, or a Focus Action, but not sure what Brian/Ish intended for it.

@istabosz @brianfeister

**Comment by BuildAndDie** [comment]
Also is there a size limit needed for how much you can create with a single invocation? (see Power Level 3)

**Comment by brianfeister** [comment]
Size limit sounds good, also can we standardize the Invocation time in the proper place at the header?

**Comment by BuildAndDie** [comment]
Got a player planning on using it Sunday, What is the invocation time suppose to be?

1 min... Focus action?

**Comment by istabosz** [comment]
@BuildAndDie I think I already took care of this in an update last night. The new text for PL 1 is:

You can create <emphasis>temporary</emphasis> non-sentient matter (plants, dirt, water, vines, etc.), anything created in this way deteriorates or decomposes to become useless after 1 hour. Using this boon you can create 1 cubic foot of nonliving matter per attribute point of the invoking attribute. The invocation time for this application is 1 hour.

That covers the invocation time issue and the size limit issue.

@brianfeister I don't think the invocation time needs to be standardized, because the different applications are pretty wide in potential. You don't want someone able to crank out a WL 2 item every hour I imagine.

**Comment by brianfeister** [comment]
Ok, that's fine. There's alot of questions that come up about "Instantaneous" for durations that are technically "permanent". We should think about this, I'd say.

**Comment by BuildAndDie** [comment]
Part of the application of that was so it had combat potential. 1 hour invocation makes it very non-combat applicable. I was originally suggesting 1 min.

Through boon focus II, the time could be reduced to 1 min. If it was 1 min, then it would only reduce down to a focus action.

**Comment by SamWilby** [comment]
To expand on @BuildAndDie , taking an hour to create something that only lasts an hour seems bad even if it's only PL 1. The idea that the suggestion came from was the based on the ability to quickly conjure up a simple item (nothing combat related) and even with Boon Focus this still takes 10 minutes. 

Think Druidcraft cantrip in D&D; it's easy enough to handle with generic rolls but the initial point of this added PL (I was the one fielding the suggestions on Discord that lead to this) was to give guidelines to that sort of rapid production. 

It seems unlikely to break anything if the time is dropped to 10 minutes (1 minute with Boon Focus), unless I'm missing something? I appreciate the desire to standardise the invocation times, but PL 1 just seems useless in the recently suggested form.

**Comment by brianfeister** [comment]
@SamWilby Agreed. I think we should go ahead and limit the high level ones as well by making them have long invocation times, while PL 1 can be 1 minute (reduced to 1 Focus Action by Boon Focus).
