### ISSUE TITLE
Rework the Indomitable Endurance Feat

### ISSUE THREAD

**Issue by istabosz** [openlegend/core-rules#34]
Right now, this feat costs 3 but only protects you from one bane, so it's overpriced, and also just a bit boring.

What do you think of this:

You are immune to the fatigued bane when it is caused by natural sources (such as a forced march, starvation, or swimming long distances). If you suffer the fatigued bane from a supernatural source, you ignore the first level inflicted in any given 24 hour period.

**Comment by brianfeister** [comment]
That might be fine, but the reason it's for just one bane is because this is the Berserker's ability to rage one extra time per day, which is powerful. I don't know, maybe even then it's not worth 3 points, open to making it 2 for that reason, but that's the main use of this feat. I like your addition of an effect that's appealing to non-Berserkers though.

One thing your comment reminds me of is the `24 hour period` stuff which is really awkward, I can't even remember how it ended up being that, perhaps it was just to be different from D&D where you can rest for 8 hours and theoretically do multiple rests and multiple recharge of abilities.

Perhaps you should scan all of the references to `once per 24 hour period` and replace with `after a long rest, up to once per day` (not sure what to replace long rest with, don't want to use D&D terms if we can help it

**Comment by istabosz** [comment]
Sounds good. I realized for this feat we don't really need to reference a time, I think. We could just say you ignore the first level of the fatigue bane. Meaning, always reduce your level by 1. Also, is this feat meant to just have two tiers?

**Comment by brianfeister** [comment]
Sounds good. Two tiers might have been an attempt to prevent "infinite rage", but just like other feats, it's all diminishing returns so I'd be fine with increasing the number or tiers.

**Comment by istabosz** [comment]
Roger Dodger. Over and Out.
