### ISSUE TITLE
Companion Level

### ISSUE THREAD

**Issue by Hassurunous** [openlegend/core-rules#343]
On the Feats you are allowed to take for Companion, several say that they scale with the level of the NPC. 

What level are Companions for the purposes of these feats?

**Comment by brianfeister** [comment]
@istabosz under "Simple Build" (https://github.com/openlegend/core-rules/blob/master/core/src/08-running-the-game/01-chapter-seven.md#simple-build) we created a pretty large problem. We were trying to simplify for GMs, but later Companions were given access to the feat list for "Simple NPC Builds", so now, where it says "Attack Specialization (**tier equal to NPC level, max 9**)" this is no longer about NPCs only, and it implies that a Companion via the Companion feat would for a level 9 character might receive Attack Specialization 9 for the cost of one feat.

**Comment by istabosz** [comment]
I think we should just specify that the companion purchases the feat at tier 1. If it wants to increase the tier, it needs to spend another feat on that.

**Comment by brianfeister** [comment]
I suppose my comment [over here](https://github.com/openlegend/core-rules/issues/341#issuecomment-288133451) (https://github.com/openlegend/core-rules/issues/341#issuecomment-288133451) should be on this instead, but still, I think Companions getting feats is our main problem. We should de-emphasize them as a free attempt at a BONUS character, and instead double down on them being very simplistic and more oriented toward plot devices rather than viable characters that also get feats

**Comment by EliManthey** [comment]
what if the player and companion shared a feat point pool...may be a bit complicated but it's the only way i can think of to still allow a companion to have feats
