### ISSUE TITLE
Multi-Boon Expert

### ISSUE THREAD

**Issue by Hassurunous** [openlegend/core-rules#344]
We talked in the Discord chat about including the bonus from Boon Focus into the calculation for Multi-Boon Expert, since both Boon Focus and Multi-Target Boon Specialist are prerequisites for Multi-Target Boon Expert. 

Suggested changing the wording to " When multi-targeting a boon for which you have the Boon Focus feat, you do not need to make an action roll if the disadvantage normally incurred from multi-targeting is completely negated by your Multi-Target Boon Specialist and Boon Focus feats. Your invocation automatically succeeds."

**Comment by brianfeister** [comment]
Too powerful to give auto-success with for 3 targets. Also, it removes the need to take Multi-Target Boon Expert because Boon Focus 3 ramps up to Advantage 5, so you'd be auto-succeeding for 6 targets at that point, for only 15 feat points. Yes, 15 is alot of feat points, but 9 of that is on Boon Focus which has an incentive of it's own.

**Comment by Hassurunous** [comment]
Can I suggest removing Boon Focus from the requirements then? As is, Multi-Target Boon Expert doesn't actually interact with Boon Focus at all, nullifying the purpose of 3-9 feat points, depending on how many you spend.

**Comment by brianfeister** [comment]
I think you might be misreading the description @Hassurunous. It says:

```
When multi-targeting a boon for which you have the Boon Focus feat
```

The whole point is that you don't get auto-success via this boon unless you have Boon Focus. This is an important balancing factor, removing it would be too powerful.
