### ISSUE TITLE
Companion Fix

### ISSUE THREAD

**Issue by Hassurunous** [openlegend/core-rules#348]
The previous issue about Alternate Form got a bit derailed dealing with Companion, so I'm moving that discussion over here. 

Link to the previous thread: https://github.com/openlegend/core-rules/issues/341

Summary: Companion can be extremely powerful, especially at higher levels.

Issues being presented, both in old thread and as new info in this thread:
- Companion III at level 9 has 165 Attribute Points compared to a level 9 PC having 112. These points are restricted to be spent in as 9,8,7,6,5,4,3,2,1, but it doesn't change the fact that Companion is getting 43 more Attribute Points worth of Attribute scores over a PC
- Companion II at level 9 gets 120
- Companion I at level 9 gets 84  
- Companions get access to up to 3 feats. Nearly every feat in the NPC Feats table (which Companion also uses) are 3 Feat Point feats, meaning that the PC has, effectively, not lost any Feat points for their investment into the Companion. This means they are also gaining an extra Major, Move, and Minor Action from their Companion.
- Companions are limited in their usability of Feats. Since they are limited to the NPC chart, they don't have access to narrative-friendly feats such as Flying (for your favorite bird companion), Hospitaler (for your fairy friend), Swimming (for your frog companion), Untrackable (for your stealthy wolf companion), or Climbing (for your gecko friend). 
- Companion allows you to simply get rid of your Companion at-will and get those Feat Points back. There is no risk involved with it as there is with every single other Feat (except the "Focus" Feats, which I believe suffer from this same issue). Losing your Companion (or your Focus) should be an opportunity for a quest, not something that becomes instantly rectified.

The proposed solution is letting the Companion take feats, but forcing them to draw further from your Feat pool at a cost of 3 Feat Points per Feat. Narratively and mechanically, this means that your character and your Companion are inherently linked. This may be a good thing, or not. 

Problems with the proposed solution:
- Even if you reduce the cost of Companion to 2 Feat Points per tier, Companions are still significantly more versatile than a PC, due to their high Attribute scores
- If the PC is forced to invest their Feat Points into Companion and that Companion is lost, they suddenly experience a massive power spike because they get a ton of Feat Points back. Granted, this is partially already in the rules, but imagine a player getting back 15 Feat Points, instead of 9. Entire character concepts can change with that amount, all because you lost a Companion? This doesn't seem to make much narrative sense to me, but I understand that we should possibly gift back the points if they lose the Companion in some way if we do not offer an alternate solution.
- Forcing players to invest so many Feat Points into their Companions, especially at low levels, will significantly negatively impact their decision to even try the Companion feat. (Note: I've already had my player say he will be switching to Summon instead of Companion if this change goes through in our game.)

I understand the desire to fix Companion. I feel like it has a host of issues, especially in higher-level play, but I don't think this is the way to do it. 

My proposal:
- Expand the NPC Feats table to allow for more interesting, diverse NPCs and Companions
- Reduce the Attribute points available to Companion. Instead of saying they have a certain spread of Attribute Scores, give them a number of Attribute Points to spend, just like players, so they can feel their companions grow with them. 
- Give them a limited Feat Point pool. (Perhaps 3 Feat Points every other tier).
- Reduce the cost of Companion to 2, while adding an extra tier. Tier 4 Companion would have half the Attribute Points of a PC and 6 Feat Points to spend on feats still limited to the newly expanded NPC feats list. 

I'm happy to listen to any feedback on this idea and adjust it. I really just want players to feel they have the agency to create the Companions that support their stories the best they can. I love this game, and would love to see it grow and expand to tell the stories inside people's hearts, and I think Companion is an incredibly powerful tool in that arsenal.

**Comment by brianfeister** [comment]
I feel bad for being very curt in response to a very long message, but I'm not really planning to do this. Companions NEED to stay simple because they slow the game down if they approach the complexity of playing two characters. 

Your proposal doesn't fix that problem so I'm not on board. As a side note, the `Companion` feat cost is currently 2 after my recent adjustment. 

> 3 feat points every other tier

Does this mean I spend 4 feat points on 2 tiers of companion and get 3 feat points?

> Expand the NPC Feats table to allow for more interesting, diverse NPCs and Companions

The companion feat should not be used for either power-gaming, or hogging the table spotlight by playing 2 full-blown characters. Some groups can still choose to go that way, but it is de-emphasized when the capabilities of Companions are less. 

The only real reason for people to not go with the feat after the recent changes is because they're more concerned about power gaming than they are about roleplaying. And that's fine by me. I would still use this feat in a heartbeat, and I can be just as power-gamer-ish as any anyone else.

**Comment by Hassurunous** [comment]
I don't even like Companion for power-gaming, I much prefer Summon and Animation. I prefer Companion for its Narrative possibilities. 

I think the proposed fix seriously gimps Companion at early levels without fixing what I believe will be the ultimate problem with Companion at higher levels. It reduces the power across the board for a feat which was already regarded as being fairly mediocre for play outside of high-level power-gaming.

**Comment by brianfeister** [comment]
The idea that the feat was mediocre honestly makes **no** sense to me at all. Can you tell me why that's the case?

At 1st level, I can have two characters, one of them has an Attribute Score of 5 and no special combat bonuses (my main character) and the other has an attribute score of 4 and **Attack Specialization III**. Can you explain how that's mediocre? Because mathematically, it is stronger at 1st level than **Multi-Attack Specialist** dual wielding Rogue, who gets 1 move and 2 attacks, with Advantage 1 at best. The **Companion** character gets 2 moves, 2 HP pools, and 2 attacks - one at Advantage 4 with a Focus Action, the other at Advantage 2 (Focus Action + Two-Handed bonus, for example.

**Comment by Hassurunous** [comment]
6 Feat Points at Level 1:

- Boon Focus II (Summon Creature) (6 feat points): I can summon up to 4 creatures with 0 Advantage/Disadvantage, each with Attributes 3, 2, 2. Each of these creatures gets their own Major/Move/Minor Actions, I can give them each different stats, and if I ever need them I can turn it off at will and resummon them. (Attribute Points total: 12-48+ depending on how many you summon). 

- Boon Access VI (Animation) (6 feat points): I can permanently summon a companion whose highest attribute score is equal to or less than my highest (assumed, 5). This creature can (or, at least it doesn't say that it can't) benefit from armor and such, just as a Companion. Also, I can summon as many of these as I wish. In a single day, I could have 3 of them, if I was willing to take a point of Fatigue for not resting. I now have 3 Companions, the only difference being that they could actually have higher potential Attribute scores and they don't technically have to listen to me (although, technically, neither does the Companion). Now I have 3 extra Major/Move/Minor actions to use. I can also get all of my feat points back without losing the summoned creations by 4th level if I put points into Creation/Entropy. (Attribute point total: ?? Theoretically infinite depending on how many your GM lets you summon.)

- Companion II (6 Feat points before fix): I get 1 extra Major/Move/Minor. It gets 2 Feats from a limited list, the most powerful probably being Attack Specialization and Multi-Attack.Assuming you put both it's feats into those two, it could, at best, have one or the other at Rank 2. It's max attribute score is 4, it also gets a 3, a 2, and a 1. (Attribute point total: 20)

- Companion III (6 feat points post fix):  I get 1 extra Major/Move/Minor. It gets 0 Feats. It's max attribute score is 4, it also gets a 3, a 2, and a 1. (Attribute point total: 20)

If you had a choice between these, even as a narrative-focused player, it makes way more sense to be a ranger that "healed a wolf back to life from the brink of death" with Animation or "summons woodland creatures" than a ranger that took Companion.

**Comment by Hassurunous** [comment]
Companion is supposed to be the character that grows with you. Your companion that is beside you through your journey. It doesn't need to be super powerful, but it should feel valuable, fun, and "cool."

The only real "problem" with Companion before was at high-level play and when it was exploited with Alternate Form. If Alternate Form is causing the issue, fix Alternate Form. If Companion is overpowered at high-level, look to what part of it is causing issue in high-level play. We haven't even addressed Animation in high-level play, which could be just as strong (if not stronger) depending on how GMs rule it, both before and after the nerf to Companion.

**Comment by brianfeister** [comment]
* Your Boon Access VI example doesn't work because you have no control over those creatures in any long-term scenario, so that's not even an option until Level 2 with Unending Charm and then you'll need 2 specific attributes with scores of 5. Not the same as companion that has zero prerequisites.
* The "swarm tactic" really is overpowered it's the only one that's far out of line, so it's a question of whether to leave it or not.  Not that your "Zero Disadvantage" comment does not "auto-summon" them, which means that you're failing to remember they're not available on round 1 and they might not be available on round 2 or 3 either. Your 4 summoned creatures have lower attributes, defenses, and HP, but to be clear, Summon Creature is very powerful. Let's go ahead and knock it down a peg ;) ... honestly, my Rogue baseline is a good example we should be thinking about. 

Companion is a simple character that grows with you, that's still true. If you want it to be complex you can spend feat points to make it so.

Animation in high level play is not that difficult, you need potent bane + unending charm to do anything at all, and really, the problem isn't with animation, it does nothing to guarantee you control. Unending Charm does that, and the reason is because it's one of those "leftover" rules from when the system was more broad and less quantified. We just need to add a "max thralls = attribute" limitation like we did to Summon Creature and then that's fixed as well. Then it requires Entropy 6 + Influence 5 + Unending Charm + Potent Bane + LOOOTS of time and a generous GM that let's you amass an army without being interrupted and you can have our max of 9 thralls.

**Comment by Hassurunous** [comment]
The only person I've ever heard of forcing you to use Unending Charm on Animated creatures is you, Brian. 

Everyone else I've talked to about it rules in the player's favor, asks for relevant rolls (Persuasion, Deception, Presence), or role plays the creation to see how it plays out. Certain creatures could probably be intimidated into service with a show of power (Might or any Extraordinary Attribute), convinced that it is in their best interest to serve (Logic), or even tortured into service (Immobilize + anything really).

**Comment by Hassurunous** [comment]
Perhaps Summon needs a nerf, sure, I'll concede I haven't researched that one quite as long as I've spent researching Companion.

**Comment by brianfeister** [comment]
I hear ya. If people aren't playing Animated RAW (which says there is zero special bond) then that's not my problem. You can also go out and torture a village of 100 peasants and force them to obey you if we're going into the story implications of things. Auto-creation of thralls is very different from using social skills to win followers, which has nothing to do with the Animation boon.

**Comment by Hassurunous** [comment]
Just because there is not special bond doesn't mean there's no reason (narratively or mechanically, given the examples I listed and countless others) for the creation to stay with you. It's not violating RAW, in any way. RAW just says there is no "special bond", which is totally open to interpretation. Given this, and the fact that most GMs are pretty lenient when it comes to PC narrative, it's perfectly reasonable for you to be able to "tame" your creation pretty easily, or at least to convince the Animated companion to stick around for a bit and attack the things that attack it.

Also, you get those Feat points back at level 3 and can still keep your Animation(s) if you invest attribute points in Creation or Entropy, unlike with Companion. Heck, if I animate the corpse of a bandit and offer to pay him I've probably got as loyal a companion as Companion, and I get my feat points back soon, and that character probably had his own feats, depending on the NPC. Animation doesn't even say the creature doesn't get whatever feats/perks/flaws...etc. that it had in life, so it could be reasonably assumed that if I animate the mercenary with Multi-Attack Specialist that he'd still have it.

**Comment by Hassurunous** [comment]
Just a huge shoutout to Brian on this closed issue. Thanks for hearing me out in the Discord. I'm glad we could bring everyone to an agreement on the proposal. I'm super excited to show my players the new Companion. I told the one who's already using it about what we decided in the Discord and he is thrilled.
