### ISSUE TITLE
Increase lucky cost and eliminate extra tiers?

### ISSUE THREAD

**Issue by istabosz** [openlegend/core-rules#35]
Seems like a pretty good feat. I think it should probably be worth 2 points. Also, I could see this one being kinda annoying for the GM (and other players too) if the player can do it more than once a day. I'd suggest keeping it at one tier. Whatta ya think?

**Comment by brianfeister** [comment]
Agreed. I just went ahead and made the change now. I introduced "once per day" instead of "24 hour period". We can change it but my frustration with "24 period" was at a peak. I had in mind to just simplify. We don't do very much "X per day" stuff in Open Legend, so maybe it's fine to just say it that way.
