### ISSUE TITLE
Reckless

### ISSUE THREAD

**Issue by BuildAndDie** [openlegend/core-rules#359]
The current wording of Reckless is

"While you are in a battle trance, on your turn you may choose to inflict 5 hit points of damage on yourself to make an additional attack as a minor action."

The "additional attack" is the point of clarification. Does this me my major action has to be an attack for me to be able to use reckless?

I know a big way I used reckless was, got a bane on me, used my move to resist it, used my major to move, and then used my minor via reckless to attack. Though if it is an "additional" then I wouldn't have been able to use reckless in that case.

The more obvious case is, boon with major, attack with reckless.

I figure this is the RAI, but the RAW might cause you to think you can't.

**Comment by BuildAndDie** [comment]
Also, and this one isn't as big, but the name: "Reckless Frenzy"

Is "Frenzy" a hold over from the old name of Battle Trance for berserker. Maybe tthe name "Reckless Attack" or something along those lines makes more sense?

**Comment by ucffool** [comment]
Yeah, rewording this to say "1 additional Major Action that can be used only for an attack action.

**Comment by BuildAndDie** [comment]
nothing that complex:

inflict 5 hit points of damage on yourself to make an attack as a minor action.

**Comment by BuildAndDie** [comment]
just remove additional

**Comment by brianfeister** [comment]
Ok let's call it "reckless attack"

**Comment by ucffool** [comment]
I suppose keeping it a minor action is what stops it from being abused over and over?

**Comment by brianfeister** [comment]
@ucffool Yup, it's intentionally a minor action to say "you get 1 free bonus attack with no penalty each round for the cost of 5 HP in damage" ... without this limitation, there would be a VERY strong build that takes Boon Focus III Regeneration and combos with this to always deal tons of damage to themselves and heal it with a payoff of a ridiculous number of attacks. It's a neat idea, but it is broken since those attacks don't have  penalty.

**Comment by brianfeister** [comment]
Closed by https://github.com/openlegend/core-rules/commit/123fff2172aa638f784e8a6478f9feb481c27343
