### ISSUE TITLE
Bane > Disarmed (PL3) - workaround for PL6

### ISSUE THREAD

**Issue by ucffool** [openlegend/core-rules#364]
In today's game, a player decided to `Disarm` a foe of his sickle at PL3, drop it at their feet (it says *up to 15 feet away*, then use a minor action to pick that weapon up. Essentially, and I found no good reason to not allow this, he accomplished Disarmed PL6 at PL3.

Adding the issue here for possible adjustments.

**Comment by brianfeister** [comment]
@ucffool what attribute / weapon / narrative did they use for having such precise control over it? Basically the intent is that whatever method you use to disarm lacks the control and precision to do something like that. 

This is a bit abstract, but If I were GMing it, I would explain that landing within 5' X 5' area isn't very precise. I would have it land in the intended square, but have the player roll an Agility check (minor action) to see if they were able to land the weapon close enough that they could reach down and grab it without provoking an attack of opportunity  (exposing your back to the enemy). 

Also, I'm fine with it as a thing that's mainly available to melee characters, since I think they're slightly behind extraordinary characters.

**Comment by ucffool** [comment]
He was [a rogue](https://openlegend.heromuster.com/character?s=pregen-fantasy4) with a bare fist and a dagger in the other hand. Narratively, he cut the creatures hands (**Agility**) forcing him to let it go, then reaching out with his free hand to pick it up off the ground.

**Comment by ucffool** [comment]
Also, go ahead and close the issue (I'm also okay with the melee character benefit) if you still believe it is working as intended. :)

**Comment by brianfeister** [comment]
Yeah, having the PL 6 version listed there to suggest that you not be able to snatch the weapon at lower power levels is about the best we can do here. Narrative stuff is squishy
