### ISSUE TITLE
Two Weapon Brute needs clarification

### ISSUE THREAD

**Issue by istabosz** [openlegend/core-rules#38]
A few things:

1) Do we ever define exactly how two weapon fighting works? It just grants an extra attack, correct?
2) This feat allows you to wield a two handed weapon when dual-wielding. Logically, shouldn't you also be able to wield a two handed weapon in one hand when only using one weapon?

What if we re-title it to Heavy Weapon Master and change the description: You can wield two handed melee weapons in one hand. If you do, you still gain the usual advantage to attack rolls for two handed melee weapons.

**Comment by brianfeister** [comment]
Great suggestion, thanks for catching that inconsistency. We used to have "Two Weapon Style" or something like that, but it was renamed to "Multi-Attack Specialist" which fits our Open Legend philosophy much better :)

**Comment by brianfeister** [comment]
And to be clear, I think your proposal sounds great, just making the feat allow you to wield over sized weapons and then you can decide to do something else with your free hand or take the other feats to get a Defense bonus. 

I suppose it does leave some slight awkwardness around wielding a pair of two-handed weapons and the meaning of that... although, I suppose what makes sense is to drop "Multi-Attack Specialist" as a pre-requisite so that this can be taken without being part of the feat chain or tied in any way to dual wielding.

**Comment by istabosz** [comment]
Roger. I changed it and dropped the multi-attack specialist prereq.
