### ISSUE TITLE
Suggesting different wording for Animation

### ISSUE THREAD

**Issue by MarkVelthuis** [openlegend/core-rules#397]
I've been told that this boon has the amount of GM discretion it has, to reduce the number of hard limits the animated being(s) have. However the wording suggests a few odd limits that seem to conflict with this intent. 

1) The boon is written in a very magic-y life/undeath way. Suggesting normal creatures or their undead versions. It makes no mention of possibilities like golems, AI controlled robots, or non-sentient ways of animation like puppeteering or wireless remote control. 

2) "Since it was birthed through magic, it has no concept of family, creator, or parent."
The limit of having no concept of family, creator or parent also has no effect on the actual mechanics of the boon, and reduces the possibilities of the boon for no seemingly good reason. 

3) "However, you cannot use this boon to animate supernatural creatures, such as dragons or basilisks."
Since the GM is allready in control of what the player is able to animate, this rule seems to have no place in the wording of the effect. 

4) "Your ability to animate the creature grants no permanent control or influence over it." 
Since the creature's disposition is also up to the GM, this line of text seems unnecessary aswell. 

5) Considering point 4, it also seems to make little sense to have the creatures be created with the charm effect on them.

**Comment by SamWilby** [comment]
1, 2 and 3 all seem like wording that needs changing to increase multi-genre friendliness. Is "supernatural creatures" meant to exclude extraordinary attributes? If so then that should probably be written out properly.

Number 4 I disagree on; it probably only needs a single word adding:

> "Your ability to animate the creature grants no **inherent** permanent control or influence over it."
The player's level of control is dependent on how the GM roleplays the companion, but it shouldn't be intrinsically under their control just because they were the ones to invoke the boon. This boon creates a new NPC, not a follower, and this line is simply to make that clear to both player and GM.

Number 5 was added when Animate was changed to its current form. It was considered necessary to give players time to "strike a deal" with the animated creature without making the creature inherently servile. Again, this is a narrative _and_ rules prompt for player and GM both; the GM knows that the creature should start out friendly and then change after the bane is resisted or expires, and the player won't be surprised when that happens. This is intended to allow players to raise powerful and possibly violent creatures without getting into combat _immediately_ after the boon is complete. I think this is fine for multi-genre; even golems and robots can "change their programming" or similar.

**Comment by brianfeister** [comment]
@istabosz thoughts here?

**Comment by istabosz** [comment]
Agreed. This feat could use some work. Here is a proposal to address some of the issues raised above:

**Description**
You create a being of subhuman intelligence that persists indefinitely and autonomously. It might be a living creature, an undead fiend, a sentient construct, or any similar creation possessing lifelike properties. Examples of this boon in play include a necromancer creating an undead bodyguard, a mad scientist forging a subhuman being from body parts collected from a variety of corpses, and an engineer creating a cyborg from parts collected at a scrap yard.

**Effect**
You are able to create an autonomous being from inanimate material components, such as dirt, bones, water, vines, scrap metal, or sand (the materials used are subject to the GM's discretion). To do so, you must first spend 8 hours completing a ritual, experiment, or similar manufacturing process. After this process is complete, make an action roll to invoke this boon. If successful, the inanimate form is permanently imbued with sentience.

Your ability to animate a creature does not grant you the permanent ability to control it. However, newly animated beings are affected by the _charmed_ bane (see below), and thus treat you more favorably immediately following their creation.

The GM, not the player, is responsible for deciding the attributes and abilities of this animated creature and should follow the guidelines established by the "Simple Build" section for creating NPCs in Chapter 8: Running the Game. Creatures created using this boon are typically limited to those of subhuman intelligence, such as zombies, combat droids, and golems.

- **Power Level 6** - You can animate a single creature. Your invoking attribute score must be equal to or greater than the highest attribute score of the creature you're animating. With a successful invocation, the creature comes into existence with the charmed (Minor Charm) bane already in effect (no roll is required).

- **Power Level 8** - You may choose to animate a group of creatures: Either 10 creatures with a max attribute of 2, 5 creatures with a max attribute of 3, or 2 creatures with a max attribute of 5. In addition, the automatically invoked charmed bane is a Major Charm instead of Minor Charm.

**Comment by brianfeister** [comment]
Looks good to me

**Comment by brianfeister** [comment]
Fixed via 54edc769b03268fc7fbf48ad2280f452581bd122
