### ISSUE TITLE
Chapter Order

### ISSUE THREAD

**Issue by JVanGo** [openlegend/core-rules#427]
I've been reading through the chapters and I've noticed that some chapters are in an odd order, which makes the flow of reading feel a bit unnatural.

At the moment, we have this order:

1: Character Creation
2: Actions & Attributes
3: Feats
4: Perks & Flaws
5: Wealth & Equipment
6: Banes & Boons
7: Combat
8: Running the game
9: Special Equipment

- Actions & Attributes is a bit out of place as it contributes little to character creation (unlike the chapters after that) and seems to be more aimed at GMs.
- The Feats and Banes & Boons chapter should follow up each other (imo Banes & Boons should be first, but I can see an argument made for either one), as there are many synergies and interactions between those two.
- Wealth & Equipment seems to be placed a bit randomly between Perks & Flaws and Banes & Boons. I'd suggest putting it as the last chapter of the character creation chapters, as players probably will decide last on equipment, as OL doesn't put the biggest emphasis on items and equipment.

**Comment by BuildAndDie** [comment]
I think that makes sense, to have everything related to character creation up front, then the hows and such after.

Actions & Attributes are more on how to do rolls, how to do advantage/disadvantage, etc etc, so it would make sense to go right before Combat.

Character Creation
Feats (help to further define your character)
Perks & Flaws (even more defining of your character)
Banes & Boons (what your character can do
Wealth & Equipment (things your character will have on them)
Actions & Attributes (how to play)
Combat (how to play)
Running the game (how to play for the GM guide)
Special Equipment (things that fall under the purvey of the GM)

Seems like that could be a good order for "flow"?

**Comment by brianfeister** [comment]
Hey @istabosz I definitely need you to look at this and offer feedback!

**Comment by JVanGo** [comment]
I like your order better Jonathan, but I would reshuffle Feats, Perks & Flaws and Banes & Boons. I'd go with Perks & Flaws first, because OL emphasises on narrative and giving your character personality first fits that mentality. But I could also see Perks & Flaws as the last of those three, if mechanics should come first.

I would put Banes & Boons before Feats, as feats modify and impact Banes & Boons, but not the other way around. If you read Boon Focus first, but don't know what Boons can accomplish, than I feel the reader misses context, that's why I feel B&B before Feats would be a more natural progression.

**Comment by istabosz** [comment]
I can definitely see the merit in reordering the chapters. It makes some sense to keep them ordered relatively similar to the steps of character creation. I like @BuildAndDie 's suggested order, but think that if we go with that we should switch Steps 5 & 6 of character creation.

**Comment by brianfeister** [comment]
@JVanGo @BuildAndDie @istabosz I'm looking at this just now and I realized a big problem with the proposal. We are hitting feats, banes, and boons before we get to attributes, which I think is a big problem.

**Comment by brianfeister** [comment]
I kind of suspect that if we want to do this differently, we need to actually need to break out a separate section like "Attributes Overview" that gets people thinking about this key ingredient in character building, and then have a later chapter that explains action rolls and gives the examples from each attribute.

**Comment by istabosz** [comment]
I feel like the Attributes at a glance tables are good enough to let people know the gist of what attributes do. Will enough people really need much more during the character creation process?

**Comment by brianfeister** [comment]
I can see your point, but I object to choosing feats (which are dependent upon attributes) before getting the drill down that explains what attributes actually are. Perhaps it's fine and I'm being pedantic. I don't know.  tough decision. What do they do in D&D? I think "feats" come quite a bit after other things, but I guess that's because feats really are an after-thought (optional even, in 5e), whereas in Open Legend they are equivalent to the "Character level tables". This is a tough one.

**Comment by brianfeister** [comment]
Also, if we decide that we're OK with showing off Feats, Banes, and Boons before explaining attributes (kind of dubious to me, since so many feats banes and boons require an understanding of what attributes are), I wonder if Banes & Boons shouldn't be earlier. It's been said many times to me, by **many** people that Banes & Boons are the big selling point and differentiating factor that make Open Legend completely different from most every other RPG.

I think this serves to highlight that we need to explain at least a little bit about the mechanical component of attributes, banes, and boons (a "teaser" of sorts) in **Character Creation** if we're going to push **Actions & Attributes** to immediately before **Combat**.

Here's a potential order for that:

1. Character Creation
1. Banes & Boons (what your character can do)
1. Feats (help to further define your character)
1. Perks & Flaws (even more defining of your character)
1. Wealth & Equipment (things your character will have on them)
1. Actions & Attributes (how to play)
1. Combat (how to play)
1. Running the game (how to play for the GM guide)
1. Special Equipment (things that fall under the purvey of the GM)

**Comment by istabosz** [comment]
The more we talk about it, the more I like keeping chapter 2 where it is.

Attributes are the core of the game, and newbies could get a ton of mileage out of nothing but chapters 1 and 2. I think @brianfeister is right that feats, banes, and boons don't make much sense without knowing how attributes work.

**Comment by brianfeister** [comment]
Yup, I'm leaning that direction as well. Also, I think the more narrative-first approach of the game is helpful with the Attribute roll examples to get people in the mindset.

**Comment by oconnor0** [comment]
Leaving Actions & Attributes as chapter 2 splits "how to play" into two different sections of the book. I think that will make it harder to find the rule I am looking for.

**Comment by brianfeister** [comment]
@oconnor0 that's fine but at this phase please only make comments based on proposed solutions that seem the best. Or just say "I prefer @BuildAndDie's proposal", for example

**Comment by BuildAndDie** [comment]
So for me, and part of the problem with the perspective of me is that I've been dealing directly with the system for awhile now (though not anywhere close to as long as @istabosz or @brianfeister ), the part that goes into depth on Attributes in the "Actions & Attributes" section is so............ long, I mean... really long.

I'll be honest here, I haven't actually read every single example there b/c tl;dr

Part of that is due to the fact I've been toying with the system in play now for awhile, and I have a pretty good grasp. The reason I am saying all that is it might actually be an overload to new people to even try and read all of that stuff when creating their character. System shock/overload. Whereas what is already in Chapter 1 covers pretty well what the attributes do.

You *could* take out the stuff about Attributes in the "Actions & Attributes" section and people would still be able to play the game, the part about Attributes just helps if you are thinking "Man, what can I do with Might", flip to that part and see the examples. The important part is Advantage/Disadvantage and legend points in that chapter.

Now, again, I'm saying that from my perspective of really diving deep into the system for the last 8 (I think?) months. I'm also saying it based on teaching my dad the system where the Attributes part in "Actions & Attributes" didn't even exist at the time.

---
I'm not saying my suggestion is the best, I like it, but I also like have the Banes & Boons up closer to the top as well. Brian's suggestion seems pretty solid that he posted above. In fact, I think I like that one better than mine. At first I was going to say have Perks & Flaws before the boons and banes, but knowing the boons and banes might help in deciding and realizing what the perks & flaws are and can do.

**Comment by brianfeister** [comment]
I think that's a great point, and I can't disagree @BuildAndDie ... when I first saw the "Challenging / Epic / Heroic" examples and that there were 3 for **every attribute** I was a bit flabbergasted. 

I do think that Attributes should come first, though, explaining the mechanics of them. 

I propose that we split Actions & Attributes and move the "Examples" section to Chapter 9, running the game, since that's alot of information that a player won't have to worry about so much, since their job is just to follow what the GM is doing and they don't need to understand "success with a twist" (we can point people to the "running the game" section for examples when we mention "success with a twist"). 

This will  put us back on the fast track to git people to a finished character as quick as possible. 

So that would be:

1. Character Creation
1. Actions & Attributes (what everything is built on -- **MINUS** the examples)
1. Banes & Boons (what your character can do)
1. Feats (help to further define your character)
1. Perks & Flaws (even more defining of your character)
1. Wealth & Equipment (things your character will have on them)
1. Combat (how to play)
1. Running the game ( **MOVE examples here**...how to play guide for the GM)
1. Special Equipment (things that fall under the purvey of the GM)

**Comment by brianfeister** [comment]
Ugh, I've been trying to implement my suggestion above and it doesn't work all that well. It's such a large chunk of content that it has the same effect in the GM chapter of creating an awkward gap -- it doesn't really work to put it at the **end** because it's not an afterthought, but if you put it **beginning** it's way too big and it runs the risk of making it so that everything else, needs it's own section.

As I'm sitting here typing this I was about to say "Meh, let's leave it where it is." But then I counted the pages... **13 pages** WOW, that is a really big TLDR; that someone is going to run into immediately when they hit chapter 2. Seems early to subject them to that. 

I don't even know... Separate chapter **before** "Running the Game" (GM Chapter)?

**Comment by JVanGo** [comment]
I like the idea of creating a separate chapter for all the example. I don't know if what's better to put it **before** or **after** "Running the game", but I think it's better suited to be there. Maybe call it the chapter "The Core Mechanic"?

**Comment by oconnor0** [comment]
Tagging off of @JVanGo's idea. How about the last 4 chapters becoming:

7. The Core Mechanic
8. Combat
9. Running the Game
10. Special Equipment

**Comment by brianfeister** [comment]
@oconnor0 that seems reasonable. Still looking for a follow up from @istabosz

**Comment by istabosz** [comment]
I have a hard time seeing how the examples would work as a chapter of their own.  I feel like they could be worked into the GMing chapter without feeling like an afterthought.

**Comment by brianfeister** [comment]
@istabosz I spent a while working with the text in layout form and moving it around in the GM chapter, it was surprising to me how difficult it was. Before we make the change, please let me know which two sections you would insert it between.

**Comment by istabosz** [comment]
I think it would go at the end of the chapter as the last section. The intro text just needs a bit of massaging to reframe it. Just because it's at the end doesn't mean it's an afterthought.

**Comment by brianfeister** [comment]
Ok, I'm good with that.

**Comment by brianfeister** [comment]
@istabosz I've moved it (sans massaging text which I'll leave to you). You can edit it on the `print-edition` branch

https://github.com/openlegend/core-rules/blob/print-edition/core/src/08-running-the-game/01-chapter-eight.md

**Comment by istabosz** [comment]
Cool. I just fixed up the intro text.

In light of these changes, I think that the previous "Actions and Attributes" chapter needs a new name. Can't quite follow what all of the proposals are at this point, but I think "The Core Mechanic" is a pretty good chapter title. We need to edit the intro text for that chapter as well based on the move, only ever so slightly. You want me to do that in the same branch @brianfeister ?

**Comment by brianfeister** [comment]
Roger that, same branch

**Comment by infernodemon2005** [comment]
following this, I think we have an awesome solution to the problem. just wanted to put my +1 seal of approval on it also lol

**Comment by istabosz** [comment]
@brianfeister Nevermind, just re-read the intro text for chapter 2, and it is fine as is.
