### ISSUE TITLE
Provoked

### ISSUE THREAD

**Issue by BuildAndDie** [openlegend/core-rules#432]
Is there a reason Protection is not included with Provoked?

**Comment by brianfeister** [comment]
Because this bane is the "draw aggro by projecting hostility bane" and that doesn't seem compatible with Protection. Don't you agree?

**Comment by BuildAndDie** [comment]
Ah, I remember the discussion from before on this now. I understand the reasoning, I'm sure protection could be flavored to fit this, but udnerstand it not being inlcuded in core

**Comment by BuildAndDie** [comment]
my mind was just thinking "this seems a very protection oriented thing to do" so that's why I wasn't thinking in the other frame of thought

**Comment by oconnor0** [comment]
I like Protection being able to inflict Provoked because that is a very protection thing to do. I think that Might inflicting Provoked is "drawing aggro by projecting hostility" while Protection inflicting Provoked is "using spells, shields, or knowledge of combat to deflect or upset attacks enough to inflict disadvantage or draw aggro".
