### ISSUE TITLE
Legend Points Chapter 2

### ISSUE THREAD

**Issue by BuildAndDie** [openlegend/core-rules#438]
I know that we had talked about it @brianfeister , that Legend Points can be spent before or after your roll, and I thought you were in favor of that.

Currently on the website and the core rules on github don't indicate this, only saying "Before" in the Legend Points section.

Just wanted to re-confirm.

**Comment by brianfeister** [comment]
I did agree to you proposal it got changed back later when someone pointed out that it is completely pointless to say "before or after" because there would be no reason to roll before if you're able to roll after.

Also, I just realized now but "after" doesn't work for disadvantage. If I have disadvantage 3 and roll

> Attribute 5 (2d6), disadvantage 3
> d20 + 5d6KL2

Then there's no way for me to figure out which dice are "keepers" when I spend 3 legend points to negate the disadvantage.
