### ISSUE TITLE
Ferocious Minions prerequisites

### ISSUE THREAD

**Issue by MarkVelthuis** [openlegend/core-rules#439]
I noticed that this feat now also works for "Summon Creature". The prerequisite at this moment however is only influence. In my opinion the banes and boons associated with influence aren't realy fitting with that of a summoner type character. I would like to suggest presence as possible requisite for this particular feat since it fits better with characters using leadership and inspiration to lead their minions.

**Comment by brianfeister** [comment]
Good catch, updating to the following:

---

### Ferocious Minions (I - III)

___
- **Cost:**  2 points
- **Prerequisites:**
 - **Tier 1:** Alteration 3, Creation 3, Entropy 3, Energy 3, or Influence 3
 - **Tier 2:** Alteration 5, Creation 5, Entropy 5, Energy 5, or Influence 5
 - **Tier 3:** Alteration 7, Creation 7, Entropy 7, Energy 7, or Influence 7
- **Description:** Whether you are a necromancer who summons hordes of undead, an inventor who crafts autonomous defense droids, or a psychic capable of bending others to your will, minions are exceptionally strong under your command.
- **Effect:** Creatures under the effects of your _charmed_ or _dominated_ banes, or those created by your invocation of the _summon creature_ boon, gain advantage 1 on all attack rolls to protect you or act in your favor for each tier of this feat you possess.

**Comment by oconnor0** [comment]
Not Presence 3/5/7 as well?

I could see Deception and Persuasion being the means by which a _charmed_ creature acts extra ferocious.

**Comment by brianfeister** [comment]
@oconnor0 Not in this case. You have to have the invoking attribute, and deception and persuasion aren't among them

**Comment by brianfeister** [comment]
I've simplified it to just be the following, since attribute 3 is not sufficient to invoke the **Summon Creature** boon at all 


### Ferocious Minions (I - III)
___
- **Cost:**  2 points
- **Prerequisites:**
 - **Tier 1:** Invoking Attribute 4
 - **Tier 2:** Invoking Attribute 5
 - **Tier 3:** Invoking Attribute 7
- **Description:** Whether you are a necromancer who summons hordes of undead, an inventor who crafts autonomous defense droids, or a psychic capable of bending others to your will, minions are exceptionally strong under your command.
- **Effect:** Creatures under the effects of your _charmed_ or _dominated_ banes, or those created by your invocation of the _summon creature_ boon, gain advantage 1 on all attack rolls to protect you or act in your favor for each tier of this feat you possess.

**Comment by ucffool** [comment]
I think I'll need to update the filter to include the new wording, _Invoking Attribute_ to get ready for when this is pushed.

**Comment by brianfeister** [comment]
> it makes it impossible to filter 'feats I have the prerequisite for' because it is dependent on something else... I can't think of the word.

I'm a bit myopically focused on print edition stuff right now, but that's a good point and it had floated through my head before. Will definitely make it explicit in the YML

**Comment by MarkVelthuis** [comment]
Interesting change. I was told the reason the actual summon creature invoking attributes weren't used for this feat because it would be particularly powerfull (compared to charm and dominate). 

As for the invoking attribute requiring at least 4 due to summon creature needing at least that much to be invoked, this is not the case for the charm/dominate banes (these have a minimum of 3).

**Comment by brianfeister** [comment]
@MarkVelthuis I had considered that this was SUPER powerful as I was reviewing it, however, the conclusion I came to is that "Summon Creature" requires invocation just like _charmed_ and _dominated_ do. The notable difference is **Boon Focus (Summon Creature)**, so in that case the bonus applies without a chance of failure. But that's only for a single creature, with **very** low HP, so that seems clearly balanced against _dominated_ targeted on a bear or something. 

The place where this gets _really_ broken is the build that takes: **Boon Focus (Summon Creature)** + ** Multi-Target Boon Specialist II** + ** Multi-Target Boon Expert** + **Superior Concentration II**

That's a long road to get there (have to be at least 5th level to take all of the above and also **Ferocious Minions I**), and I feel like by 5th level, I can find alot of degenerate and broken things happening in many of the builds if I'm looking for them.

**Comment by MarkVelthuis** [comment]
Thanks for the clear explenation. 

What about the change from tier 1 now requiring an attribute of 4 while the charm and dominate banes require just 3 ?

**Comment by brianfeister** [comment]
Nah, we're good, thanks
