### ISSUE TITLE
Declare Power Level after rolling for banes and boons?

### ISSUE THREAD

**Issue by istabosz** [openlegend/core-rules#44]
@brianfeister There have been a few discussions about changing the bane/boon process to the following instead of determining your power level first:
1) Name the bane/boon
2) Make action roll
3) Determine Power Level

I like this change, and I think you do too, but I just wanted to confirm before I make it official.

**Comment by DMsShadow** [comment]
I've been debating this as a house rule for a while. A few players have done it this way by accident (in play by post game) and I just went with it to not disrupt the game flow. It works as long as you stick to the power level restrictions.

**Comment by brianfeister** [comment]
Yeah, I think we should make it explicit in the rules that this happens (if you WANT the lower PL effect) automatically. :)

**Comment by DMsShadow** [comment]
I think it works to allow them to use the other tier, otherwise I've seen the odd player use a lower PL to hedge their bets. If you see what I mean.

**Comment by WarthogRoadkil** [comment]
I think this is a good way of enforcing Every Roll Matters. Instead of getting a lame roll and doing nothing, you have a chance of nabbing a lower PL of the boon you're doing. This could be quite humorous for something like shapeshift. I want to morph into a tiger, but I didn't make it, so I'm going to shift into a house cat instead!

**Comment by brianfeister** [comment]
:) ... yeah, this one is on the books, not really any discussion needed - lots of good reasons to do this.

**Comment by istabosz** [comment]
Let it be so. Updated.
