### ISSUE TITLE
Shapeshift, won't mess with layout much at all

### ISSUE THREAD

**Issue by BuildAndDie** [openlegend/core-rules#456]
So, I feel like it has been discussed before, but didn't see it in the closed issues.

this line:

> so humanoids and animals are both mammals and therefore can be shifted between.

Not all animals are mammals, so that statement, along with the whole line is a lot of confusion. Not sure if mammal was intended, since I think a lot of people might want to turn into birds, which aren't mammals, but are animals. And has VanGo pointed out in mod chat, this makes the PL 5 restriction removal weird that allows flying.

Yes there are some mammals like Pegasus that could have flying, but I feel that was put in there for birds more than Pegasus. Could be wrong though.

A simple rewording of:
> Humaniods belong to the Animal category and therefore can be shifted between.

I think is one way to fix it without much change at all. That would also make the follow line make more sense and possibly create less confusion for people that read it:

> However animals, dragons, plants, elementals, and oozes all have different physiologies, so they cannot be shifted between.

Though honestly, not sure why Dragons have that much different physiologies than animals either. You can't gain their extraordinary stuff until PL 7 anyways, and even if they have an Attribute of 9/10, you can only have a max value of that attribute equal to the Alteration Score of the one doing the shapeshift.

**Comment by JVanGo** [comment]
I also add that there is an arbitrary rule in there, which isn't applied to any boon, as far as I can tell: 

> You or a willing creature you touch transform into a creature whose highest attribute is less than or equal to your Alteration score.

Is it really necessary to create a "range: touch" exception for a single boon? Why aren't we using the regular boon invocation rules?

**Comment by BuildAndDie** [comment]
Just noticed another little problem with Shapeshift in the wording for PL7

> Power Level 7 - Gain all extraordinary attributes possessed by the target. If both forms have an Alteration attribute, the target chooses between the two scores.

So, the intent, as I remember it from our discussions so long ago, was that at PL7, you are able to get the extraordinary attributs of the thing you shapeshift into at that point. However, with the word "Target" up there, it seems to indicate the original creature you targeted rather than what you shapeshifted them (or yourself) into.

I think it is suppose to say:

> Power Level 7 - Gain all extraordinary attributes possessed by the new form. If both forms have an Alteration attribute, the target chooses between the two scores.

since "target" in all the other Power Level mentions are referring to the target of the boon rather than what they shapeshift into.

@brianfeister does that sound right?

**Comment by istabosz** [comment]
Looking this boon over, I also noticed a line that I don't quite get "Your Alteration score for the purpose of this boon is limited to the maximum attribute score permitted by your level." I think your score in any attribute is limited by the maximum, right? I mean, that's why it's a maximum. Unless I'm completely missing something.

Taking all the feedback here into account, here' my new proposal for Shapeshift:


- **Duration:** Sustain Persists
- **Invocation Time:** 1 Major Action
- **Power Level:** 2 / 3 / 4 / 5 / 6 / 7 / 8
- **Attributes:** Alteration
- **Description:** A target's physical structure is temporarily altered, allowing it to assume the form of potentially any creature no matter how fantastic or exotic. Common examples of shapeshifting include lyncanthropes (such as werewolves), amorphous alien lifeforms, dopplegangers, and certain types of druids.
- **Effect:** The target transforms into a creature whose highest attribute is less than or equal to your Alteration score. With the exception of Alteration, all of the target's extraordinary attribute scores drop to zero, and they acquire the Agility, Fortitude, Might, and Perception attributes of the new form.

 The GM, not the player, is responsible for deciding the attributes and abilities of creature. It is recommended that this creature follow the guidelines established by the "Simple Build" section for creating NPCs in Chapter 8: Running the Game.

 In order to keep track of hit points, the target should record the total damage they have suffered. When transforming, damage remains with the character even if their maximum hit points change. For example, Vera has a max HP of 20 but is turned into a dragon and her Fortitude increases from 5 to 9, increasing her hit points to 28. During combat, she suffers 10 damage. When she later transforms back into her human form, the 10 damage remains and is subtracted from her new maximum, leaving her with 10 out of 20 hit points. Additionally, if the shift would reduce the target's hit points to less than 1, the target's hit point total becomes 1 instead.

 Limitations are applied starting at power level 2 and are gradually removed at higher power levels:
 - **Power Level 2** - The new form cannot be a different size than that of the target. It must possess similar physiology to the target. Examples of different physiology classifications include animals, plants, elementals, and oozes. This list is not exhaustive, and the GM has final say as to what forms are allowed. The target does not gain alternate forms of movement (flight, swimming, climbing, burrowing, etc.). The target does not gain extraordinary attributes of the new form (hence, they cannot inflict banes that rely on the creature's extraordinary attributes).
 - **Power Level 3** - Shapeshift into a creature between half and double the target's original size. Gain any non-flight movement modes of the new form.
 - **Power Level 4** - Shapeshift into a creature between one quarter and quadruple the target's original size.
 - **Power Level 5** - Gain the flying movement mode of the new form, if applicable.
 - **Power Level 6** - Shapeshift into a living creature of a different physiology, such as an elemental, ooze, or a plant.
 - **Power Level 7** - Gain all extraordinary attributes possessed by the new form. If both forms have an Alteration attribute, the target chooses between the two scores.
 - **Power Level 8** - Shapeshift into a creature of any size.

- **Special:** Shapeshifting into a specific creature (attempting to impersonate them) requires a Deception action roll which is opposed by Perception attribute of anyone who sees the shapeshifted creature. In addition, at power levels 4 and lower, the target does not gain mastery over any special movement modes granted by the new form. As such, the movement speed is cut in half for movement modes not native to the original form, and the GM may rule that certain actions, such as swimming in combat, suffer disadvantage on relevant action rolls.


@brianfeister If you think that looks good, I'll leave implementation to you, because I don't want to screw up the layout

**Comment by BuildAndDie** [comment]
Very nice. Big question is if it messes with layout and sends @brianfeister over the edge and we all pay for it via death in our sleep or not.

**Comment by brianfeister** [comment]
@istabosz the weird attribute limit wording was from @EliManthey

**Comment by JVanGo** [comment]
Wasn't it to still be able to use your alteration attribute for other stuff when shapeshifted? I think some found it strange that you would lose your shapeshifting abilities, while shapeshifted or something along those lines...

**Comment by BuildAndDie** [comment]
The creature you transform into could have a higher level.

The idea was to limit you, so that no attribute could be higher than YOUR level, independent of what you transform into.

So if I transform into a creature that has 8 Alteration, whereas I only have 7, it would drop the score down to 7 for purposes of me using it in that form.

Same with if I switched into a creature that had 7 Might, but I was only level 3. I would only be able to use Might at 6 in that case, b/c of my level.

I believe this was the reasoning behind some of that at one point of time.

I thinkt his was before the "you can't transform into a creature that has a higher attribute score than your alteration score" existed though?
