### ISSUE TITLE
Multi-Bane Specialist?

### ISSUE THREAD

**Issue by oconnor0** [openlegend/core-rules#457]
**Multi-Bane Specialist**

> You are able to inflict both banes with a single attack.

This would seem to indicate that either a damaging attack or a bane attack could be used.

> If the banes target different defenses, you choose which defense your attack targets.

But that text seems to indicate making a bane attack since banes have specific rules around which defenses they target while damaging attacks do not.

> In order to benefit from the bane focus feat when using a multi-bane attack, you must possess bane focus for both banes.

This would seem to indicate that a damaging attack can inflict two banes. But perhaps only on 5+ damage? As I read it, **Multi-Bane Specialist** allows exceptional success to inflict both banes.

Either way, this has caused some confusion to me and others in the Discord chat. Some clarification around what kinds of attacks would be greatly appreciated. :)

Edit: Bane attacks target defenses not attributes.

**Comment by BuildAndDie** [comment]
> But that text seems to indicate making a bane attack since banes have specific rules around which attributes they target while damaging attacks do not.

@oconnor0 actually, that's not true. You are thinking for Might and Agility:

> Once you have chosen your attacking attribute, determine an appropriate defense (Guard, Toughness, or Resolve) to use as the Challenge Rating for your attack, as follows.
Physical attacks always target Guard.
Non-physical attacks are more open-ended and often require the GM to decide the type of defense targeted using the following guidelines [...]

However, there is certainly room in the way multi-bane specialist is worded to rule either way for it. My first inclination was the same as yours. On 10+ without bane focus, on 5+ with bane focus you can do both banes on damaging attacks.

After all, that is an expenditure of 9 feat points to be able to do 2 banes on a damaging attack of 5+

Compare to Crushing blow + Overpower Strike. That is 5 feat points to do 2 banes on a successful hit (matching their defense score). And since those are lower level banes (Forced Move + Knockdown), makes sense it would cost a little less with what you can do with Mulit-Bane.

**Comment by oconnor0** [comment]
@BuildAndDie That's not what I said. Bane attacks target specific defenses - like a bane attack to inflict slowed would always be, e.g. Energy vs Guard. Damaging attacks do not have specific rules for which defenses they target; it could be Energy vs Guard, Toughness, or Resolve.

**Comment by brianfeister** [comment]
The reason the text implies that this feat can be used with either a Bane Attack **OR** a Damaging Attack is because, both are allowed. 

Thank you for submitting your opinion that the text does not effectively convey this. We will have to agree to disagree.

Here is the current text:

> **Effect**: Choose two banes that you are able to inflict and that share a common prerequisite attribute. You are able to inflict both banes with a single attack. 

Both bane attacks and damaging attacks are of the "attack" type. This is not ambiguous.

> The required attribute score for combining the banes is equal to the sum of their power levels (e.g., combining knockdown and slowed, both power level 1, would require an attribute score of 2). If the banes target different defenses, you choose which defense your attack targets. 

You choose which defense is quite clearly talking about Bane Attacks, since damaging attacks don't let the player choose and the "target different defenses" clause wouldn't be germaine.

> On a successful attack roll, the target is inflicted with both banes. They each persist independently of one another and must be resisted separately.
> **Special**: In order to benefit from the bane focus feat when using a multi-bane attack, you must possess bane focus for both banes.

**Comment by oconnor0** [comment]
> You choose which defense is quite clearly talking about Bane Attacks, since damaging attacks don't let the player choose and the "target different defenses" clause wouldn't be germaine.

Why not say "you choose which defense your bane attack targets" to clarify this applies only to bane attacks?

> Special: In order to benefit from the bane focus feat when using a multi-bane attack, you must possess bane focus for both banes.

Bane Focus only applies to damaging attacks so a "multi-bane attack" introduces extra confusion; what about changing the above text to say:

> Special: In order to benefit from the bane focus feat when making a damaging attack, you must possess bane focus for both banes.

**Comment by brianfeister** [comment]
Alright, that works.

**Comment by istabosz** [comment]
@oconnor0 said:
> Bane Focus only applies to damaging attacks so a "multi-bane attack" introduces extra confusion

But bane focus doesn't only apply to damaging attacks. Bane focus provides advantage 2 on bane attacks.

**Comment by oconnor0** [comment]
> But bane focus doesn't only apply to damaging attacks. Bane focus provides advantage 2 on bane attacks.

Ah, so it does. My suggestion above is inaccurate then. Perhaps:

Special: In order to benefit from the bane focus feat when making an attack, you must possess bane focus for both banes.

**Comment by istabosz** [comment]
Sorry if I'm missing something, but I'm not seeing how that adds anything that the original text doesn't already indicate:

> In order to benefit from the bane focus feat when using a multi-bane attack, you must possess bane focus for both banes.

**Comment by oconnor0** [comment]
My concern with "multi-bane attack" is that language indicates making a bane attack because damaging attacks do not declare banes before the roll but only inflict them on an extraordinary success (or a boon focus success). On the other hand, Multi-Bane Specialist allows making a bane attack that will inflict two specific banes; it's a "multi-bane attack" before dice are rolled.

**Comment by istabosz** [comment]
I'm still not seeing it. The rules say that in order for this feat to work with bane focus, you have to have bane focus in both banes that you want to inflict. That rule stands whether you are doing a bane attack or inflicting the banes via an exceptional success on a damaging attack.

**Comment by BuildAndDie** [comment]
You aren't seeing it, just like I didn't see it @istabosz , however that doesn't mean there isn't confusion with the wording. SEVERAL people have come asking about this, and thinking that they can ONLY do a bane attack for Multi-Bane Specialist, and not via doing 5+ damage (if you have bane focus on both) or 10+ damage otherwise.

The confusion is in the original line where it says "mulit-bane attack", this makes it seem like it has to be a BANE attack, just b/c the name is multi-bane.

> In order to benefit from the bane focus feat when using Multi-Bane Specialist to perform an attack, you must possess bane focus for both banes.

**Comment by oconnor0** [comment]
I've been trying to think of how to better explain my confusion for how this rule is worded, but I'm not finding a better explanation. I recognize that, at this point, if I don't have an obvious improvement to the rules text, further discussion is kind of pointless since it's not going to change.

I know this is slightly off topic, but it is obvious to me why bane focus in both banes is needed for multi-bane specialist to apply to a damaging attack - so they inflict together. I do not understand why bane focus in both banes is needed for multi-bane specialist to apply to a bane attack - bane focus in one of the banes would grant advantage 2 on bane attacks; bane focus in both of the banes would grant advantage 4 on bane attacks.

**Comment by BuildAndDie** [comment]
@oconnor0 

You can't gain the Advantage 2 to the bane attack unless you have BOTH bane focuses. It's not that you get Advantage 4 from it if you have both.

**Comment by oconnor0** [comment]
@BuildAndDie Two things:

1. I recognize that rules-as-currently-written, you gain no advantage on bane attacks from bane focus unless you have it for both banes.

2. Why wouldn't you get advantage 4 from having both?

**Comment by BuildAndDie** [comment]
@oconnor0 

You can't get the benefit of 1 Bane Focus unless you have Both, so it doesn't double stack. Having it on both banes means you get THE benefit of bane focus. It is just one attack, after all, and you only pick, out of the two, one of the defenses. That much additional advantage would be very powerful.

Same thing with Two-Handed Brute. You don't get the Advantage 1 from two-handed twice, and then dual wielding to equal 3 advantage, you just get a total of 2 advantage from it.

**Comment by brianfeister** [comment]
There's WAY too much discussion on this thread.
