### ISSUE TITLE
Reference to "standard movement" is not clear

### ISSUE THREAD

**Issue by brianfeister** [openlegend/core-rules#46]
It doesn't even matter if this is incorrect, because I've heard it a million times thus far, get asked often. If it's there, we need to clarify and make it more prominent, maybe with character creation? I don't know. And if it's not there, let's add it.

**Comment by brianfeister** [comment]
https://www.reddit.com/r/openlegendrpg/comments/58rwho/how_to_calculate_speed_or_movement_square_amount/

**Comment by Groumy** [comment]
I think that in chapter 6, Combat, under Move Actions ; Move your speed would be a great place.

Earlier than that it's just noise, because we don't have multiple races that all have their own speed, so there's no benefits of calling it out in the character creation chapter. 

In fact it will be harder to reference at the table (if need be, since a simple enough think to remember, but it could happen).

**Comment by istabosz** [comment]
Resolved. I've added 30' base speed to both Character Creation and the Combat chapter
