### ISSUE TITLE
Unarmed attacks should have at least one property

### ISSUE THREAD

**Issue by DukeAnax** [openlegend/core-rules#49]
As far as I can tell weapon attacks and damage are only based on the Attribute they use.
Two handed and swift weapons get advantage, but that's it. 

This is especially noticable with bare hands being exactly the same as a one handed longsword.

Not sure what to do about that though.

**Comment by brianfeister** [comment]
Yeah, probably need to add the **Swift** property to Unarmed, I supose.

**Comment by Groumy** [comment]
Unless you have some very serious training, Unarmed Attack are less then weapon attacks ... if not who would ever created a weapon ?!

I think to balance it out, unarmed attack should have dsisadvantage 1. 

That could be cleared out for a monk with the Attack Specialization feat, showing the actual training of the monk in unarmed attacks.

**Comment by DMsShadow** [comment]
I was going to suggest that there must be some way to make it less advantageous to use an unarmed attack without being overly complex, but then with feats or similar to allow you to have a monk/kung fu character without again adding in too much complication. On the face of it I quite like the disadvantage idea. Curious on Brain and Ish's thoughts.

**Comment by Elvenoob** [comment]
I think the lack of negative effects when it comes to weapons vs. unarmed is simply for balance reasons, because it's so easy to get a weapon that it's pretty much trivial, so balance-wise, it shouldn't give an advantage. 

And, for any character using unarmed strikes, I guess it's just that the system assumes anyone crazy enough to enter melee unarmed has the sufficient training to fight on-par with their weapon-holding opponents.

(Also, Unarmed is currently the only attacking method with no advantageous property or boost to inflicting certain banes, so there are already disadvantages designed in to fighting melee. (And, before you mention it, remember, in the next update, the bane properties of weapons are already getting a bit of a buff, so that difference is going to be a bit more meaningful))

**Comment by DukeAnax** [comment]
Aside from swift, there should also be some grappling Boons for unarmed, like Knockdown or Forced Move. But the Point I was trying to make was more along the line of their damage being identical.

Dagger and Unarmed for example have very close fighting styles except that hitting with a Dagger, generally does more damage, mostly because it can poke through weak spots and holes in armor.
Or another pair: Maul and Warhammer, identical except that Warhammer is more expensive, though it should be better at penetrating armor. Same for Crossbow and Longbow, identical except that Longbow has more range, but Crossbow should penetrate armor.

I see a red string there: maybe we should add another weapon property: 
**Piercing**: This weapon is better at penetrating armor and lowers Armor effectiveness by half.

Such a weapon would essentially raise their damage slightly by lowering the target CR, if the target is wearing Armor.

While talking about Crossbows I got an idea for another weapon property, that could come in handy for more modern settings:
**Loaded** Attacking with a loaded weapon requires only a minor action, however reloading requires a major action.

**Comment by brianfeister** [comment]
Yeah, sorry for those who are new to the system and don't understand all of the underlying philosophy. But almost 100% of the time, Open Legend defines differences between things by making other things better, rather than making one particular thing worse. Everything is "Additive", not "subtractive" (penalty-based). 

So no, we won't be implementing a penalty for unarmed attacks. In Open Legend, there are no Weapon or Style "Proficiences" so the game assumes that whatever attribute you use represents the training that you have chosen for your character's backstory. Anyone who think unarmed attacks can't do lots of damage has never been strangled, choked, joint-locked, or had a pressure point applied to them. Remember that if you chose to play a character that uses Agility and says that you are trained in pressure points and vital strikes, this is the whole point of the system. You only add feats (e.g. **Attack Specialization**) if you want to be even more brutal in dealing out damage with that kind of damage.

The advantage of never losing your weapon is relatively small, so I'm not going to punish monks. I'm pretty sure that the only thing we will do here is add **Swift** to unarmed since, truly daggers are not faster than fists. 

Rather than add other properties to unarmed, we will keep it balanced -- with just **Swift** and not losing your weapon are the advantages, it is a FREE weapon, after all.

If you want to be a monk that grapples, **Bane Focus: Immobile** is the path for you. You get Advantage 2 to invoke the bane and you can automatically grapple on a damaging attack when you deal 5 or more damage. 

@DukeAnax - I now we already do have a bunch of properties, but **Piercing** is far more complex than Open Legend aims to be. **Loaded** is interesting but far too open for abuse, since you can pre-load a large number of weapons.

**Comment by istabosz** [comment]
I just added unarmed strike to the melee weapons table. I made it Precise and Forceful, Swift 2. If that sounds good to you @brianfeister , go ahead and close this one.

**Comment by brianfeister** [comment]
👍
