### ISSUE TITLE
Does Fear bane only affect the target's movement?

### ISSUE THREAD

**Issue by istabosz** [openlegend/core-rules#6]
https://github.com/openlegend/core-rules/blob/master/banes/banes.yml#L194

Wording wasn't clear. Can the target still use their normal action? Or do they have to spend their entire turn moving away?

**Comment by brianfeister** [comment]
Yeah my thought was not to make it too overpowered, essentially you have to spend your movement moving away, but can still make a fighting retreat. That was the thought, what do you think?

**Comment by istabosz** [comment]
Makes sense to me, as long as it fits in the right power level compared to similar banes.

**Comment by istabosz** [comment]
Since the target still gets its other actions as normal, I assume we should make this one resist ends and get rid of the free resist roll too, right?

**Comment by brianfeister** [comment]
Having second thoughts just now. Maybe it should be full move away and no other actions. It kind of takes you out of a fight completely. The best comparison in that case would be `Incapacitated`, which takes you out of the fight but is fragile in the sense that you can be easily roused from it. But with `Incapacitated`, you can be coup de grace'd which is deadly. In this case, running away takes you out of the fight but also gets you to a point where you can't be attacked by your enemy because you're out of range. The two seem close to equal in power as major game-changers at Power Level 5.

**Comment by istabosz** [comment]
Yea, I like that better too.
