### ISSUE TITLE
Sync between core rules and other materials.

### ISSUE THREAD

**Issue by LordRyst** [openlegend/core-rules#69]
I've noticed that "A Star Once Fallen" doesn't match all the current core rules. Although a minor issue, wouldn't it be awesome if I could download a nightly build of the adventure and get the latest rules? I have no idea what tools would be required, but it seems that with a living document of this size, and the ability of others to include small portions in their projects, if we had a standard way to select sections and allow people to pull sections when they change? Anyone have ideas? This includes a request to include the adventure here, as it is free forever, might as well get patched too. I'm just trying to avoid double work and sync issues.

**Comment by raihje** [comment]
It could just be a separate project, that is run exactly like the site, but is referenced on the site (ie a section of the site could be used for the adventure similar to the core rules are.) That way it's separate enough people can work on it (separate project on github) but it's cohesive in one place. Then if they want to update a PDF (not sure how programatically that can be done) they can periodically.

**Comment by Odog4ever** [comment]
I actually listened to a podcast that was running "A Star Once Fallen" and I was confused why they were having some issues (like not being able to heal because no one put points into Creation). I just assumed they weren't following the rules until I downloaded the module myself and low and behold the Heal boon is limited in a way it is not compared to the online rule set. That quick start is going to need a update sooner rather than later.

**Comment by brianfeister** [comment]
@Odog4ever is right. @istabosz we need to fix inconsistencies. In this case, I've added `Presence` and `Logic` as attributes with access to the `Heal` boon, restoring HP, provided it's not lethal damage.

**Comment by LordRyst** [comment]
If the source for the PDF versions can pull from html or yaml, it should be possible to point to github and pull recent changes. If that is too course, it might be worth subdividing feats, boons, and banes to individual pages each. Either way, these features have already been written and updated, and future sources need a way to do a nightly build as it were.

**Comment by brianfeister** [comment]
@LordRyst We're talking about "A Star Once Fallen" here and fixing inconsistencies with a completely separate text. So, since it has an actual release / publication cycle, we don't want to automate it updates to pull from a source file. Your suggestion is fine for the openlegendrpg.com website, but that's not actually what we're talking about here.

**Comment by raihje** [comment]
@brianfeister So you want to release something like an Errata (similar to other systems, I believe 5E and WoD both have Erratas for their books/PDFs) That could be feasible.

**Comment by brianfeister** [comment]
Errata releases are a fine suggestion but that doesn't change anything about the fact that automating the transfer of fragments in one document into fragments of another document is not an ideal task for automation.

**Comment by raihje** [comment]
That's perfectly fair, when I brought up that they could be synced I was meaning that it would be a section on the site. (similar to core rules) An errata may be more feasible in the short term though.

**Comment by brianfeister** [comment]
Gotcha - that makes sense. Remind me if I forget.

**Comment by brianfeister** [comment]
Closed due to automated builds being suboptimal for the task at hand.
