### ISSUE TITLE
Reconsider how resisting the Phantasm bane works.

### ISSUE THREAD

**Issue by istabosz** [openlegend/core-rules#7]
https://github.com/openlegend/core-rules/blob/master/banes/banes.yml#L283

It seems like phantasm favors the target too much. First, the attacker has to overcome their resolve. Then the target gets a free resist roll every round. And finally, the target gets an extra roll whenever it interacts with the illusion. Conceivably, a target would always be interacting with an illusion.

I propose we just make this like every other bane in that we keep it at the resist roll to end.

**Comment by brianfeister** [comment]
Wow, I never actually played by my own rules, didn't remember I gave a free resist roll each round.  I agree, you make a very good point about 

> conceivably, a target would always be interacting with an illusion

So yeah, just making it Resist ends seems ideal

**Comment by DMsShadow** [comment]
Someone just cast phantasm in my game and I was trying to get my head round this one too. I'd agree with making it a resist on interacting. But wanted to ask, if the attacker isn't sustaining the phantasm, surely it disappears, so a resist roll isn't needed?

Get Outlook for iOS




On Sat, Jul 9, 2016 at 5:46 AM +0100, "Brian Feister" <notifications@github.com> wrote:





Wow, I never actually played by my own rules, didn't remember I gave a free resist roll each round.  I agree, you make a very good point about

> conceivably, a target would always be interacting with an illusion

So yeah, just making it Resist ends seems ideal

---

**Comment by brianfeister** [comment]
This is amazing! @DMsShadow how did you even know we were chatting on here? My mind is blown right now. You're everywhere at once!

Well, the thing about Phantasm is that sustaining as a requirement is a bit too generous to the invoker of the bane. 

I think @istabosz's point about having it be "resist ends" is interesting if we're talking about players controlling their characters without having to "think like" their characters.

But I agree with @DMsShadow's contrary point here, as well.

Here's my new proposal: We definitely need to get rid of the "free resist roll every round" part. So that's agreed upon by all. As I'm typing this I'm vacillating between the two opposite suggestions by you two. 

Here's my dilemma: if we make it `Resist Ends`, then we have a weird way of encouraging metagame thinking. This is especially important from the GM's perspective, as he will use illusion and players will need to constantly say "I attempt to disbelieve" and if they ever forget to, they're screwed. 

On the other side of the fence, Ish raises a good point about "always interacting" with an illusion. It's true. Even if it's something simple like the accuracy of a raven's call, hearing it exposes the possibility of detecting the falsehood.

So, I'm now stuck because both seem quite problematic.

... Ok, writing later on now, I think `Resist Ends` is the way to go, simply because it's the simplest. It has the fewest dice rolls involved (not automatic every turn), it helps the GM because they can use Phantasm against the players and it is congruent with how I've always used the ability (frequently) in my campaign - which is to allow the GM to make up stuff, pretend it's real, and then let the players figure it out naturally in a narrative context. Other options seem to push to much in the opposite direction of "every roll matters" where you're just constantly rolling dice.

Thoughts?

**Comment by istabosz** [comment]
I like making it resist ends because it forces players to actively disbelieve or investigate. So, until they have an inkling that there is an illusion, they'll just be treating it as real based on the  GM's description of things.

**Comment by DMsShadow** [comment]
Stick with Resist Ends. Like Ish says it fits better narratively and as you pointed out it removes extraneous dice rolling.
On the point of me being everywhere, I just got an email with this discussion, but I have no idea how I managed it.

Get Outlook for iOS




On Sat, Jul 9, 2016 at 6:28 PM +0100, "istabosz" <notifications@github.com> wrote:





I like making it resist ends because it forces players to actively disbelieve or investigate. So, until they have an inkling that there is an illusion, they'll just be treating it as real based on the  GM's description of things.

> On Jul 9, 2016, at 12:36 PM, Brian Feister <notifications@github.com> wrote:
>
> This is amazing! @DMsShadow how did you even know we were chatting on here? My mind is blown right now. You're everywhere at once!
>
> Well, the thing about Phantasm is that sustaining as a requirement is a bit too generous to the invoker of the bane.
>
> I think @istabosz's point about having it be "resist ends" is interesting if we're talking about players controlling their characters without having to "think like" their characters.
>
> But I agree with @DMsShadow's contrary point here, as well.
>
> Here's my new proposal: We definitely need to get rid of the "free resist roll every round" part. So that's agreed upon by all. As I'm typing this I'm vacillating between the two opposite suggestions by you two.
>
> Here's my dilemma: if we make it Resist Ends, then we have a weird way of encouraging metagame thinking. This is especially important from the GM's perspective, as he will use illusion and players will need to constantly say "I attempt to disbelieve" and if they ever forget to, they're screwed.
>
> On the other side of the fence, Ish raises a good point about "always interacting" with an illusion. It's true. Even if it's something simple like the accuracy of a raven's call, hearing it exposes the possibility of detecting the falsehood.
>
> So, I'm now stuck because both seem quite problematic.
>
> ... Ok, writing later on now, I think Resist Ends is the way to go, simply because it's the simplest. It has the fewest dice rolls involved (not automatic every turn), it helps the GM because they can use Phantasm against the players and it is congruent with how I've always used the ability (frequently) in my campaign - which is to allow the GM to make up stuff, pretend it's real, and then let the players figure it out naturally in a narrative context. Other options seem to push to much in the opposite direction of "every roll matters" where you're just constantly rolling dice.
>
> Thoughts?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or mute the thread.
>


---
