### ISSUE TITLE
Dual Wielding - Currently No Incentive

### ISSUE THREAD

**Issue by raihje** [openlegend/core-rules#73]
From what I've read, you can get a 2 point feat that lets you draw an extra weapon on your turn, and you can wield 2 one-handed weapons. However mechanically there's nothing supporting this aside from an extra possible bane if they choose an asymmetric idea. Currently you need to emulate dual wielding entirely with feats, which is expensive for the rogue with 2 daggers, or the ranger with 2 shortswords or scimitars. Things like multi-target or multi-attack specialist or fast draw.

Two-Handing gives adv. 1. to melee attacks.
Shields offer adv. 1 to defend actions.

Perhaps allow dual wielders to get one extra attack, neither attack would have adv. or dis. but it'd take their move (or minor?) action for the second attack to simulate them feinting/flourishing their weapons. This way the feats are still relevant, but dual wielding has a benefit. two weaker attacks instead of 1 strong one, any more and they would need to invest feat points.

Alternatively (and more simple), give them adv. only on the d20, similar to resilient for melee attacks to simulate the idea of 2 smaller blades having a better chance to nick the oppoonent or carve them deftly around their defenses.

**Comment by Hvalfisk** [comment]
Simply give advantage 1 to melee attacks when dual wielding.

**Comment by raihje** [comment]
I was trying to set them apart from other benefits, to make different fighting styles interesting but that works too I guess, lol.

**Comment by Groumy** [comment]
My first reflex would also be to simply grant advantage 1. That advantage will counter some disadvantage level of Multi-Target actions, or Multi-Actions, which is fitting.

Narratively, it's not because you dual wield that you actually make to attacks. You could use one to deflect the opponent weapon and make an opening for the other, etc.

That will also keep the action economy intact. It's for that reason that D&D 5e only grant a second attack at the cost of your bonus action and deny you your stat modifier on damage. That in 4th it was simply flavored in part of you encounter powers and granted a secondary target and that in 3rd it was with a great deal of penalty that required multiple feats to get rid of.

**Comment by brianfeister** [comment]
Dual-wielding is covered by the hugely expensive (and correctly priced because of the incredible power of two attacks) [Multi-Attack Specialist feat](http://www.openlegendrpg.com/feats/multi-attack_specialist).

You can wield two weapons for flavor and choose to use only one of them (your choice), but to actually dual-wield this feat is the only way. 

In Open Legend, an additional attack is FAR MORE deadly than in other systems so we won't be giving them out without a hefty price. I **highly** advise GMs not to hand them out for a cost lower than what the feat sets forth.

**Comment by brianfeister** [comment]
@istabosz @Groumy @raihje -- I've warmed up to this idea over time. I suppose it does make sense that a fighter who chooses not to use a shield is imposing a penalty on themselves. As has been stated already, I think this would need to be protected from abuse via a `Melee Only` clause so that dagger wielders aren't trying to get freebie Advantage on ranged dagger throws. 

But yeah, I suppose it makes sense both mechanically to reward the sacrifice of armor bonus, and also narratively, wielding two light weapons might not mean you're **awesome** with both, however you have twice as many "holes" in the opponent's defense that you can capitalize on when there are two separate points of threatening.
