### ISSUE TITLE
Rules provisions for size, vision, etc.

### ISSUE THREAD

**Issue by raihje** [openlegend/core-rules#83]
So currently, afaik there aren't really any rules regarding size, vision (ie infra/dark vision?) and other details that are important to characters. Size has a few mentions of "size categories" or "size classes" but I didn't see them really defined anywhere. I was thinking infra could be a perk - It only lets you see things that give off heat, which limits it quite a bit (vs say, undead, or trying to navigate a dark dungeon.) darkvision could be a feat on the other hand, to represent it's wide-spread utility.

At first I thought maybe just use the same scale/vision/environmental ideas as 5E but I though I could simplify them a bit here and you guys can offer some feedback.
Size: *1/4 means 1 per 4 squares, for example 2x2 or 1x4
4/sq Tiny/Diminutive.Fits in the palm of your hand, size of your fist, etc. Bats, rodents, etc.
1/sq Small/Short: Dwarves, Halflings, Some settings' elves, etc..
1/sq  Medium/Average: Humans, probably most players fall here.
1/4sq Creatures that tower over the common man, ogres, trolls and the like.
1/9sq Small Dragons, supernatural beings like Ents, etc.
1/16sq Truly horrifying/magnificient creatures, ancient dragons, behemoths that shake the ground when they walk.

Vision:
Blinding: Dis. 1 Bright: Fine. Dim/Difficulty: Dis. 1 Dark/Missing one or more senses completely: Dis. 2
Environment: There aren't really any environmental effects, this would be somewhere the DM could just rule obscurity as above, or offer disadv. on certain types of checks (ie sight/hearing in a windy blizzard, might on the frozen surface of a lake pulling shots to avoid breaking through, etc.)

**Comment by Groumy** [comment]
It make sense to use the size categories that every one is used to since the D20 era. But on the other hand that sounds a lot of size category to keep track of for an otherwise rule lite system. May be we can merge them in broader categories ?!

Personally, I ruled that difference in size category should grant advantage in the right circumstances.

Like when a creature attacks a creature one size category larger it could have advantage or something. And disadvantage when you try a Immobilize bane attack on a creature larger than you with might.

The dilemma I have though is if this circumstances should or shouldn't be state. If we don't state the circumstances the rules stays easy to grasp, but it the GM that have to make judgement calls. If we do states the circumstances in which size category should grant advantage then I fear it will be hard to decide where to stop and that risk becoming a rule heavy subsystem.

Maybe there's a middle road in which we made some suggestions or the actual circumstances list will not be as big as I think it can be.

**Comment by raihje** [comment]
We need to state this stuff to some extent for shifting and other size related rules.
By keeping with the d20 people who have played other systems before will adapt quickly (since it's not really a lot of sizes. It's 6 total and you could probably get rid of the largest one.

**Comment by DukeAnax** [comment]
I think where size is used we currently have these 7 categories adding some detail it could look like this
Miniscule - 4 swarms per square -  flies, bees
Tiny - 1 swarm per square - rats, snakes, bats
Small - 4 per square - dogs, cats, gnomes (?)
Medium. - 1 per square gnomes (?) dwarfes, humans, elves
Large - 1 per 4 square - horses, trolls, oger,
Huge - 1 per 9 square - elefants, ents
Gargantuan - 1 per 16 square - dragons, giants,

**Comment by brianfeister** [comment]
I'm not planning to be this direct in answering the questions. This is an example of the rules wandering into territory where they're quantifying things that I don't want the system to quantify. 

You'll notice alot of rules text in Open Legend says "with GM approval", the GM and/or player should work out how big a creature is and the rules should stay out of the way.
