### ISSUE TITLE
Revamping the Legend Point System

### ISSUE THREAD

**Issue by Hassurunous** [openlegend/core-rules#90]
I'm going to be testing something with my playgroup: adding additional options for Legend Points. Namely, I'm thinking about giving them the opportunity to purchase feat/attribute points, to give them more of an incentive to earn those points through role-play and ingenuity. I'm curious what your thoughts are on this and how you think it could be balanced. 

Right now, my players seem to be rather disengaged with the Legend Point system, which might not be a bad thing if it isn't meant to be as powerful a source of GM motivation, but I want to use the points to encourage them to role-play their characters a bit more than they are familiar with (only 2 of the 7 have ever played a tabletop rpg before). 

I'll provide any feedback I get from the group as well as my own observations as the point system plays out. 

Thoughts on what to add/subtract from the Legend Points Shop? Balancing? Thanks!

**Comment by brianfeister** [comment]
My recommendation is to never modify the attribute / feat point economy unless you're doing it in a global way that always affects all characters equally. Don't use feat or attribute points as a reward system because players who are more shy / quiet will be punished.

If your characters aren't engaged with the Legend point system, I recommend that you make suggestions about when they can roleplay their **Flaw** in a way that would give them a Legend point. With new players, I find it best to tell them what they could do because it takes some practice to get into the groove with roleplaying so I just act as an advisor / partner for them in the beginning. 

But if you're asking about something like starting everyone at level 6 because they're all superheroes, then I say go for it -- that's totally fine!

Also, I'm going to close this issue because this is more of a discussion question rather than a rules problem that needs to be fixed. Github is for "bugs" or issues that need fixing, the community site is for general GMing style / discussions like this: https://openlegend.mightybell.com

**Comment by Hassurunous** [comment]
I should have just posted over there to begin with. Long day. My mistake.

**Comment by brianfeister** [comment]
No worries - not my intention to make you feel bad or anything, just have so much discussion on here it's tough to keep track of so I have to limit it wherever possible.

**Comment by Hassurunous** [comment]
Makes sense. Let me know if there's anything specific you want me to take a look at, especially over the weekend when I've got more free time. Going through the open issues and recent commits now to see where the action is, so to speak.
